// <auto-generated>
//   Generated by Xantham.Generator from @cloudflare/computer.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec FSharp.CloudEdge.Runtime.ComputerArtifacts

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

type WorkspaceAttributeValue = U3<string, float, bool>

[<Interface>]
type WorkspaceObserver =
    /// <summary>
    /// Wraps <c>run</c> in a span named <c>name</c>, seeded with <c>attributes</c>. The
    /// callback receives a <c>WorkspaceSpan</c> it can use to attach further
    /// attributes once the work has produced values worth recording (byte
    /// counts, exit codes, applied / skipped counts).
    /// <br /><br />
    /// Implementations must run <c>run</c> synchronously and return its result
    /// (or its promise) unchanged so the wrapping is invisible to the
    /// caller. Errors thrown by <c>run</c> must propagate.
    /// </summary>
    abstract span<'T>: name: string * attributes: ReadonlyRecord<string, WorkspaceAttributeValue option> * run: (WorkspaceSpan -> JS.Promise<'T>) -> JS.Promise<'T>
    [<ParamObject; Emit("$0")>]
    static member Create (span: Func<string, ReadonlyRecord<string, WorkspaceAttributeValue option>, (WorkspaceSpan -> JS.Promise<'T>), JS.Promise<'T>>) : WorkspaceObserver = jsNative

[<Interface>]
type WorkspaceSpan =
    /// <summary>
    /// Sets a single attribute on the span. Passing <c>undefined</c> is a
    /// no-op so callers can forward optional values directly.
    /// </summary>
    abstract setAttribute: key: string * ?value: WorkspaceAttributeValue -> unit
    [<ParamObject; Emit("$0")>]
    static member Create (setAttribute: Action<string, WorkspaceAttributeValue option>) : WorkspaceSpan = jsNative

[<Interface>]
type ResolvedS3 =
    abstract bucket: string with get, set
    abstract endpoint: string with get, set
    abstract accessKeyId: string with get, set
    abstract secretAccessKey: string with get, set
    abstract region: string with get, set
    abstract service: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (bucket: string, endpoint: string, accessKeyId: string, secretAccessKey: string, region: string, service: string) : ResolvedS3 = jsNative

/// <summary>@cloudflare/computer/artifacts</summary>
module Artifacts =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type ArtifactScope =
        | [<CompiledName("read")>] Read
        | [<CompiledName("write")>] Write

    /// <summary>
    /// Source spec for <c>import</c>. Mirrors the binding's <c>source</c> block.
    /// </summary>
    [<Interface>]
    type ArtifactImportSource =
        abstract url: string with get, set
        abstract branch: string option with get, set
        abstract depth: float option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (url: string, ?branch: string, ?depth: float) : ArtifactImportSource = jsNative

    /// <summary>
    /// Options for <c>import</c>'s target repo.
    /// </summary>
    [<Interface>]
    type ArtifactImportOptions =
        abstract description: string option with get, set
        abstract readOnly: bool option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (?description: string, ?readOnly: bool) : ArtifactImportOptions = jsNative

    /// <summary>
    /// A repo summary as returned by <c>list</c>: the binding's
    /// <c>ArtifactsRepoInfo</c> without the <c>remote</c> field, with the <c>name</c>
    /// rewritten to its local (unscoped) form.
    /// </summary>
    [<Interface>]
    type ArtifactRepoSummary =
        /// <summary>
        /// Unique repository ID.
        /// </summary>
        abstract id: string with get, set
        /// <summary>
        /// Repository name.
        /// </summary>
        abstract name: string with get, set
        /// <summary>
        /// Repository description, or null if not set.
        /// </summary>
        abstract description: string option with get, set
        /// <summary>
        /// Default branch name (e.g. "main").
        /// </summary>
        abstract defaultBranch: string with get, set
        /// <summary>
        /// ISO 8601 creation timestamp.
        /// </summary>
        abstract createdAt: string with get, set
        /// <summary>
        /// ISO 8601 last-updated timestamp.
        /// </summary>
        abstract updatedAt: string with get, set
        /// <summary>
        /// ISO 8601 timestamp of the last push, or null if never pushed.
        /// </summary>
        abstract lastPushAt: string option with get, set
        /// <summary>
        /// Fork source (e.g. "github:owner/repo", "artifacts:namespace/repo"), or null if not a fork.
        /// </summary>
        abstract source: string option with get, set
        /// <summary>
        /// Whether the repository is read-only.
        /// </summary>
        abstract readOnly: bool with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (id: string, name: string, defaultBranch: string, createdAt: string, updatedAt: string, readOnly: bool, ?description: string, ?lastPushAt: string, ?source: string) : ArtifactRepoSummary = jsNative

    /// <summary>
    /// The session-scoped client.
    /// </summary>
    [<Interface>]
    type ArtifactClient =
        /// <summary>
        /// The session id every operation is scoped under.
        /// </summary>
        abstract sessionId: string
        /// <summary>
        /// Create a repo. The returned <c>name</c> is local (unscoped).
        /// </summary>
        abstract create: name: string * ?opts: Artifacts.ArtifactClient.Create.Opts -> JS.Promise<obj>
        /// <summary>
        /// Resolve repository metadata. The returned <c>name</c> is local.
        /// Throws <c>ArtifactsError</c> (code <c>NOT_FOUND</c>) if it does not exist.
        /// </summary>
        abstract get: name: string -> JS.Promise<obj>
        /// <summary>
        /// List the session's repos, walking every page. Names are local.
        /// </summary>
        abstract list: unit -> JS.Promise<FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactRepoSummary[]>
        /// <summary>
        /// Import an external git remote into a session repo.
        /// </summary>
        abstract import: name: string * source: FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactImportSource * ?opts: FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactImportOptions -> JS.Promise<obj>
        /// <summary>
        /// Delete a repo. Returns false when it does not exist.
        /// </summary>
        abstract delete: name: string -> JS.Promise<bool>
        /// <summary>
        /// Mint a git token for a session repo.
        /// </summary>
        abstract createToken: name: string * ?scope: FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactScope * ?ttl: float -> JS.Promise<obj>
        /// <summary>
        /// List a session repo's token page (metadata only — no plaintext).
        /// </summary>
        abstract listTokens: name: string -> JS.Promise<obj>
        /// <summary>
        /// Get a single token's metadata by id. The binding has no direct
        /// accessor and no token-list cursor, so this filters the page
        /// returned by <c>listTokens()</c> and throws <c>NotFoundError</c> on a miss.
        /// </summary>
        abstract getToken: name: string * id: string -> JS.Promise<obj>
        /// <summary>
        /// Revoke a token by id or plaintext. Returns false on a miss.
        /// </summary>
        abstract revokeToken: name: string * tokenOrId: string -> JS.Promise<bool>
        /// <summary>
        /// Argv-driven entry point. The worker-backend's <c>artifacts</c>
        /// custom command dispatches through this; in-process callers can
        /// use it too when they want CLI-shaped output.
        /// </summary>
        abstract cli: input: FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactsCLIInput -> JS.Promise<FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactsCLIResult>
        [<ParamObject; Emit("$0")>]
        static member Create (sessionId: string, create: Func<string, Artifacts.ArtifactClient.Create.Opts option, JS.Promise<obj>>, get: (string -> JS.Promise<obj>), list: (unit -> JS.Promise<FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactRepoSummary[]>), import: Func<string, FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactImportSource, FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactImportOptions option, JS.Promise<obj>>, delete: (string -> JS.Promise<bool>), createToken: Func<string, FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactScope option, float option, JS.Promise<obj>>, listTokens: (string -> JS.Promise<obj>), getToken: Func<string, string, JS.Promise<obj>>, revokeToken: Func<string, string, JS.Promise<bool>>, cli: (FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactsCLIInput -> JS.Promise<FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactsCLIResult>)) : ArtifactClient = jsNative

    type RemoteAddFn = (Artifacts.RemoteAddFn.Opts -> JS.Promise<Artifacts.RemoteAddFn.Result.Item>)

    [<Interface>]
    type ArtifactsCLIInput =
        /// <summary>
        /// Argv as seen by the shell command. <c>argv[0]</c> is the group.
        /// </summary>
        abstract argv: string[] with get, set
        /// <summary>
        /// Environment variables. Reserved for future use.
        /// </summary>
        abstract env: Record<string, string> option with get, set
        /// <summary>
        /// Optional git seam used only by the <c>create</c> shorthand to register
        /// the remote. When absent, <c>create</c> skips the git step and instead
        /// reports a ready-to-run <c>git remote add</c> line.
        /// </summary>
        abstract remoteAdd: FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.RemoteAddFn option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (argv: string[], ?env: Record<string, string>, ?remoteAdd: FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.RemoteAddFn) : ArtifactsCLIInput = jsNative

    [<Interface>]
    type ArtifactsCLIResult =
        abstract stdout: string with get, set
        abstract stderr: string with get, set
        abstract exitCode: float with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (stdout: string, stderr: string, exitCode: float) : ArtifactsCLIResult = jsNative

    /// <summary>
    /// Base class for every artifacts error. The <c>code</c> field is the
    /// contract: CLI dispatchers and external callers branch on it.
    /// </summary>
    [<Interface>]
    type ArtifactError =
        abstract code: string
        abstract name: string with get, set
        abstract message: string with get, set
        abstract stack: string option with get, set
        abstract cause: obj option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (code: string, name: string, message: string, ?stack: string, ?cause: obj) : ArtifactError = jsNative
        /// <summary>
        /// Indicates whether the argument provided is a built-in Error instance or not.
        /// </summary>
        [<Import("ArtifactError.isError", "@cloudflare/computer/artifacts")>]
        static member isError (error: obj) : bool = jsNative

    /// <summary>
    /// Raised when a repo name is empty, contains a path separator, or
    /// is otherwise unusable as the trailing segment of a scoped name.
    /// </summary>
    [<Interface>]
    type InvalidRepoNameError =
        inherit FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactError
        [<ParamObject; Emit("$0")>]
        static member Create (name: string, message: string, code: string, ?stack: string, ?cause: obj) : InvalidRepoNameError = jsNative
        /// <summary>
        /// Indicates whether the argument provided is a built-in Error instance or not.
        /// </summary>
        [<Import("InvalidRepoNameError.isError", "@cloudflare/computer/artifacts")>]
        static member isError (error: obj) : bool = jsNative

    /// <summary>
    /// Raised when a session id is empty or contains a path separator.
    /// A session id becomes the leading segment of every scoped name,
    /// so it has the same shape constraints as a repo name.
    /// </summary>
    [<Interface>]
    type InvalidSessionIdError =
        inherit FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactError
        [<ParamObject; Emit("$0")>]
        static member Create (name: string, message: string, code: string, ?stack: string, ?cause: obj) : InvalidSessionIdError = jsNative
        /// <summary>
        /// Indicates whether the argument provided is a built-in Error instance or not.
        /// </summary>
        [<Import("InvalidSessionIdError.isError", "@cloudflare/computer/artifacts")>]
        static member isError (error: obj) : bool = jsNative

    /// <summary>
    /// Raised when a repo lookup misses or a token id can't be found
    /// within a repo's token list.
    /// </summary>
    [<Interface>]
    type NotFoundError =
        inherit FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactError
        [<ParamObject; Emit("$0")>]
        static member Create (name: string, message: string, code: string, ?stack: string, ?cause: obj) : NotFoundError = jsNative
        /// <summary>
        /// Indicates whether the argument provided is a built-in Error instance or not.
        /// </summary>
        [<Import("NotFoundError.isError", "@cloudflare/computer/artifacts")>]
        static member isError (error: obj) : bool = jsNative

    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        /// <summary>
        /// Build a session-scoped artifacts client over a namespace binding.
        /// </summary>
        [<Import("createArtifact", "@cloudflare/computer/artifacts")>]
        static member createArtifact (binding: obj, sessionId: string) : FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactClient = jsNative
        [<Import("runArtifactsCLI", "@cloudflare/computer/artifacts")>]
        static member runArtifactsCLI (client: FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactClient, input: FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactsCLIInput) : JS.Promise<FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactsCLIResult> = jsNative
        /// <summary>
        /// Base class for every artifacts error. The <c>code</c> field is the
        /// contract: CLI dispatchers and external callers branch on it.
        /// </summary>
        [<Import("ArtifactError", "@cloudflare/computer/artifacts"); EmitConstructor>]
        static member ArtifactError (code: string, message: string, ?options: Artifacts.ArtifactError.Options) : FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactError = jsNative
        /// <summary>
        /// Raised when a repo name is empty, contains a path separator, or
        /// is otherwise unusable as the trailing segment of a scoped name.
        /// </summary>
        [<Import("InvalidRepoNameError", "@cloudflare/computer/artifacts"); EmitConstructor>]
        static member InvalidRepoNameError (name: string, reason: string, ?options: Artifacts.InvalidRepoNameError.Options) : FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.InvalidRepoNameError = jsNative
        /// <summary>
        /// Raised when a session id is empty or contains a path separator.
        /// A session id becomes the leading segment of every scoped name,
        /// so it has the same shape constraints as a repo name.
        /// </summary>
        [<Import("InvalidSessionIdError", "@cloudflare/computer/artifacts"); EmitConstructor>]
        static member InvalidSessionIdError (sessionId: string, reason: string, ?options: Artifacts.InvalidSessionIdError.Options) : FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.InvalidSessionIdError = jsNative
        /// <summary>
        /// Raised when a repo lookup misses or a token id can't be found
        /// within a repo's token list.
        /// </summary>
        [<Import("NotFoundError", "@cloudflare/computer/artifacts"); EmitConstructor>]
        static member NotFoundError (message: string, ?options: Artifacts.NotFoundError.Options) : FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.NotFoundError = jsNative

    module ArtifactClient =
        module Create =
            [<Interface>]
            type Opts =
                abstract readOnly: bool option with get, set
                abstract description: string option with get, set
                abstract setDefaultBranch: string option with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (?readOnly: bool, ?description: string, ?setDefaultBranch: string) : Opts = jsNative

    module ArtifactError =
        [<Interface>]
        type Options =
            abstract cause: obj option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?cause: obj) : Options = jsNative

    module InvalidRepoNameError =
        [<Interface>]
        type Options =
            abstract cause: obj option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?cause: obj) : Options = jsNative

    module InvalidSessionIdError =
        [<Interface>]
        type Options =
            abstract cause: obj option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?cause: obj) : Options = jsNative

    module NotFoundError =
        [<Interface>]
        type Options =
            abstract cause: obj option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?cause: obj) : Options = jsNative

    module RemoteAddFn =
        [<Interface>]
        type Opts =
            abstract name: string with get, set
            abstract url: string with get, set
            abstract force: bool option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (name: string, url: string, ?force: bool) : Opts = jsNative

        module Result =
            [<Interface>]
            type Item =
                abstract ok: bool with get, set
                abstract exists: bool option with get, set
                abstract message: string option with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (ok: bool, ?exists: bool, ?message: string) : Item = jsNative

    /// <summary>
    /// Base class for every artifacts error. The <c>code</c> field is the
    /// contract: CLI dispatchers and external callers branch on it.
    /// </summary>
    type ArtifactErrorConstructor =
        /// <summary>
        /// Indicates whether the argument provided is a built-in Error instance or not.
        /// </summary>
        abstract isError: error: obj -> bool
        /// <summary>
        /// Base class for every artifacts error. The <c>code</c> field is the
        /// contract: CLI dispatchers and external callers branch on it.
        /// </summary>
        [<EmitConstructor>]
        abstract Create: code: string * message: string * ?options: Artifacts.ArtifactError.Options -> FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.ArtifactError

    /// <summary>
    /// Raised when a repo name is empty, contains a path separator, or
    /// is otherwise unusable as the trailing segment of a scoped name.
    /// </summary>
    type InvalidRepoNameErrorConstructor =
        /// <summary>
        /// Indicates whether the argument provided is a built-in Error instance or not.
        /// </summary>
        abstract isError: error: obj -> bool
        /// <summary>
        /// Raised when a repo name is empty, contains a path separator, or
        /// is otherwise unusable as the trailing segment of a scoped name.
        /// </summary>
        [<EmitConstructor>]
        abstract Create: name: string * reason: string * ?options: Artifacts.InvalidRepoNameError.Options -> FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.InvalidRepoNameError

    /// <summary>
    /// Raised when a session id is empty or contains a path separator.
    /// A session id becomes the leading segment of every scoped name,
    /// so it has the same shape constraints as a repo name.
    /// </summary>
    type InvalidSessionIdErrorConstructor =
        /// <summary>
        /// Indicates whether the argument provided is a built-in Error instance or not.
        /// </summary>
        abstract isError: error: obj -> bool
        /// <summary>
        /// Raised when a session id is empty or contains a path separator.
        /// A session id becomes the leading segment of every scoped name,
        /// so it has the same shape constraints as a repo name.
        /// </summary>
        [<EmitConstructor>]
        abstract Create: sessionId: string * reason: string * ?options: Artifacts.InvalidSessionIdError.Options -> FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.InvalidSessionIdError

    /// <summary>
    /// Raised when a repo lookup misses or a token id can't be found
    /// within a repo's token list.
    /// </summary>
    type NotFoundErrorConstructor =
        /// <summary>
        /// Indicates whether the argument provided is a built-in Error instance or not.
        /// </summary>
        abstract isError: error: obj -> bool
        /// <summary>
        /// Raised when a repo lookup misses or a token id can't be found
        /// within a repo's token list.
        /// </summary>
        [<EmitConstructor>]
        abstract Create: message: string * ?options: Artifacts.NotFoundError.Options -> FSharp.CloudEdge.Runtime.ComputerArtifacts.Artifacts.NotFoundError

/// <summary>@cloudflare/computer/assets</summary>
module Assets =
    [<Interface>]
    type R2PutBucket =
        abstract put: key: string * value: obj * ?options: Assets.R2PutBucket.Put.Options -> JS.Promise<obj>
        [<ParamObject; Emit("$0")>]
        static member Create (put: Func<string, obj, Assets.R2PutBucket.Put.Options option, JS.Promise<obj>>) : R2PutBucket = jsNative

    [<Interface>]
    type WorkspaceLike =
        abstract sessionId: string
        abstract fs: Assets.WorkspaceLike.Fs
        [<ParamObject; Emit("$0")>]
        static member Create (sessionId: string, fs: Assets.WorkspaceLike.Fs) : WorkspaceLike = jsNative

    type AssetsEnv = Record<string, string option>

    [<Interface>]
    type S3Config =
        abstract bucket: string with get, set
        abstract accountId: string option with get, set
        abstract accessKeyId: string option with get, set
        abstract secretAccessKey: string option with get, set
        abstract endpoint: string option with get, set
        abstract region: string option with get, set
        abstract service: string option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (bucket: string, ?accountId: string, ?accessKeyId: string, ?secretAccessKey: string, ?endpoint: string, ?region: string, ?service: string) : S3Config = jsNative

    [<Interface>]
    type CreateAssetsOptions =
        abstract ws: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.WorkspaceLike with get, set
        abstract bucket: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.R2PutBucket with get, set
        abstract s3: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.S3Config with get, set
        abstract env: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.AssetsEnv option with get, set
        abstract now: (unit -> float) option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (ws: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.WorkspaceLike, bucket: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.R2PutBucket, s3: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.S3Config, ?env: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.AssetsEnv, ?now: (unit -> float)) : CreateAssetsOptions = jsNative

    [<Interface>]
    type ShareOptions =
        abstract expiresAfter: float with get, set
        abstract prefix: string option with get, set
        abstract contentType: string option with get, set
        abstract filename: string option with get, set
        abstract disposition: Assets.ShareOptions.Disposition option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (expiresAfter: float, ?prefix: string, ?contentType: string, ?filename: string, ?disposition: Assets.ShareOptions.Disposition) : ShareOptions = jsNative

    [<Interface>]
    type AssetsClient =
        abstract share: path: string * opts: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.ShareOptions -> JS.Promise<string>
        [<ParamObject; Emit("$0")>]
        static member Create (share: Func<string, FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.ShareOptions, JS.Promise<string>>) : AssetsClient = jsNative

    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        [<Import("resolveS3", "@cloudflare/computer/assets")>]
        static member resolveS3 (s3: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.S3Config, env: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.AssetsEnv) : ResolvedS3 = jsNative
        [<Import("createAssets", "@cloudflare/computer/assets")>]
        static member createAssets (options: FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.CreateAssetsOptions) : FSharp.CloudEdge.Runtime.ComputerArtifacts.Assets.AssetsClient = jsNative

    module R2PutBucket =
        module Put =
            [<Interface>]
            type Options =
                abstract httpMetadata: Assets.R2PutBucket.Put.Options.HttpMetadata option with get, set
                abstract customMetadata: Record<string, string> option with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (?httpMetadata: Assets.R2PutBucket.Put.Options.HttpMetadata, ?customMetadata: Record<string, string>) : Options = jsNative

            module Options =
                [<Interface>]
                type HttpMetadata =
                    abstract contentType: string option with get, set
                    abstract contentDisposition: string option with get, set
                    [<ParamObject; Emit("$0")>]
                    static member Create (?contentType: string, ?contentDisposition: string) : HttpMetadata = jsNative

    module ShareOptions =
        [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
        type Disposition =
            | [<CompiledName("attachment")>] Attachment
            | [<CompiledName("inline")>] Inline

    module WorkspaceLike =
        [<Interface>]
        type Fs =
            abstract stat: path: string -> JS.Promise<Assets.WorkspaceLike.Fs.Stat.Result.Item>
            abstract readFile: path: string -> JS.Promise<obj>
            [<ParamObject; Emit("$0")>]
            static member Create (stat: (string -> JS.Promise<Assets.WorkspaceLike.Fs.Stat.Result.Item>), readFile: (string -> JS.Promise<obj>)) : Fs = jsNative

        module Fs =
            module Stat =
                module Result =
                    [<Interface>]
                    type Item =
                        abstract size: float with get, set
                        [<ParamObject; Emit("$0")>]
                        static member Create (size: float) : Item = jsNative

module Observe =
    /// <summary>@cloudflare/computer/observe/cloudflare</summary>
    module Cloudflare =
        [<Interface>]
        type CloudflareObserverOptions =
            /// <summary>
            /// The runtime's user-tracing handle. Pass <c>ctx.tracing</c> from inside a
            /// Worker or Durable Object, or <c>tracing</c> imported from
            /// <c>cloudflare:workers</c>. <c>undefined</c> is accepted because the runtime
            /// omits the property in environments without the user-tracing
            /// feature flag; the adapter then degrades to a pass-through.
            /// </summary>
            abstract tracing: obj option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?tracing: obj) : CloudflareObserverOptions = jsNative

        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            /// <summary>
            /// Build a <c>WorkspaceObserver</c> backed by the Cloudflare runtime's built-in
            /// user tracing surface.
            /// <br /><br />
            /// When <c>tracing</c> is <c>undefined</c>, returns an observer that runs the
            /// callback directly with a span object whose <c>setAttribute</c> is a no-op.
            /// This lets the same wiring code work in environments without the
            /// user-tracing feature flag, without forcing callers to branch on a
            /// possibly-undefined <c>ctx.tracing</c>.
            /// </summary>
            [<Import("createCloudflareObserver", "@cloudflare/computer/observe/cloudflare")>]
            static member createCloudflareObserver (options: FSharp.CloudEdge.Runtime.ComputerArtifacts.Observe.Cloudflare.CloudflareObserverOptions) : WorkspaceObserver = jsNative

module Shell =
    /// <summary>@cloudflare/computer/shell/core</summary>
    module Core =
        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("default", "@cloudflare/computer/shell/core")>]
            static member _default: ReadonlyRecord<string, Shell.Core.Default.Item> = jsNative

        module Default =
            [<Interface>]
            type Item =
                abstract js: string with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (js: string) : Item = jsNative

    /// <summary>@cloudflare/computer/shell/curl</summary>
    module Curl =
        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("default", "@cloudflare/computer/shell/curl")>]
            static member _default: ReadonlyRecord<string, Shell.Curl.Default.Item> = jsNative

        module Default =
            [<Interface>]
            type Item =
                abstract js: string with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (js: string) : Item = jsNative

    /// <summary>@cloudflare/computer/shell/file</summary>
    module File =
        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("default", "@cloudflare/computer/shell/file")>]
            static member _default: ReadonlyRecord<string, Shell.File.Default.Item> = jsNative

        module Default =
            [<Interface>]
            type Item =
                abstract js: string with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (js: string) : Item = jsNative

    /// <summary>@cloudflare/computer/shell/html-to-markdown</summary>
    module HtmlToMarkdown =
        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("default", "@cloudflare/computer/shell/html-to-markdown")>]
            static member _default: ReadonlyRecord<string, Shell.HtmlToMarkdown.Default.Item> = jsNative

        module Default =
            [<Interface>]
            type Item =
                abstract js: string with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (js: string) : Item = jsNative

    /// <summary>@cloudflare/computer/shell/jq</summary>
    module Jq =
        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("default", "@cloudflare/computer/shell/jq")>]
            static member _default: ReadonlyRecord<string, Shell.Jq.Default.Item> = jsNative

        module Default =
            [<Interface>]
            type Item =
                abstract js: string with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (js: string) : Item = jsNative

    /// <summary>@cloudflare/computer/shell/js-exec</summary>
    module JsExec =
        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("default", "@cloudflare/computer/shell/js-exec")>]
            static member _default: ReadonlyRecord<string, Shell.JsExec.Default.Item> = jsNative

        module Default =
            [<Interface>]
            type Item =
                abstract js: string with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (js: string) : Item = jsNative

    /// <summary>@cloudflare/computer/shell/python</summary>
    module Python =
        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("default", "@cloudflare/computer/shell/python")>]
            static member _default: ReadonlyRecord<string, Shell.Python.Default.Item> = jsNative

        module Default =
            [<Interface>]
            type Item =
                abstract js: string with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (js: string) : Item = jsNative

    /// <summary>@cloudflare/computer/shell/sqlite</summary>
    module Sqlite =
        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("default", "@cloudflare/computer/shell/sqlite")>]
            static member _default: ReadonlyRecord<string, Shell.Sqlite.Default.Item> = jsNative

        module Default =
            [<Interface>]
            type Item =
                abstract js: string with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (js: string) : Item = jsNative

    /// <summary>@cloudflare/computer/shell/xan</summary>
    module Xan =
        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("default", "@cloudflare/computer/shell/xan")>]
            static member _default: ReadonlyRecord<string, Shell.Xan.Default.Item> = jsNative

        module Default =
            [<Interface>]
            type Item =
                abstract js: string with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (js: string) : Item = jsNative

    /// <summary>@cloudflare/computer/shell/yq</summary>
    module Yq =
        /// <summary>The package's value exports, each bound to its import.</summary>
        [<Erase>]
        type Exports =
            [<Import("default", "@cloudflare/computer/shell/yq")>]
            static member _default: ReadonlyRecord<string, Shell.Yq.Default.Item> = jsNative

        module Default =
            [<Interface>]
            type Item =
                abstract js: string with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (js: string) : Item = jsNative
