// <auto-generated>
//   Generated by Xantham.Generator from @cloudflare/containers.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec FSharp.CloudEdge.Runtime.Containers

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Erase>]
type OutboundHandlerContext<'Params> = private OutboundHandlerContext__ of obj

type OutboundHandler<'E, 'P> = delegate of req: FSharp.CloudEdge.Runtime.Workers.Request<obj, U2<FSharp.CloudEdge.Runtime.Workers.RequestInitCfProperties, FSharp.CloudEdge.Runtime.Workers.IncomingRequestCfProperties<obj>>> * env: 'E * ctx: obj -> U2<JS.Promise<FSharp.CloudEdge.Runtime.Workers.Response>, FSharp.CloudEdge.Runtime.Workers.Response>

type OutboundHandlerParams = FSharp.CloudEdge.Runtime.Workers.Cloudflare.Pipelines.PipelineRecord

[<Erase>]
type OutboundHandlerParamsOf<'THandler> = private OutboundHandlerParamsOf__ of obj

type BivarianceHack<'E> = delegate of req: FSharp.CloudEdge.Runtime.Workers.Request<obj, U2<FSharp.CloudEdge.Runtime.Workers.RequestInitCfProperties, FSharp.CloudEdge.Runtime.Workers.IncomingRequestCfProperties<obj>>> * env: 'E * ctx: obj -> U2<JS.Promise<FSharp.CloudEdge.Runtime.Workers.Response>, FSharp.CloudEdge.Runtime.Workers.Response>

type OutboundHandlers<'ParamsByMethod, 'E> =
    [<EmitIndexer>]
    abstract Item: string -> BivarianceHack<'E> option with get, set

[<Interface>]
type ContainerProxy =
    abstract fetch: request: FSharp.CloudEdge.Runtime.Workers.Request<obj, U2<FSharp.CloudEdge.Runtime.Workers.RequestInitCfProperties, FSharp.CloudEdge.Runtime.Workers.IncomingRequestCfProperties<obj>>> -> JS.Promise<FSharp.CloudEdge.Runtime.Workers.Response>
    abstract __WORKER_ENTRYPOINT_BRAND: unit
    abstract ctx: FSharp.CloudEdge.Runtime.Workers.ExecutionContext<ContainerProxy.Ctx.Item> with get, set
    abstract env: obj with get, set
    abstract email: (FSharp.CloudEdge.Runtime.Workers.ForwardableEmailMessage -> JS.Promise<unit> option) option with get, set
    abstract connect: (FSharp.CloudEdge.Runtime.Workers.Socket -> JS.Promise<unit> option) option with get, set
    abstract queue: (FSharp.CloudEdge.Runtime.Workers.MessageBatch<obj> -> JS.Promise<unit> option) option with get, set
    abstract scheduled: (FSharp.CloudEdge.Runtime.Workers.ScheduledController -> JS.Promise<unit> option) option with get, set
    abstract tail: (FSharp.CloudEdge.Runtime.Workers.TraceItem[] -> JS.Promise<unit> option) option with get, set
    abstract tailStream: (FSharp.CloudEdge.Runtime.Workers.TailStream.TailEvent<FSharp.CloudEdge.Runtime.Workers.Onset> -> U3<JS.Promise<FSharp.CloudEdge.Runtime.Workers.TailEventHandlerType>, (FSharp.CloudEdge.Runtime.Workers.TailStream.TailEvent<FSharp.CloudEdge.Runtime.Workers.EventType> -> JS.Promise<unit> option), FSharp.CloudEdge.Runtime.Workers.TailEventHandlerType2>) option with get, set
    abstract test: (obj -> JS.Promise<unit> option) option with get, set
    abstract trace: (FSharp.CloudEdge.Runtime.Workers.TraceItem[] -> JS.Promise<unit> option) option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (fetch: (FSharp.CloudEdge.Runtime.Workers.Request<obj, U2<FSharp.CloudEdge.Runtime.Workers.RequestInitCfProperties, FSharp.CloudEdge.Runtime.Workers.IncomingRequestCfProperties<obj>>> -> JS.Promise<FSharp.CloudEdge.Runtime.Workers.Response>), ctx: FSharp.CloudEdge.Runtime.Workers.ExecutionContext<ContainerProxy.Ctx.Item>, env: obj, ?email: (FSharp.CloudEdge.Runtime.Workers.ForwardableEmailMessage -> JS.Promise<unit> option), ?connect: (FSharp.CloudEdge.Runtime.Workers.Socket -> JS.Promise<unit> option), ?queue: (FSharp.CloudEdge.Runtime.Workers.MessageBatch<obj> -> JS.Promise<unit> option), ?scheduled: (FSharp.CloudEdge.Runtime.Workers.ScheduledController -> JS.Promise<unit> option), ?tail: (FSharp.CloudEdge.Runtime.Workers.TraceItem[] -> JS.Promise<unit> option), ?tailStream: (FSharp.CloudEdge.Runtime.Workers.TailStream.TailEvent<FSharp.CloudEdge.Runtime.Workers.Onset> -> U3<JS.Promise<FSharp.CloudEdge.Runtime.Workers.TailEventHandlerType>, (FSharp.CloudEdge.Runtime.Workers.TailStream.TailEvent<FSharp.CloudEdge.Runtime.Workers.EventType> -> JS.Promise<unit> option), FSharp.CloudEdge.Runtime.Workers.TailEventHandlerType2>), ?test: (obj -> JS.Promise<unit> option), ?trace: (FSharp.CloudEdge.Runtime.Workers.TraceItem[] -> JS.Promise<unit> option)) : ContainerProxy = jsNative

type BivarianceHack2 = delegate of req: FSharp.CloudEdge.Runtime.Workers.Request<obj, U2<FSharp.CloudEdge.Runtime.Workers.RequestInitCfProperties, FSharp.CloudEdge.Runtime.Workers.IncomingRequestCfProperties<obj>>> * env: obj * ctx: OutboundHandlerContext<obj> -> U2<JS.Promise<FSharp.CloudEdge.Runtime.Workers.Response>, FSharp.CloudEdge.Runtime.Workers.Response>

[<Interface>]
type CancellationOptions =
    /// <summary>
    /// abort signal, use to abort startAndWaitForPorts manually.
    /// </summary>
    abstract abort: FSharp.CloudEdge.Runtime.Workers.AbortSignal option with get, set
    /// <summary>
    /// max time to get container instance and start it (application inside may not be ready), in milliseconds
    /// </summary>
    abstract instanceGetTimeoutMS: float option with get, set
    /// <summary>
    /// max time to wait for application to be listening at all specified ports, in milliseconds.
    /// </summary>
    abstract portReadyTimeoutMS: float option with get, set
    /// <summary>
    /// time to wait between polling, in milliseconds
    /// </summary>
    abstract waitInterval: float option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?abort: FSharp.CloudEdge.Runtime.Workers.AbortSignal, ?instanceGetTimeoutMS: float, ?portReadyTimeoutMS: float, ?waitInterval: float) : CancellationOptions = jsNative

[<Interface>]
[<Import("Container", "@cloudflare/containers")>]
type Container<'Env> =
    abstract defaultPort: float option with get, set
    abstract requiredPorts: float[] option with get, set
    abstract sleepAfter: U2<string, float> with get, set
    abstract envVars: Record<string, string> option with get, set
    abstract entrypoint: string[] option with get, set
    abstract enableInternet: bool with get, set
    abstract labels: Record<string, string> option with get, set
    abstract interceptHttps: bool with get, set
    abstract allowedHosts: string[] option with get, set
    abstract deniedHosts: string[] option with get, set
    abstract pingEndpoint: string with get, set
    abstract applyOutboundInterceptionPromise: JS.Promise<unit> with get, set
    abstract usingInterception: bool with get, set
    /// <summary>
    /// Gets the current state of the container
    /// </summary>
    /// <returns>Promise&lt;State&gt;</returns>
    abstract getState: unit -> JS.Promise<State>
    /// <summary>
    /// Set the catch-all outbound handler to a named method from <c>outboundHandlers</c>.
    /// Overrides the default <c>outbound</c> at runtime via ContainerProxy props.
    /// </summary>
    /// <param name="methodName">- Name of a method defined in <c>static outboundHandlers</c></param>
    /// <param name="params">- Optional params passed to the handler as <c>ctx.params</c></param>
    /// <remarks>@throws Error if the method name is not found in <c>outboundHandlers</c></remarks>
    abstract setOutboundHandler: methodName: string * [<ParamArray>] paramsArg: obj -> JS.Promise<unit>
    /// <summary>
    /// Add or override a hostname-specific outbound handler at runtime,
    /// referencing a named method from <c>outboundHandlers</c>.
    /// Overrides any matching entry in <c>static outboundByHost</c> for this hostname.
    /// </summary>
    /// <param name="hostname">- The hostname or ip:port to intercept (e.g. <c>'google.com'</c>)</param>
    /// <param name="methodName">- Name of a method defined in <c>static outboundHandlers</c></param>
    /// <param name="params">- Optional params passed to the handler as <c>ctx.params</c></param>
    /// <remarks>@throws Error if the method name is not found in <c>outboundHandlers</c></remarks>
    abstract setOutboundByHost: hostname: string * methodName: string * [<ParamArray>] paramsArg: obj -> JS.Promise<unit>
    /// <summary>
    /// Remove a runtime hostname override added via <c>setOutboundByHost</c>.
    /// The default handler from <c>static outboundByHost</c> (if any) will be used again.
    /// </summary>
    /// <param name="hostname">- The hostname or ip:port to stop overriding</param>
    abstract removeOutboundByHost: hostname: string -> JS.Promise<unit>
    /// <summary>
    /// Replace all runtime hostname overrides at once.
    /// Each value may be either a method name or an object with <c>method</c> and <c>params</c>.
    /// </summary>
    /// <param name="handlers">- Record mapping hostnames to handler configs in <c>outboundHandlers</c></param>
    /// <remarks>@throws Error if any method name is not found in <c>outboundHandlers</c></remarks>
    abstract setOutboundByHosts<'Params>: handlers: Container.SetOutboundByHosts.Handlers<'Params> -> JS.Promise<unit>
    /// <summary>
    /// Replace all allowed hosts at runtime.
    /// Allowed hosts get internet access even when <c>enableInternet</c> is false.
    /// </summary>
    /// <param name="hosts">- Array of hostnames to allow (e.g. <c>['api.stripe.com', 'example.com']</c>)</param>
    abstract setAllowedHosts: hosts: string[] -> JS.Promise<unit>
    /// <summary>
    /// Replace all denied hosts at runtime.
    /// Denied hosts are blocked unconditionally, even when <c>enableInternet</c> is true
    /// or a catch-all outbound handler is set.
    /// </summary>
    /// <param name="hosts">- Array of hostnames to deny (e.g. <c>['evil.com', 'blocked.org']</c>)</param>
    abstract setDeniedHosts: hosts: string[] -> JS.Promise<unit>
    /// <summary>
    /// Add a single hostname to the allowed hosts list at runtime.
    /// </summary>
    /// <param name="hostname">- The hostname to allow (e.g. <c>'api.stripe.com'</c>)</param>
    abstract allowHost: hostname: string -> JS.Promise<unit>
    /// <summary>
    /// Add a single hostname to the denied hosts list at runtime.
    /// </summary>
    /// <param name="hostname">- The hostname to deny (e.g. <c>'evil.com'</c>)</param>
    abstract denyHost: hostname: string -> JS.Promise<unit>
    /// <summary>
    /// Remove a hostname from the allowed hosts list.
    /// </summary>
    /// <param name="hostname">- The hostname to remove from the allow list</param>
    abstract removeAllowedHost: hostname: string -> JS.Promise<unit>
    /// <summary>
    /// Remove a hostname from the denied hosts list.
    /// </summary>
    /// <param name="hostname">- The hostname to remove from the deny list</param>
    abstract removeDeniedHost: hostname: string -> JS.Promise<unit>
    /// <summary>
    /// Start the container if it's not running and set up monitoring and lifecycle hooks,
    /// without waiting for ports to be ready.
    /// <br /><br />
    /// It will automatically retry if the container fails to start, using the specified waitOptions
    /// </summary>
    /// <example>
    /// <code>
    /// await this.start({
    ///   envVars: { DEBUG: 'true', NODE_ENV: 'development' },
    ///   entrypoint: ['npm', 'run', 'dev'],
    ///   enableInternet: false,
    ///   labels: { tenant: 'acme', env: 'prod' },
    /// });
    /// </code>
    /// </example>
    /// <param name="startOptions">- Override <c>envVars</c>, <c>entrypoint</c>, <c>enableInternet</c> and <c>labels</c> on a per-instance basis</param>
    /// <param name="waitOptions">- Optional wait configuration with abort signal for cancellation. Default ~8s timeout.</param>
    /// <returns>A promise that resolves when the container start command has been issued</returns>
    /// <remarks>@throws Error if no container context is available or if all start attempts fail</remarks>
    abstract start: ?startOptions: ContainerStartConfigOptions * ?waitOptions: WaitOptions -> JS.Promise<unit>
    /// <summary>
    /// Start the container and wait for ports to be available.
    /// <br /><br />
    /// For each specified port, it polls until the port is available or <c>cancellationOptions.portReadyTimeoutMS</c> is reached.
    /// </summary>
    /// <param name="ports">- The ports to wait for (if undefined, uses requiredPorts or defaultPort)</param>
    /// <param name="cancellationOptions">- Options to configure timeouts, polling intereva, and abort signal</param>
    /// <param name="startOptions">Override configuration on a per-instance basis for env vars, entrypoint command, internet access, and labels</param>
    /// <returns>A promise that resolves when the container has been started and the ports are listening</returns>
    /// <remarks>@throws Error if port checks fail after the specified timeout or if the container fails to start.</remarks>
    abstract startAndWaitForPorts: args: StartAndWaitForPortsOptions -> JS.Promise<unit>
    /// <summary>
    /// Start the container and wait for ports to be available.
    /// <br /><br />
    /// For each specified port, it polls until the port is available or <c>cancellationOptions.portReadyTimeoutMS</c> is reached.
    /// </summary>
    /// <param name="ports">- The ports to wait for (if undefined, uses requiredPorts or defaultPort)</param>
    /// <param name="cancellationOptions">- Options to configure timeouts, polling intereva, and abort signal</param>
    /// <param name="startOptions">Override configuration on a per-instance basis for env vars, entrypoint command, internet access, and labels</param>
    /// <returns>A promise that resolves when the container has been started and the ports are listening</returns>
    /// <remarks>@throws Error if port checks fail after the specified timeout or if the container fails to start.</remarks>
    abstract startAndWaitForPorts: ?ports: U2<float, float[]> * ?cancellationOptions: CancellationOptions * ?startOptions: ContainerStartConfigOptions -> JS.Promise<unit>
    /// <summary>
    /// Start the container and wait for ports to be available.
    /// <br /><br />
    /// For each specified port, it polls until the port is available or <c>cancellationOptions.portReadyTimeoutMS</c> is reached.
    /// </summary>
    /// <param name="ports">- The ports to wait for (if undefined, uses requiredPorts or defaultPort)</param>
    /// <param name="cancellationOptions">- Options to configure timeouts, polling intereva, and abort signal</param>
    /// <param name="startOptions">Override configuration on a per-instance basis for env vars, entrypoint command, internet access, and labels</param>
    /// <returns>A promise that resolves when the container has been started and the ports are listening</returns>
    /// <remarks>@throws Error if port checks fail after the specified timeout or if the container fails to start.</remarks>
    abstract startAndWaitForPorts: ?portsOrArgs: U3<float, float[], StartAndWaitForPortsOptions> * ?cancellationOptions: CancellationOptions * ?startOptions: ContainerStartConfigOptions -> JS.Promise<unit>
    /// <summary>
    /// Waits for a specified port to be ready
    /// <br /><br />
    /// Returns the number of tries used to get the port, or throws if it couldn't get the port within the specified retry limits.
    /// </summary>
    /// <param name="waitOptions">
    /// -
    /// - <c>portToCheck</c>: The port number to check
    /// - <c>abort</c>: Optional AbortSignal to cancel waiting
    /// - <c>retries</c>: Number of retries before giving up (default: TRIES_TO_GET_PORTS)
    /// - <c>waitInterval</c>: Interval between retries in milliseconds (default: INSTANCE_POLL_INTERVAL_MS)
    /// </param>
    abstract waitForPort: waitOptions: WaitOptions -> JS.Promise<float>
    /// <summary>
    /// Send a signal to the container.
    /// </summary>
    /// <param name="signal">- The signal to send to the container (default: 15 for SIGTERM)</param>
    abstract stop: ?signal: U2<float, string> -> JS.Promise<unit>
    /// <summary>
    /// Destroys the container with a SIGKILL. Triggers onStop.
    /// </summary>
    abstract destroy: unit -> JS.Promise<unit>
    /// <summary>
    /// Lifecycle method called when container starts successfully
    /// Override this method in subclasses to handle container start events
    /// </summary>
    abstract onStart: unit -> JS.Promise<unit> option
    /// <summary>
    /// Lifecycle method called when container shuts down
    /// Override this method in subclasses to handle Container stopped events
    /// </summary>
    /// <param name="params">- Object containing exitCode and reason for the stop</param>
    abstract onStop: ``params``: StopParams -> JS.Promise<unit> option
    /// <summary>
    /// Lifecycle method called when the container is running, and the activity timeout
    /// expiration (set by <c>sleepAfter</c>) has been reached.
    /// <br /><br />
    /// If you want to shutdown the container, you should call this.stop() here
    /// <br /><br />
    /// By default, this method calls <c>this.stop()</c>
    /// </summary>
    abstract onActivityExpired: unit -> JS.Promise<unit>
    /// <summary>
    /// Error handler for container errors
    /// Override this method in subclasses to handle container errors
    /// </summary>
    /// <param name="error">- The error that occurred</param>
    /// <returns>Can return any value or throw the error</returns>
    abstract onError: error: obj -> obj
    /// <summary>
    /// Renew the container's activity timeout
    /// <br /><br />
    /// Call this method whenever there is activity on the container
    /// </summary>
    abstract renewActivityTimeout: unit -> unit
    /// <summary>
    /// Decrement the inflight request counter.
    /// When the counter transitions to 0, renew the activity timeout so the
    /// inactivity window starts fresh from the moment the last request completes.
    /// </summary>
    abstract decrementInflight: obj with get, set
    /// <summary>
    /// Schedule a task to be executed in the future.
    /// <br /><br />
    /// We strongly recommend using this instead of the <c>alarm</c> handler.
    /// </summary>
    /// <remarks>@template T Type of the payload data</remarks>
    /// <param name="when">When to execute the task (Date object or number of seconds delay)</param>
    /// <param name="callback">Name of the method to call</param>
    /// <param name="payload">Data to pass to the callback</param>
    /// <returns>Schedule object representing the scheduled task</returns>
    abstract schedule<'T>: ``when``: U2<float, JS.Date> * callback: string * ?payload: 'T -> JS.Promise<Container.Schedule.Result.Item>
    /// <summary>
    /// Send a request to the container (HTTP or WebSocket) using standard fetch API signature
    /// <br /><br />
    /// This method handles HTTP requests to the container.
    /// <br /><br />
    /// WebSocket requests done outside the DO won't work until https://github.com/cloudflare/workerd/issues/2319 is addressed.
    /// Until then, please use <c>switchPort</c> + <c>fetch()</c>.
    /// <br /><br />
    /// Method supports multiple signatures to match standard fetch API:
    /// - containerFetch(request: Request, port?: number)
    /// - containerFetch(url: string | URL, init?: RequestInit, port?: number)
    /// <br /><br />
    /// Starts the container if not already running, and waits for the target port to be ready.
    /// </summary>
    /// <returns>A Response from the container</returns>
    abstract containerFetch: requestOrUrl: U3<string, FSharp.CloudEdge.Runtime.Workers.Request<obj, U2<FSharp.CloudEdge.Runtime.Workers.RequestInitCfProperties, FSharp.CloudEdge.Runtime.Workers.IncomingRequestCfProperties<obj>>>, FSharp.CloudEdge.Runtime.Workers.URL> * ?portOrInit: U2<float, FSharp.CloudEdge.Runtime.Workers.RequestInit<U2<FSharp.CloudEdge.Runtime.Workers.RequestInitCfProperties, FSharp.CloudEdge.Runtime.Workers.IncomingRequestCfProperties<obj>>>> * ?portParam: float -> JS.Promise<FSharp.CloudEdge.Runtime.Workers.Response>
    /// <summary>
    /// Fetch handler on the Container class.
    /// By default this forwards all requests to the container by calling <c>containerFetch</c>.
    /// Use <c>switchPort</c> to specify which port on the container to target, or this will use <c>defaultPort</c>.
    /// </summary>
    /// <param name="request">The request to handle</param>
    abstract fetch: request: FSharp.CloudEdge.Runtime.Workers.Request<obj, U2<FSharp.CloudEdge.Runtime.Workers.RequestInitCfProperties, FSharp.CloudEdge.Runtime.Workers.IncomingRequestCfProperties<obj>>> -> JS.Promise<FSharp.CloudEdge.Runtime.Workers.Response>
    abstract container: obj with get, set
    abstract onStopCalled: obj with get, set
    abstract state: obj with get, set
    abstract monitor: obj with get, set
    abstract startInFlight: obj with get, set
    abstract monitoredPromise: obj with get, set
    abstract sleepAfterMs: obj with get, set
    abstract inflightRequests: obj with get, set
    abstract outboundByHostOverrides: obj with get, set
    abstract outboundHandlerOverride: obj option with get, set
    abstract allowedHostsOverride: obj option with get, set
    abstract deniedHostsOverride: obj option with get, set
    abstract hasInterceptAllRegistration: obj with get, set
    /// <summary>
    /// Validates that a method name exists in the outboundHandlers registry for this class.
    /// </summary>
    /// <remarks>@throws Error if the method name is not found</remarks>
    abstract validateOutboundHandlerMethodName: obj with get, set
    abstract effectiveAllowedHosts: obj
    abstract effectiveDeniedHosts: obj
    abstract getOutboundConfiguration: obj with get, set
    abstract persistOutboundConfiguration: obj with get, set
    abstract restoreOutboundConfiguration: obj with get, set
    /// <summary>
    /// Returns true if a catch-all outbound HTTP interception is needed.
    /// This is the case when a static <c>outbound</c> handler or a runtime
    /// <c>outboundHandlerOverride</c> (catch-all) is configured.
    /// When false, we only intercept specific hosts to avoid overhead.
    /// </summary>
    abstract needsCatchAllInterception: obj with get, set
    abstract hasMutableOutboundConfiguration: obj with get, set
    abstract shouldInterceptAllOutbound: obj with get, set
    abstract getStaticOutboundByHostKeys: obj with get, set
    /// <summary>
    /// Collects all hostnames that need per-host outbound interception.
    /// This path is only used for the narrow optimized case where outbound
    /// handling is static and host-specific.
    /// </summary>
    abstract getHostsToIntercept: obj with get, set
    abstract refreshOutboundInterception: obj with get, set
    /// <summary>
    /// Applies (or re-applies) outbound HTTP interception with the current
    /// default registries + runtime overrides passed through ContainerProxy props.
    /// <br /><br />
    /// Uses per-host interception only for static host-specific outbound handlers.
    /// As soon as the config needs to evaluate all hosts (catch-all outbound,
    /// allow/deny lists, or runtime-mutated outbound config), we promote the
    /// container to intercept-all and keep it there until the instance restarts.
    /// <br /><br />
    /// When <c>interceptHttps</c> is enabled, also applies HTTPS interception:
    /// - Intercept-all mode: <c>interceptOutboundHttps('*', ...)</c> for all HTTPS traffic
    /// - Per-host mode: <c>interceptOutboundHttps(host, ...)</c> for each known host
    /// </summary>
    abstract applyOutboundInterception: obj with get, set
    /// <summary>
    /// Execute SQL queries against the Container's database
    /// </summary>
    abstract sql: obj with get, set
    abstract requestAndPortFromContainerFetchArgs: obj with get, set
    /// <summary>
    /// The method prioritizes port sources in this order:
    /// 1. Ports specified directly in the method call
    /// 2. <c>requiredPorts</c> class property (if set)
    /// 3. <c>defaultPort</c> (if neither of the above is specified)
    /// 4. Falls back to port 33 if none of the above are set
    /// </summary>
    abstract getPortsToCheck: obj with get, set
    /// <summary>
    /// Tries to start a container if it's not already running
    /// Returns the number of tries used
    /// </summary>
    abstract startContainerIfNotRunning: obj with get, set
    abstract doStartContainer: obj with get, set
    abstract setupMonitorCallbacks: obj with get, set
    abstract deleteSchedules: name: string -> unit
    /// <summary>
    /// Method called when an alarm fires
    /// Executes any scheduled tasks that are due
    /// </summary>
    abstract alarm: ?alarmProps: FSharp.CloudEdge.Runtime.Workers.AlarmInvocationInfo -> JS.Promise<unit>
    abstract timeout: float option with get, set
    abstract resolve: (unit -> unit) option with get, set
    abstract syncPendingStoppedEvents: obj with get, set
    abstract callOnStop: obj with get, set
    /// <summary>
    /// Schedule the next alarm based on upcoming tasks
    /// </summary>
    abstract scheduleNextAlarm: ?ms: float -> JS.Promise<unit>
    abstract listSchedules: name: string -> JS.Promise<FSharp.CloudEdge.Runtime.Containers.Container.Schedule.Result.Item[]>
    abstract toSchedule: obj with get, set
    /// <summary>
    /// Get a scheduled task by ID
    /// </summary>
    /// <remarks>@template T Type of the payload data</remarks>
    /// <param name="id">ID of the scheduled task</param>
    /// <returns>The Schedule object or undefined if not found</returns>
    abstract getSchedule<'T>: id: string -> JS.Promise<U2<Container.GetSchedule.Result.Item<'T>, Container.GetSchedule.Result.Item2<'T>> option>
    abstract isActivityExpired: obj with get, set
    abstract __DURABLE_OBJECT_BRAND: unit
    abstract ctx: FSharp.CloudEdge.Runtime.Workers.DurableObjectState<obj> with get, set
    abstract env: 'Env with get, set
    abstract connect: (FSharp.CloudEdge.Runtime.Workers.Socket -> JS.Promise<unit> option) option with get, set
    abstract webSocketMessage: Func<FSharp.CloudEdge.Runtime.Workers.WebSocket, U2<string, JS.ArrayBuffer>, JS.Promise<unit> option> option with get, set
    abstract webSocketClose: Func<FSharp.CloudEdge.Runtime.Workers.WebSocket, float, string, bool, JS.Promise<unit> option> option with get, set
    abstract webSocketError: Func<FSharp.CloudEdge.Runtime.Workers.WebSocket, obj, JS.Promise<unit> option> option with get, set
    static member outboundByHost
        with get (): Record<string, BivarianceHack2> option = jsNative
        and set (_: Record<string, BivarianceHack2> option): unit = jsNative
    static member outboundHandlers
        with get (): Record<string, BivarianceHack2> option = jsNative
        and set (_: Record<string, BivarianceHack2> option): unit = jsNative
    static member outbound
        with get (): BivarianceHack2 option = jsNative
        and set (_: BivarianceHack2 option): unit = jsNative
    static member outboundProxies
        with get (): Record<string, BivarianceHack2> option = jsNative
        and set (_: Record<string, BivarianceHack2> option): unit = jsNative
    static member outboundProxy
        with get (): BivarianceHack2 option = jsNative
        and set (_: BivarianceHack2 option): unit = jsNative

[<Interface>]
type StartAndWaitForPortsOptions =
    abstract startOptions: ContainerStartConfigOptions option with get, set
    abstract ports: U2<float, float[]> option with get, set
    abstract cancellationOptions: CancellationOptions option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?startOptions: ContainerStartConfigOptions, ?ports: U2<float, float[]>, ?cancellationOptions: CancellationOptions) : StartAndWaitForPortsOptions = jsNative

[<Interface>]
type State2 =
    abstract lastChange: float with get, set
    abstract status: State2.Status with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (lastChange: float, status: State2.Status) : State2 = jsNative

[<Interface>]
type State3 =
    abstract lastChange: float with get, set
    abstract status: string with get, set
    abstract exitCode: float option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (lastChange: float, status: string, ?exitCode: float) : State3 = jsNative

/// <summary>
/// Message structure for communication with containers
/// </summary>
[<Interface>]
type ContainerMessage<'T> =
    abstract ``type``: string with get, set
    abstract payload: 'T option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, ?payload: 'T) : ContainerMessage<'T> = jsNative

/// <summary>
/// Options for container configuration
/// </summary>
[<Interface>]
type ContainerOptions =
    /// <summary>
    /// Optional ID for the container
    /// </summary>
    abstract id: string option with get, set
    /// <summary>
    /// Default port number to connect to (defaults to container.defaultPort)
    /// </summary>
    abstract defaultPort: float option with get, set
    /// <summary>
    /// How long to keep the container alive without activity
    /// </summary>
    abstract sleepAfter: U2<string, float> option with get, set
    /// <summary>
    /// Environment variables to pass to the container
    /// </summary>
    abstract envVars: Record<string, string> option with get, set
    /// <summary>
    /// Custom entrypoint to override container default
    /// </summary>
    abstract entrypoint: string[] option with get, set
    /// <summary>
    /// Whether to enable internet access for the container
    /// </summary>
    abstract enableInternet: bool option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?id: string, ?defaultPort: float, ?sleepAfter: U2<string, float>, ?envVars: Record<string, string>, ?entrypoint: string[], ?enableInternet: bool) : ContainerOptions = jsNative

type ContainerEventHandler = (unit -> JS.Promise<unit> option)

/// <summary>
/// Options for starting a container with specific configuration
/// </summary>
[<Interface>]
type ContainerStartConfigOptions =
    /// <summary>
    /// Environment variables to pass to the container
    /// </summary>
    abstract envVars: Record<string, string> option with get, set
    /// <summary>
    /// Custom entrypoint to override container default
    /// </summary>
    abstract entrypoint: string[] option with get, set
    /// <summary>
    /// Whether to enable internet access for the container
    /// </summary>
    abstract enableInternet: bool option with get, set
    /// <summary>
    /// Key-value metadata labels attached to the container for metrics/observability
    /// </summary>
    abstract labels: Record<string, string> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?envVars: Record<string, string>, ?entrypoint: string[], ?enableInternet: bool, ?labels: Record<string, string>) : ContainerStartConfigOptions = jsNative

/// <summary>
/// Options for waitForPort()
/// </summary>
[<Interface>]
type WaitOptions =
    /// <summary>
    /// The port number to check for readiness
    /// </summary>
    abstract portToCheck: float with get, set
    /// <summary>
    /// Optional AbortSignal, use this to abort waiting for ports
    /// </summary>
    abstract signal: FSharp.CloudEdge.Runtime.Workers.AbortSignal option with get, set
    /// <summary>
    /// Number of attempts to wait for port to be ready
    /// </summary>
    abstract retries: float option with get, set
    /// <summary>
    /// Time to wait in between polling port for readiness, in milliseconds
    /// </summary>
    abstract waitInterval: float option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (portToCheck: float, ?signal: FSharp.CloudEdge.Runtime.Workers.AbortSignal, ?retries: float, ?waitInterval: float) : WaitOptions = jsNative

/// <summary>
/// Params sent to <c>onStop</c> method when the container stops
/// </summary>
[<Interface>]
type StopParams =
    abstract exitCode: float with get, set
    abstract reason: StopParams.Reason with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (exitCode: float, reason: StopParams.Reason) : StopParams = jsNative

type State = U2<State2, State3>

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("outboundParams", "@cloudflare/containers")>]
    static member outboundParams<'THandler> (_handler: 'THandler, ``params``: obj) : obj = jsNative
    [<Import("ContainerProxy", "@cloudflare/containers"); EmitConstructor>]
    static member ContainerProxy (ctx: FSharp.CloudEdge.Runtime.Workers.ExecutionContext<obj>, env: obj) : ContainerProxy = jsNative
    [<Import("Container", "@cloudflare/containers"); EmitConstructor>]
    static member Container<'Env> (ctx: FSharp.CloudEdge.Runtime.Workers.DurableObjectState<obj>, env: 'Env, ?options: ContainerOptions) : Container<'Env> = jsNative
    /// <summary>
    /// Get a random container instances across N instances. This is useful for load balancing.
    /// </summary>
    /// <param name="binding">The Container's Durable Object binding</param>
    /// <param name="instances">Number of instances to load balance across</param>
    /// <returns>A promise resolving to a container stub ready to handle requests</returns>
    [<Import("getRandom", "@cloudflare/containers")>]
    static member getRandom<'T when 'T :> Container<obj>> (binding: FSharp.CloudEdge.Runtime.Workers.DurableObjectNamespace<'T>, ?instances: float) : JS.Promise<obj> = jsNative
    /// <summary>
    /// Deprecated funtion to get random container instances. Renamed to getRandom
    /// </summary>
    /// <param name="binding">The Container's Durable Object binding</param>
    /// <param name="instances">Number of instances to load balance across</param>
    /// <returns>A promise resolving to a container stub ready to handle requests</returns>
    [<Import("loadBalance", "@cloudflare/containers")>]
    static member loadBalance<'T when 'T :> Container<obj>> (binding: FSharp.CloudEdge.Runtime.Workers.DurableObjectNamespace<'T>, ?instances: float) : JS.Promise<obj> = jsNative
    /// <summary>
    /// Get a container stub
    /// </summary>
    /// <param name="binding">The Container's Durable Object binding</param>
    /// <param name="name">The name of the instance to get, uses 'cf-singleton-container' by default</param>
    /// <returns>A container stub ready to handle requests</returns>
    [<Import("getContainer", "@cloudflare/containers")>]
    static member getContainer<'T when 'T :> Container<obj>> (binding: FSharp.CloudEdge.Runtime.Workers.DurableObjectNamespace<'T>, ?name: string) : obj = jsNative
    /// <summary>
    /// Return a request with the port target set correctly
    /// You can use this method when you have to use <c>fetch</c> and not <c>containerFetch</c> with as it's a JSRPC method and it
    /// comes with some consequences like not being able to pass WebSockets.
    /// </summary>
    /// <example><c>container.fetch(switchPort(request, 8090));</c></example>
    [<Import("switchPort", "@cloudflare/containers")>]
    static member switchPort (request: FSharp.CloudEdge.Runtime.Workers.Request<obj, U2<FSharp.CloudEdge.Runtime.Workers.RequestInitCfProperties, FSharp.CloudEdge.Runtime.Workers.IncomingRequestCfProperties<obj>>>, port: float) : FSharp.CloudEdge.Runtime.Workers.Request<obj, U2<FSharp.CloudEdge.Runtime.Workers.RequestInitCfProperties, FSharp.CloudEdge.Runtime.Workers.IncomingRequestCfProperties<obj>>> = jsNative

module Container =
    module GetSchedule =
        module Result =
            [<Interface>]
            type Item<'T> =
                /// <summary>
                /// Unique identifier for the schedule
                /// </summary>
                abstract taskId: string with get, set
                /// <summary>
                /// Name of the method to be called
                /// </summary>
                abstract callback: string with get, set
                /// <summary>
                /// Data to be passed to the callback
                /// </summary>
                abstract payload: 'T with get, set
                /// <summary>
                /// Type of schedule for one-time execution at a specific time
                /// </summary>
                abstract ``type``: string with get, set
                /// <summary>
                /// Timestamp when the task should execute
                /// </summary>
                abstract time: float with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (taskId: string, callback: string, payload: 'T, ``type``: string, time: float) : Item<'T> = jsNative

            [<Interface>]
            type Item2<'T> =
                /// <summary>
                /// Unique identifier for the schedule
                /// </summary>
                abstract taskId: string with get, set
                /// <summary>
                /// Name of the method to be called
                /// </summary>
                abstract callback: string with get, set
                /// <summary>
                /// Data to be passed to the callback
                /// </summary>
                abstract payload: 'T with get, set
                /// <summary>
                /// Type of schedule for delayed execution
                /// </summary>
                abstract ``type``: string with get, set
                /// <summary>
                /// Timestamp when the task should execute
                /// </summary>
                abstract time: float with get, set
                /// <summary>
                /// Number of seconds to delay execution
                /// </summary>
                abstract delayInSeconds: float with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (taskId: string, callback: string, payload: 'T, ``type``: string, time: float, delayInSeconds: float) : Item2<'T> = jsNative

    module Schedule =
        module Result =
            [<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
            type Item =
                | [<CompiledName("scheduled")>] Scheduled of taskId: string * callback: string * payload: obj * time: float
                | [<CompiledName("delayed")>] Delayed of taskId: string * callback: string * payload: obj * time: float * delayInSeconds: float

            [<Interface>]
            type Item2<'T> =
                /// <summary>
                /// Unique identifier for the schedule
                /// </summary>
                abstract taskId: string with get, set
                /// <summary>
                /// Name of the method to be called
                /// </summary>
                abstract callback: string with get, set
                /// <summary>
                /// Data to be passed to the callback
                /// </summary>
                abstract payload: 'T with get, set
                /// <summary>
                /// Type of schedule for one-time execution at a specific time
                /// </summary>
                abstract ``type``: string with get, set
                /// <summary>
                /// Timestamp when the task should execute
                /// </summary>
                abstract time: float with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (taskId: string, callback: string, payload: 'T, ``type``: string, time: float) : Item2<'T> = jsNative

            [<Interface>]
            type Item3<'T> =
                /// <summary>
                /// Unique identifier for the schedule
                /// </summary>
                abstract taskId: string with get, set
                /// <summary>
                /// Name of the method to be called
                /// </summary>
                abstract callback: string with get, set
                /// <summary>
                /// Data to be passed to the callback
                /// </summary>
                abstract payload: 'T with get, set
                /// <summary>
                /// Type of schedule for delayed execution
                /// </summary>
                abstract ``type``: string with get, set
                /// <summary>
                /// Timestamp when the task should execute
                /// </summary>
                abstract time: float with get, set
                /// <summary>
                /// Number of seconds to delay execution
                /// </summary>
                abstract delayInSeconds: float with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (taskId: string, callback: string, payload: 'T, ``type``: string, time: float, delayInSeconds: float) : Item3<'T> = jsNative

    module SetOutboundByHosts =
        type Handlers<'Params> =
            [<EmitIndexer>]
            abstract Item: string -> obj with get, set

module ContainerProxy =
    module Ctx =
        [<Interface>]
        type Item =
            abstract enableInternet: bool option with get, set
            abstract containerId: string with get, set
            abstract className: string with get, set
            abstract outboundByHostOverrides: Record<string, FSharp.CloudEdge.Runtime.Containers.ContainerProxy.Ctx.Item.OutboundByHostOverrides.Item<obj>> option with get, set
            abstract outboundHandlerOverride: FSharp.CloudEdge.Runtime.Containers.ContainerProxy.Ctx.Item.OutboundByHostOverrides.Item<obj> option with get, set
            abstract allowedHosts: string[] option with get, set
            abstract deniedHosts: string[] option with get, set
            abstract interceptAll: bool option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (containerId: string, className: string, ?enableInternet: bool, ?outboundByHostOverrides: Record<string, FSharp.CloudEdge.Runtime.Containers.ContainerProxy.Ctx.Item.OutboundByHostOverrides.Item<obj>>, ?outboundHandlerOverride: FSharp.CloudEdge.Runtime.Containers.ContainerProxy.Ctx.Item.OutboundByHostOverrides.Item<obj>, ?allowedHosts: string[], ?deniedHosts: string[], ?interceptAll: bool) : Item = jsNative

        module Item =
            module OutboundByHostOverrides =
                [<Erase>]
                type Item<'Params> = private Item__ of obj

module State2 =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Status =
        | [<CompiledName("healthy")>] Healthy
        | [<CompiledName("running")>] Running
        | [<CompiledName("stopped")>] Stopped
        | [<CompiledName("stopping")>] Stopping

module StopParams =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Reason =
        | [<CompiledName("exit")>] Exit
        | [<CompiledName("runtime_signal")>] RuntimeSignal

type ContainerConstructor =
    abstract outboundByHost: Record<string, BivarianceHack2> option with get, set
    abstract outboundHandlers: Record<string, BivarianceHack2> option with get, set
    abstract outbound: BivarianceHack2 option with get, set
    abstract outboundProxies: Record<string, BivarianceHack2> option with get, set
    abstract outboundProxy: BivarianceHack2 option with get, set
    [<EmitConstructor>]
    abstract Create<'Env>: ctx: FSharp.CloudEdge.Runtime.Workers.DurableObjectState<obj> * env: 'Env * ?options: ContainerOptions -> Container<'Env>
