// <auto-generated>
//   Generated by Xantham.Generator from @cloudflare/ai-utils.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec FSharp.CloudEdge.Runtime.AIUtils

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type Config =
    abstract overrides: ConfigRule[] with get, set
    abstract matchPatterns: obj[] option with get, set
    abstract options: Config.Options option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (overrides: ConfigRule[], ?matchPatterns: obj[], ?options: Config.Options) : Config = jsNative

[<Interface>]
type ConfigRule =
    abstract matcher: (ConfigRule.Matcher.Values -> bool) with get, set
    abstract values: ConfigRule.Values with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (matcher: (ConfigRule.Matcher.Values -> bool), values: ConfigRule.Values) : ConfigRule = jsNative

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type UppercaseHttpMethod =
    | DELETE
    | GET
    | HEAD
    | OPTIONS
    | PATCH
    | POST
    | PUT

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type LowercaseHttpMethod =
    | [<CompiledName("delete")>] Delete
    | [<CompiledName("get")>] Get
    | [<CompiledName("head")>] Head
    | [<CompiledName("options")>] Options
    | [<CompiledName("patch")>] Patch
    | [<CompiledName("post")>] Post
    | [<CompiledName("put")>] Put

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type HttpMethod =
    | DELETE
    | GET
    | HEAD
    | OPTIONS
    | PATCH
    | POST
    | PUT
    | [<CompiledName("delete")>] Delete
    | [<CompiledName("get")>] Get
    | [<CompiledName("head")>] Head
    | [<CompiledName("options")>] Options
    | [<CompiledName("patch")>] Patch
    | [<CompiledName("post")>] Post
    | [<CompiledName("put")>] Put

[<Interface>]
type Parameter =
    abstract name: string with get, set
    abstract required: bool with get, set
    abstract ``type``: string with get, set
    abstract description: string with get, set
    abstract ``$ref``: string option with get, set
    abstract schema: obj option with get, set
    abstract ``in``: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string, required: bool, ``type``: string, description: string, ?``$ref``: string, ?schema: obj, ?``in``: string) : Parameter = jsNative

[<Interface>]
type Meta =
    abstract url: string with get, set
    abstract ``method``: HttpMethod with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (url: string, ``method``: HttpMethod) : Meta = jsNative

[<Interface>]
type AiTextGenerationToolInputWithFunction =
    abstract name: string with get, set
    abstract description: string with get, set
    abstract parameters: AiTextGenerationToolInputWithFunction.Parameters option with get, set
    abstract ``function``: (obj -> JS.Promise<string>) option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string, description: string, ?parameters: AiTextGenerationToolInputWithFunction.Parameters, ?``function``: (obj -> JS.Promise<string>)) : AiTextGenerationToolInputWithFunction = jsNative

[<Interface>]
type ToolsSchema<'T> =
    abstract name: string with get, set
    abstract description: string with get, set
    abstract parameters: 'T with get, set
    abstract ``function``: (obj -> JS.Promise<string>) option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string, description: string, parameters: 'T, ?``function``: (obj -> JS.Promise<string>)) : ToolsSchema<'T> = jsNative

[<Interface>]
type ApiKeySecurityScheme =
    abstract ``type``: string with get, set
    abstract description: string option with get, set
    abstract name: string with get, set
    abstract ``in``: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, name: string, ``in``: string, ?description: string) : ApiKeySecurityScheme = jsNative

type ArraySchemaObject =
    inherit BaseSchemaObject
    abstract ``type``: string with get, set
    abstract items: U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject> with get, set

type BaseSchemaObject =
    abstract title: string option with get, set
    abstract description: string option with get, set
    abstract format: string option with get, set
    abstract ``default``: obj option with get, set
    abstract multipleOf: float option with get, set
    abstract maximum: float option with get, set
    abstract exclusiveMaximum: bool option with get, set
    abstract minimum: float option with get, set
    abstract exclusiveMinimum: bool option with get, set
    abstract maxLength: float option with get, set
    abstract minLength: float option with get, set
    abstract pattern: string option with get, set
    abstract additionalProperties: U4<bool, ArraySchemaObject, NonArraySchemaObject, ReferenceObject> option with get, set
    abstract maxItems: float option with get, set
    abstract minItems: float option with get, set
    abstract uniqueItems: bool option with get, set
    abstract maxProperties: float option with get, set
    abstract minProperties: float option with get, set
    abstract required: string[] option with get, set
    abstract enum: obj[] option with get, set
    abstract properties: Record<string, U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject>> option with get, set
    abstract allOf: U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject>[] option with get, set
    abstract oneOf: U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject>[] option with get, set
    abstract anyOf: U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject>[] option with get, set
    abstract ``not``: U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject> option with get, set
    abstract nullable: bool option with get, set
    abstract discriminator: DiscriminatorObject option with get, set
    abstract readOnly: bool option with get, set
    abstract writeOnly: bool option with get, set
    abstract xml: XMLObject option with get, set
    abstract externalDocs: ExternalDocumentationObject option with get, set
    abstract example: obj option with get, set
    abstract deprecated: bool option with get, set

type CallbackObject =
    [<EmitIndexer>]
    abstract Item: string -> CallbackObject.Item<obj> with get, set

[<Interface>]
type ComponentsObject =
    abstract schemas: Record<string, U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject>> option with get, set
    abstract responses: Record<string, U2<ReferenceObject, ResponseObject>> option with get, set
    abstract parameters: Record<string, U2<ParameterObject, ReferenceObject>> option with get, set
    abstract examples: Record<string, U2<ExampleObject, ReferenceObject>> option with get, set
    abstract requestBodies: Record<string, U2<ReferenceObject, RequestBodyObject>> option with get, set
    abstract headers: Record<string, U2<HeaderObject, ReferenceObject>> option with get, set
    abstract securitySchemes: Record<string, U5<ApiKeySecurityScheme, HttpSecurityScheme, OAuth2SecurityScheme, OpenIdSecurityScheme, ReferenceObject>> option with get, set
    abstract links: Record<string, U2<LinkObject, ReferenceObject>> option with get, set
    abstract callbacks: Record<string, U2<CallbackObject, ReferenceObject>> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?schemas: Record<string, U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject>>, ?responses: Record<string, U2<ReferenceObject, ResponseObject>>, ?parameters: Record<string, U2<ParameterObject, ReferenceObject>>, ?examples: Record<string, U2<ExampleObject, ReferenceObject>>, ?requestBodies: Record<string, U2<ReferenceObject, RequestBodyObject>>, ?headers: Record<string, U2<HeaderObject, ReferenceObject>>, ?securitySchemes: Record<string, U5<ApiKeySecurityScheme, HttpSecurityScheme, OAuth2SecurityScheme, OpenIdSecurityScheme, ReferenceObject>>, ?links: Record<string, U2<LinkObject, ReferenceObject>>, ?callbacks: Record<string, U2<CallbackObject, ReferenceObject>>) : ComponentsObject = jsNative

[<Interface>]
type ContactObject =
    abstract name: string option with get, set
    abstract url: string option with get, set
    abstract email: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?name: string, ?url: string, ?email: string) : ContactObject = jsNative

[<Interface>]
type DiscriminatorObject =
    abstract propertyName: string with get, set
    abstract mapping: Record<string, string> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (propertyName: string, ?mapping: Record<string, string>) : DiscriminatorObject = jsNative

[<Interface>]
type Document<'T> =
    abstract openapi: string with get, set
    abstract info: InfoObject with get, set
    abstract servers: ServerObject[] option with get, set
    abstract paths: PathsObject<'T, obj> with get, set
    abstract components: ComponentsObject option with get, set
    abstract security: SecurityRequirementObject[] option with get, set
    abstract tags: TagObject[] option with get, set
    abstract externalDocs: ExternalDocumentationObject option with get, set
    abstract ``x-express-openapi-additional-middleware``: U2<Document.XExpressOpenapiAdditionalMiddleware.Item, Document.XExpressOpenapiAdditionalMiddleware.Item2>[] option with get, set
    abstract ``x-express-openapi-validation-strict``: bool option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (openapi: string, info: InfoObject, paths: PathsObject<'T, obj>, ?servers: ServerObject[], ?components: ComponentsObject, ?security: SecurityRequirementObject[], ?tags: TagObject[], ?externalDocs: ExternalDocumentationObject, ?``x-express-openapi-additional-middleware``: U2<Document.XExpressOpenapiAdditionalMiddleware.Item, Document.XExpressOpenapiAdditionalMiddleware.Item2>[], ?``x-express-openapi-validation-strict``: bool) : Document<'T> = jsNative

[<Interface>]
type EncodingObject =
    abstract contentType: string option with get, set
    abstract headers: Record<string, U2<HeaderObject, ReferenceObject>> option with get, set
    abstract style: string option with get, set
    abstract explode: bool option with get, set
    abstract allowReserved: bool option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?contentType: string, ?headers: Record<string, U2<HeaderObject, ReferenceObject>>, ?style: string, ?explode: bool, ?allowReserved: bool) : EncodingObject = jsNative

[<Interface>]
type ExampleObject =
    abstract summary: string option with get, set
    abstract description: string option with get, set
    abstract value: obj option with get, set
    abstract externalValue: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?summary: string, ?description: string, ?value: obj, ?externalValue: string) : ExampleObject = jsNative

[<Interface>]
type ExternalDocumentationObject =
    abstract description: string option with get, set
    abstract url: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (url: string, ?description: string) : ExternalDocumentationObject = jsNative

[<Interface>]
type HeaderObject =
    inherit ParameterBaseObject
    [<ParamObject; Emit("$0")>]
    static member Create (?description: string, ?required: bool, ?deprecated: bool, ?allowEmptyValue: bool, ?style: string, ?explode: bool, ?allowReserved: bool, ?schema: U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject>, ?example: obj, ?examples: Record<string, U2<ExampleObject, ReferenceObject>>, ?content: Record<string, MediaTypeObject>) : HeaderObject = jsNative

[<Interface>]
type HttpSecurityScheme =
    abstract ``type``: string with get, set
    abstract description: string option with get, set
    abstract scheme: string with get, set
    abstract bearerFormat: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, scheme: string, ?description: string, ?bearerFormat: string) : HttpSecurityScheme = jsNative

[<Interface>]
type InfoObject =
    abstract title: string with get, set
    abstract description: string option with get, set
    abstract termsOfService: string option with get, set
    abstract contact: ContactObject option with get, set
    abstract license: LicenseObject option with get, set
    abstract version: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (title: string, version: string, ?description: string, ?termsOfService: string, ?contact: ContactObject, ?license: LicenseObject) : InfoObject = jsNative

[<Interface>]
type LicenseObject =
    abstract name: string with get, set
    abstract url: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string, ?url: string) : LicenseObject = jsNative

[<Interface>]
type LinkObject =
    abstract operationRef: string option with get, set
    abstract operationId: string option with get, set
    abstract parameters: Record<string, obj> option with get, set
    abstract requestBody: obj option with get, set
    abstract description: string option with get, set
    abstract server: ServerObject option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?operationRef: string, ?operationId: string, ?parameters: Record<string, obj>, ?requestBody: obj, ?description: string, ?server: ServerObject) : LinkObject = jsNative

[<Interface>]
type MediaTypeObject =
    abstract schema: U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject> option with get, set
    abstract example: obj option with get, set
    abstract examples: Record<string, U2<ExampleObject, ReferenceObject>> option with get, set
    abstract encoding: Record<string, EncodingObject> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?schema: U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject>, ?example: obj, ?examples: Record<string, U2<ExampleObject, ReferenceObject>>, ?encoding: Record<string, EncodingObject>) : MediaTypeObject = jsNative

type NonArraySchemaObject =
    inherit BaseSchemaObject
    abstract ``type``: NonArraySchemaObjectType option with get, set

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type NonArraySchemaObjectType =
    | [<CompiledName("boolean")>] Boolean
    | [<CompiledName("integer")>] Integer
    | [<CompiledName("number")>] Number
    | [<CompiledName("object")>] Object
    | [<CompiledName("string")>] String

[<Interface>]
type OAuth2SecurityScheme =
    abstract ``type``: string with get, set
    abstract description: string option with get, set
    abstract flows: OAuth2SecurityScheme.Flows with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, flows: OAuth2SecurityScheme.Flows, ?description: string) : OAuth2SecurityScheme = jsNative

[<Interface>]
type OpenIdSecurityScheme =
    abstract ``type``: string with get, set
    abstract description: string option with get, set
    abstract openIdConnectUrl: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, openIdConnectUrl: string, ?description: string) : OpenIdSecurityScheme = jsNative

[<Interface>]
type ParameterBaseObject =
    abstract description: string option with get, set
    abstract required: bool option with get, set
    abstract deprecated: bool option with get, set
    abstract allowEmptyValue: bool option with get, set
    abstract style: string option with get, set
    abstract explode: bool option with get, set
    abstract allowReserved: bool option with get, set
    abstract schema: U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject> option with get, set
    abstract example: obj option with get, set
    abstract examples: Record<string, U2<ExampleObject, ReferenceObject>> option with get, set
    abstract content: Record<string, MediaTypeObject> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?description: string, ?required: bool, ?deprecated: bool, ?allowEmptyValue: bool, ?style: string, ?explode: bool, ?allowReserved: bool, ?schema: U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject>, ?example: obj, ?examples: Record<string, U2<ExampleObject, ReferenceObject>>, ?content: Record<string, MediaTypeObject>) : ParameterBaseObject = jsNative

[<Interface>]
type ParameterObject =
    inherit ParameterBaseObject
    abstract name: string with get, set
    abstract ``in``: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string, ``in``: string, ?description: string, ?required: bool, ?deprecated: bool, ?allowEmptyValue: bool, ?style: string, ?explode: bool, ?allowReserved: bool, ?schema: U3<ArraySchemaObject, NonArraySchemaObject, ReferenceObject>, ?example: obj, ?examples: Record<string, U2<ExampleObject, ReferenceObject>>, ?content: Record<string, MediaTypeObject>) : ParameterObject = jsNative

type PathsObject<'T, 'P> =
    [<EmitIndexer>]
    abstract Item: string -> obj option with get, set

[<Interface>]
type ReferenceObject =
    abstract ``$ref``: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``$ref``: string) : ReferenceObject = jsNative

[<Interface>]
type RequestBodyObject =
    abstract description: string option with get, set
    abstract content: Record<string, MediaTypeObject> with get, set
    abstract required: bool option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (content: Record<string, MediaTypeObject>, ?description: string, ?required: bool) : RequestBodyObject = jsNative

[<Interface>]
type ResponseObject =
    abstract description: string with get, set
    abstract headers: Record<string, U2<HeaderObject, ReferenceObject>> option with get, set
    abstract content: Record<string, MediaTypeObject> option with get, set
    abstract links: Record<string, U2<LinkObject, ReferenceObject>> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (description: string, ?headers: Record<string, U2<HeaderObject, ReferenceObject>>, ?content: Record<string, MediaTypeObject>, ?links: Record<string, U2<LinkObject, ReferenceObject>>) : ResponseObject = jsNative

type SecurityRequirementObject =
    [<EmitIndexer>]
    abstract Item: string -> string[] with get, set

[<Interface>]
type ServerObject =
    abstract url: string with get, set
    abstract description: string option with get, set
    abstract variables: Record<string, ServerVariableObject> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (url: string, ?description: string, ?variables: Record<string, ServerVariableObject>) : ServerObject = jsNative

[<Interface>]
type ServerVariableObject =
    abstract enum: U2<string[], float[]> option with get, set
    abstract ``default``: U2<string, float> with get, set
    abstract description: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``default``: U2<string, float>, ?enum: U2<string[], float[]>, ?description: string) : ServerVariableObject = jsNative

[<Interface>]
type TagObject =
    abstract name: string with get, set
    abstract description: string option with get, set
    abstract externalDocs: ExternalDocumentationObject option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (name: string, ?description: string, ?externalDocs: ExternalDocumentationObject) : TagObject = jsNative

[<Interface>]
type XMLObject =
    abstract name: string option with get, set
    abstract ``namespace``: string option with get, set
    abstract prefix: string option with get, set
    abstract attribute: bool option with get, set
    abstract wrapped: bool option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?name: string, ?``namespace``: string, ?prefix: string, ?attribute: bool, ?wrapped: bool) : XMLObject = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("createToolsFromOpenAPISpec", "@cloudflare/ai-utils")>]
    static member createToolsFromOpenAPISpec (spec: string, ?config: Config) : JS.Promise<AiTextGenerationToolInputWithFunction[]> = jsNative
    [<Import("runWithTools", "@cloudflare/ai-utils")>]
    static member runWithTools (ai: obj, model: obj, input: RunWithTools.Input, ?config: RunWithTools.Config) : JS.Promise<obj> = jsNative
    [<Import("tool", "@cloudflare/ai-utils")>]
    static member tool<'T> (tool: ToolsSchema<'T>) : ToolsSchema<'T> = jsNative
    [<Import("fetchSpec", "@cloudflare/ai-utils")>]
    static member fetchSpec (spec: string) : JS.Promise<Document<obj> option> = jsNative
    [<Import("validateArgsWithZod", "@cloudflare/ai-utils")>]
    static member validateArgsWithZod (args: obj, properties: Record<string, obj>) : bool = jsNative
    [<Import("autoTrimTools", "@cloudflare/ai-utils")>]
    static member autoTrimTools (tools: AiTextGenerationToolInputWithFunction[], ai: obj, model: obj, messages: obj[]) : JS.Promise<AiTextGenerationToolInputWithFunction[]> = jsNative

module AiTextGenerationToolInputWithFunction =
    [<Interface>]
    type Parameters =
        abstract ``type``: string with get, set
        abstract properties: Record<string, AiTextGenerationToolInputWithFunction.Parameters.Properties.Item> with get, set
        abstract required: string[] with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (``type``: string, properties: Record<string, AiTextGenerationToolInputWithFunction.Parameters.Properties.Item>, required: string[]) : Parameters = jsNative

    module Parameters =
        module Properties =
            [<Interface>]
            type Item =
                abstract ``type``: string with get, set
                abstract description: string option with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (``type``: string, ?description: string) : Item = jsNative

module CallbackObject =
    [<Interface>]
    type Item<'T> =
        abstract ``$ref``: string option with get, set
        abstract summary: string option with get, set
        abstract description: string option with get, set
        abstract servers: ServerObject[] option with get, set
        abstract parameters: U2<ParameterObject, ReferenceObject>[] option with get, set
        abstract delete: obj option with get, set
        abstract get: obj option with get, set
        abstract head: obj option with get, set
        abstract options: obj option with get, set
        abstract patch: obj option with get, set
        abstract post: obj option with get, set
        abstract put: obj option with get, set
        abstract trace: obj option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (?``$ref``: string, ?summary: string, ?description: string, ?servers: ServerObject[], ?parameters: U2<ParameterObject, ReferenceObject>[], ?delete: obj, ?get: obj, ?head: obj, ?options: obj, ?patch: obj, ?post: obj, ?put: obj, ?trace: obj) : Item<'T> = jsNative

module Config =
    [<Interface>]
    type Options =
        abstract verbose: bool option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (?verbose: bool) : Options = jsNative

module ConfigRule =
    [<Interface>]
    type Values =
        abstract headers: Record<string, string> option with get, set
        abstract pathData: Record<string, string> option with get, set
        abstract query: Record<string, string> option with get, set
        abstract body: obj option with get, set
        abstract cookies: Record<string, string> option with get, set
        abstract formData: Record<string, obj> option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (?headers: Record<string, string>, ?pathData: Record<string, string>, ?query: Record<string, string>, ?body: obj, ?cookies: Record<string, string>, ?formData: Record<string, obj>) : Values = jsNative

    module Matcher =
        [<Interface>]
        type Values =
            abstract url: obj with get, set
            abstract ``method``: HttpMethod with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (url: obj, ``method``: HttpMethod) : Values = jsNative

module Document =
    module XExpressOpenapiAdditionalMiddleware =
        type Item = delegate of request: obj * response: obj * next: obj -> JS.Promise<unit>

        type Item2 = delegate of request: obj * response: obj * next: obj -> unit

module OAuth2SecurityScheme =
    [<Interface>]
    type Flows =
        abstract implicit: OAuth2SecurityScheme.Flows.Implicit option with get, set
        abstract password: OAuth2SecurityScheme.Flows.Password option with get, set
        abstract clientCredentials: OAuth2SecurityScheme.Flows.ClientCredentials option with get, set
        abstract authorizationCode: OAuth2SecurityScheme.Flows.AuthorizationCode option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (?implicit: OAuth2SecurityScheme.Flows.Implicit, ?password: OAuth2SecurityScheme.Flows.Password, ?clientCredentials: OAuth2SecurityScheme.Flows.ClientCredentials, ?authorizationCode: OAuth2SecurityScheme.Flows.AuthorizationCode) : Flows = jsNative

    module Flows =
        [<Interface>]
        type AuthorizationCode =
            abstract authorizationUrl: string with get, set
            abstract tokenUrl: string with get, set
            abstract refreshUrl: string option with get, set
            abstract scopes: Record<string, string> with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (authorizationUrl: string, tokenUrl: string, scopes: Record<string, string>, ?refreshUrl: string) : AuthorizationCode = jsNative

        [<Interface>]
        type ClientCredentials =
            abstract tokenUrl: string with get, set
            abstract refreshUrl: string option with get, set
            abstract scopes: Record<string, string> with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (tokenUrl: string, scopes: Record<string, string>, ?refreshUrl: string) : ClientCredentials = jsNative

        [<Interface>]
        type Implicit =
            abstract authorizationUrl: string with get, set
            abstract refreshUrl: string option with get, set
            abstract scopes: Record<string, string> with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (authorizationUrl: string, scopes: Record<string, string>, ?refreshUrl: string) : Implicit = jsNative

        [<Interface>]
        type Password =
            abstract tokenUrl: string with get, set
            abstract refreshUrl: string option with get, set
            abstract scopes: Record<string, string> with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (tokenUrl: string, scopes: Record<string, string>, ?refreshUrl: string) : Password = jsNative

module RunWithTools =
    [<Interface>]
    type Config =
        abstract streamFinalResponse: bool option with get, set
        abstract maxRecursiveToolRuns: float option with get, set
        abstract strictValidation: bool option with get, set
        abstract verbose: bool option with get, set
        abstract trimFunction: RunWithTools.Config.TrimFunction option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (?streamFinalResponse: bool, ?maxRecursiveToolRuns: float, ?strictValidation: bool, ?verbose: bool, ?trimFunction: RunWithTools.Config.TrimFunction) : Config = jsNative

    [<Interface>]
    type Input =
        abstract messages: obj[] with get, set
        abstract tools: AiTextGenerationToolInputWithFunction[] with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (messages: obj[], tools: AiTextGenerationToolInputWithFunction[]) : Input = jsNative

    module Config =
        type TrimFunction = delegate of tools: AiTextGenerationToolInputWithFunction[] * ai: obj * model: obj * messages: obj[] -> JS.Promise<AiTextGenerationToolInputWithFunction[]>
