<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <HawaiiBindingsRoot Condition="'$(HawaiiBindingsRoot)' == ''">$(MSBuildThisFileDirectory)../..</HawaiiBindingsRoot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(HawaiiBindingsRoot)/src/Management/FSharp.CloudEdge.Management.Compute/FSharp.CloudEdge.Management.Compute.fsproj" />
    <ProjectReference Include="$(HawaiiBindingsRoot)/src/Tenancy/FSharp.CloudEdge.Tenancy/FSharp.CloudEdge.Tenancy.fsproj" />
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
