// <auto-generated>
//   Generated by Xantham.Generator from @cloudflare/pages-plugin-turnstile.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec FSharp.CloudEdge.Runtime.PagesPluginTurnstile

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type PluginArgs =
    abstract secret: string with get, set
    abstract response: string option with get, set
    abstract remoteip: string option with get, set
    abstract idempotency_key: string option with get, set
    abstract onError: obj option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (secret: string, ?response: string, ?remoteip: string, ?idempotency_key: string, ?onError: obj) : PluginArgs = jsNative

[<Interface>]
type TurnstileSuccess =
    abstract success: bool with get, set
    abstract challenge_ts: string with get, set
    abstract hostname: string with get, set
    abstract ``error-codes``: string[] option with get, set
    abstract action: string option with get, set
    abstract cdata: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (success: bool, challenge_ts: string, hostname: string, ?``error-codes``: string[], ?action: string, ?cdata: string) : TurnstileSuccess = jsNative

[<Interface>]
type TurnstileFailure =
    abstract success: bool with get, set
    abstract ``error-codes``: string[] with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (success: bool, ``error-codes``: string[]) : TurnstileFailure = jsNative

[<Interface>]
type PluginData =
    abstract turnstile: U2<TurnstileFailure, TurnstileSuccess> with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (turnstile: U2<TurnstileFailure, TurnstileSuccess>) : PluginData = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("default", "@cloudflare/pages-plugin-turnstile")>]
    static member pagesPluginTurnstile (args: PluginArgs) : obj = jsNative
