<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Examples.props" />
  <ItemGroup>
    <ProjectReference Include="$(CloudEdgeSrc)Runtime/Platform/FSharp.CloudEdge.Runtime.Workers/FSharp.CloudEdge.Runtime.Workers.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="LinkShortener.fs" />
    <Compile Include="ShoppingCart.fs" />
    <Compile Include="FileDrop.fs" />
    <Compile Include="Guestbook.fs" />
    <Compile Include="Checkout.fs" />
  </ItemGroup>
</Project>
