// <auto-generated>
//   Generated by Xantham.Generator from @cloudflare/pages-plugin-static-forms.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec FSharp.CloudEdge.Runtime.PagesPluginStaticForms

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type PluginArgs =
    abstract respondWith: (PluginArgs.RespondWith0 -> U2<JS.Promise<Fable.Core.TS.Dom.Response>, Fable.Core.TS.Dom.Response>) with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (respondWith: (PluginArgs.RespondWith0 -> U2<JS.Promise<Fable.Core.TS.Dom.Response>, Fable.Core.TS.Dom.Response>)) : PluginArgs = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("default", "@cloudflare/pages-plugin-static-forms")>]
    static member pagesPluginStaticForms (args: PluginArgs) : obj = jsNative

module PluginArgs =
    [<Interface>]
    type RespondWith0 =
        abstract formData: Fable.Core.TS.Dom.FormData with get, set
        abstract name: string with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (formData: Fable.Core.TS.Dom.FormData, name: string) : RespondWith0 = jsNative
