// <auto-generated>
//   Generated by Xantham.Generator from @cloudflare/cabidela.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec FSharp.CloudEdge.Runtime.Cabidela

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<Interface>]
type CabidelaOptions =
    abstract applyDefaults: bool option with get, set
    abstract useMerge: bool option with get, set
    abstract errorMessages: bool option with get, set
    abstract fullErrors: bool option with get, set
    abstract subSchemas: obj[] option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?applyDefaults: bool, ?useMerge: bool, ?errorMessages: bool, ?fullErrors: bool, ?subSchemas: obj[]) : CabidelaOptions = jsNative

[<Interface>]
type SchemaNavigation =
    abstract path: string[] with get, set
    abstract schema: obj with get, set
    abstract payload: obj with get, set
    abstract evaluatedProperties: JS.Set<string> with get, set
    abstract carryProperties: bool option with get, set
    abstract deferredApplyDefaults: bool option with get, set
    abstract absorvErrors: bool option with get, set
    abstract errors: JS.Set<string> with get, set
    abstract defaultsCallbacks: obj[] with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (path: string[], schema: obj, payload: obj, evaluatedProperties: JS.Set<string>, errors: JS.Set<string>, defaultsCallbacks: obj[], ?carryProperties: bool, ?deferredApplyDefaults: bool, ?absorvErrors: bool) : SchemaNavigation = jsNative

[<Interface>]
type Cabidela =
    abstract schema: obj with get, set
    abstract options: obj with get, set
    abstract definitions: obj with get, set
    abstract setSchema: schema: obj -> unit
    abstract addSchema: subSchema: obj * ?combine: bool -> unit
    abstract getSchema: unit -> obj
    abstract setOptions: options: CabidelaOptions -> unit
    abstract throw: message: string * needle: SchemaNavigation -> unit
    abstract parseAdditionalProperties: needle: SchemaNavigation * contextAdditionalProperties: obj * contextEvaluatedProperties: JS.Set<string> -> float
    abstract parseObject: needle: SchemaNavigation -> bool
    abstract parseList: list: obj * needle: SchemaNavigation * ?breakCondition: JS.Function -> float
    abstract parseSubSchema: needle: SchemaNavigation -> float
    abstract validate: payload: obj -> bool
    [<ParamObject; Emit("$0")>]
    static member Create (schema: obj, options: obj, definitions: obj, setSchema: (obj -> unit), addSchema: Action<obj, bool option>, getSchema: (unit -> obj), setOptions: (CabidelaOptions -> unit), throw: Action<string, SchemaNavigation>, parseAdditionalProperties: Func<SchemaNavigation, obj, JS.Set<string>, float>, parseObject: (SchemaNavigation -> bool), parseList: Func<obj, SchemaNavigation, JS.Function option, float>, parseSubSchema: (SchemaNavigation -> float), validate: (obj -> bool)) : Cabidela = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("Cabidela", "@cloudflare/cabidela"); EmitConstructor>]
    static member Cabidela (schema: obj, ?options: CabidelaOptions) : Cabidela = jsNative
