import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { closeSync, existsSync, mkdirSync, openSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { inspectInputOverlays } from "./input-overlays.mjs";
import { catalogCandidates, catalogProjectDependencies, declarationReferences, generationOrder } from "./catalogs.mjs";

const requireThat = (condition, message) => { if (!condition) throw new Error(message); };
const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");
const slash = (value) => value.split(path.sep).join("/");
const xml = (value) => value.replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
const object = (value) => value !== null && typeof value === "object" && !Array.isArray(value);
const compare = (a, b) => a < b ? -1 : a > b ? 1 : 0;
const exactVersion = (value) => typeof value === "string" && /^\d+\.\d+\.\d+(?:\.\d+)?(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(value);
const canonical = (value) => JSON.stringify(value, function (_, child) {
  return object(child) ? Object.fromEntries(Object.entries(child).sort(([a], [b]) => compare(a, b))) : child;
});

function fields(value, required, allowed, label) {
  requireThat(object(value), `${label} must be an object`);
  requireThat(required.every((key) => Object.hasOwn(value, key)), `${label} is missing a required field`);
  requireThat(Object.keys(value).every((key) => allowed.includes(key)), `${label} contains an unknown field`);
}

function relativeFile(base, value, label) {
  requireThat(typeof value === "string" && value.length > 0 && !path.isAbsolute(value), `${label} must be a relative path`);
  requireThat(!/[\\\x00-\x1f$;*?]/.test(value), `${label} contains unsupported path characters`);
  const absolute = path.resolve(base, value);
  const relative = path.relative(base, absolute);
  requireThat(relative !== ".." && !relative.startsWith(`..${path.sep}`), `${label} escapes its directory`);
  return absolute;
}

function projectText(project, defaults, byId) {
  const directory = path.dirname(project.file);
  const relative = (file) => xml(slash(path.relative(directory, file)));
  return [
    '<Project Sdk="Microsoft.NET.Sdk">',
    "  <!-- Generated by scripts/projects.mjs from config/targets.json. -->",
    "  <PropertyGroup>",
    `    <TargetFramework>${xml(defaults.targetFramework)}</TargetFramework>`,
    "    <NoWarn>$(NoWarn);FS1104</NoWarn>",
    "    <OtherFlags>$(OtherFlags) --maxerrors:20</OtherFlags>",
    "  </PropertyGroup>",
    "  <ItemGroup>",
    ...project.sources.map((source) => `    <Compile Include="${relative(source)}" />`),
    "  </ItemGroup>",
    "  <ItemGroup>",
    ...Object.entries(defaults.packages).sort(([a], [b]) => compare(a, b)).map(([name, version]) => `    <PackageReference Include="${xml(name)}" Version="${xml(version)}" />`),
    ...project.dependencies.map((id) => `    <ProjectReference Include="${relative(byId.get(id).file)}" />`),
    "  </ItemGroup>",
    "</Project>",
    "",
  ].join("\n");
}

/** Pure planning: file order and dependency ownership come only from checked configuration. */
export function planProjects(config, repositoryRoot, catalogDependencies = new Map()) {
  const root = path.resolve(repositoryRoot);
  const keys = ["schemaVersion", "toolchain", "xantham", "profiles", "projectDefaults", "targets"];
  fields(config, keys, keys, "configuration");
  requireThat(config.schemaVersion === 2, "Project scaffolding requires schemaVersion 2");
  requireThat(exactVersion(config.toolchain?.typescript), "toolchain must pin TypeScript exactly");
  const defaults = config.projectDefaults;
  fields(defaults, ["targetFramework", "packages"], ["targetFramework", "packages"], "projectDefaults");
  requireThat(typeof defaults.targetFramework === "string" && /^net(?:standard)?\d+\.\d+$/.test(defaults.targetFramework), "targetFramework must name one .NET target framework");
  requireThat(object(defaults.packages) && Object.keys(defaults.packages).length > 0, "packages must contain exact NuGet pins");
  for (const [name, version] of Object.entries(defaults.packages)) {
    requireThat(/^[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(name) && exactVersion(version), `Invalid exact NuGet pin: ${name}`);
  }
  requireThat(Object.hasOwn(defaults.packages, "Fable.Core"), "packages must explicitly pin Fable.Core");
  requireThat(Object.hasOwn(defaults.packages, "Xantham.Fable.Core"), "packages must explicitly pin Xantham.Fable.Core");
  const supportPackage = { id: "Xantham.Fable.Core", version: defaults.packages["Xantham.Fable.Core"] };
  requireThat(Array.isArray(config.profiles) && config.profiles.length > 0, "At least one profile is required");
  const profiles = new Map();
  for (const profile of config.profiles) {
    fields(profile, ["id", "directory"], ["id", "directory"], "profile");
    requireThat(typeof profile.id === "string" && /^[a-z][a-z0-9-]*$/.test(profile.id) && !profiles.has(profile.id), "Profile IDs must be unique lowercase names");
    profiles.set(profile.id, relativeFile(root, profile.directory, `Profile ${profile.id}`));
  }
  requireThat(Array.isArray(config.targets) && config.targets.length > 0, "At least one target is required");
  const byId = new Map();
  const sourceOwners = new Map();
  const moduleOwners = new Map();
  for (const target of config.targets) {
    const targetKeys = ["id", "package", "version", "outputDirectory", "files", "generator", "profile", "dependencies"];
    fields(target, targetKeys, [...targetKeys, "catalogCandidates"], "target");
    requireThat(typeof target.id === "string" && /^[a-z][a-z0-9-]*$/.test(target.id) && !byId.has(target.id), "Target IDs must be unique lowercase names");
    requireThat(typeof target.package === "string" && /^(?:@[a-z0-9._-]+\/)?[a-z0-9._-]+$/.test(target.package) && exactVersion(target.version), `${target.id}: invalid package or exact version`);
    requireThat(profiles.has(target.profile), `${target.id}: unknown profile ${target.profile}`);
    requireThat(Array.isArray(target.dependencies) && target.dependencies.every((id) => typeof id === "string") && new Set(target.dependencies).size === target.dependencies.length, `${target.id}: dependencies must be unique target IDs`);
    const module = target.generator?.module;
    requireThat(typeof module === "string" && /^[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*$/.test(module), `${target.id}: invalid generator.module`);
    requireThat(target.generator.declarationCatalog === undefined || typeof target.generator.declarationCatalog === "boolean", `${target.id}: declarationCatalog must be a boolean`);
    const references = target.generator.declarationReferences ?? [];
    requireThat(Array.isArray(references) && references.every((file) => typeof file === "string" && file.trim().length > 0) && new Set(references).size === references.length, `${target.id}: declarationReferences must be unique nonempty paths`);
    for (const [other, owner] of moduleOwners) {
      requireThat(module !== other && !module.startsWith(other + ".") && !other.startsWith(module + "."), `${target.id}: module ${module} collides with ${owner}'s ${other}`);
    }
    moduleOwners.set(module, target.id);
    const directory = relativeFile(root, target.outputDirectory, `${target.id}: outputDirectory`);
    const inSrc = path.relative(path.join(root, "src"), directory);
    requireThat(inSrc.length > 0 && inSrc !== ".." && !inSrc.startsWith(`..${path.sep}`), `${target.id}: outputDirectory must be below src/`);
    requireThat(Array.isArray(target.files) && target.files.length > 0, `${target.id}: files must specify F# compile order`);
    let entrySeen = false;
    const sources = target.files.map((file) => {
      const source = relativeFile(directory, file, `${target.id}: source`);
      requireThat(source.endsWith(".fs"), `${target.id}: compile inputs must be .fs files`);
      requireThat(!sourceOwners.has(source), `${target.id}: source already owned by ${sourceOwners.get(source)}: ${file}`);
      sourceOwners.set(source, target.id);
      const group = slash(path.relative(directory, source)).startsWith("groups/");
      requireThat(!group || !entrySeen, `${target.id}: group files must precede entry files`);
      if (!group) entrySeen = true;
      return source;
    });
    byId.set(target.id, { id: target.id, profile: target.profile, target, sources, dependencies: [...new Set([...target.dependencies, ...(catalogDependencies.get(target.id) ?? [])])], file: path.join(directory, module + ".fsproj") });
  }
  const projects = [];
  const visited = new Set();
  function visit(id, ancestors) {
    requireThat(byId.has(id), `Unknown dependency target: ${id}`);
    requireThat(!ancestors.includes(id), `Project dependency cycle: ${[...ancestors, id].join(" -> ")}`);
    if (visited.has(id)) return;
    const project = byId.get(id);
    project.dependencies.forEach((dependency) => visit(dependency, [...ancestors, id]));
    visited.add(id);
    projects.push(project);
  }
  generationOrder(config.targets).forEach((target) => visit(target.id, []));
  projects.forEach((project) => { project.content = projectText(project, defaults, byId); });
  const solution = path.join(root, "FSharp.CloudEdge.Bindings.slnx");
  const folders = new Map();
  for (const project of projects) {
    const parent = slash(path.relative(path.join(root, "src"), path.dirname(path.dirname(project.file))));
    const folder = parent ? `/${parent}/` : "/src/";
    if (!folders.has(folder)) folders.set(folder, []);
    folders.get(folder).push(project);
  }
  const solutionContent = [
    "<Solution>",
    "  <!-- Generated bindings only; consumer tests remain in FSharp.CloudEdge.slnx. -->",
    ...[...folders].sort(([a], [b]) => compare(a, b)).flatMap(([folder, members]) => [
      `  <Folder Name="${xml(folder)}">`,
      ...members.map((project) => `    <Project Path="${xml(slash(path.relative(root, project.file)))}" />`),
      "  </Folder>",
    ]),
    "</Solution>",
    "",
  ].join("\n");
  return { root, config, projects, solution, solutionContent, supportPackage };
}

function atomicWrite(file, content) {
  mkdirSync(path.dirname(file), { recursive: true });
  const temporary = `${file}.${process.pid}.tmp`;
  writeFileSync(temporary, content);
  renameSync(temporary, file);
}

export function writeProjects(plan) {
  plan = reconcileProjects(plan);
  for (const project of plan.projects) atomicWrite(project.file, project.content);
  atomicWrite(plan.solution, plan.solutionContent);
}

function selectedProjects(plan, requested) {
  const byId = new Map(plan.projects.map((project) => [project.id, project]));
  const wanted = new Set();
  function include(id) {
    requireThat(byId.has(id), `Unknown target: ${id}`);
    if (wanted.has(id)) return;
    wanted.add(id);
    byId.get(id).dependencies.forEach(include);
  }
  (requested.length ? requested : plan.projects.map((project) => project.id)).forEach(include);
  return plan.projects.filter((project) => wanted.has(project.id));
}

/** Cache read-only profile inspection across receipts, including inherited catalog producers. */
function receiptReader(plan) {
  const profiles = new Map(plan.config.profiles.map((profile) => [profile.id, path.resolve(plan.root, profile.directory)]));
  const inspectedProfiles = new Map();
  const receipts = new Map();
  function read(target) {
    const provenanceFile = path.join(plan.root, "artifacts", target.id, "generation.json");
    requireThat(existsSync(provenanceFile), `${target.id}: generation provenance is missing`);
    const provenance = JSON.parse(readFileSync(provenanceFile, "utf8"));
    const toolLockFile = path.join(plan.root, "config/tool-packages.json");
    requireThat(existsSync(toolLockFile), `${target.id}: generator package lock is missing`);
    const toolLock = JSON.parse(readFileSync(toolLockFile, "utf8"));
    const expectedTool = toolLock.tools?.[plan.config.xantham.tool];
    requireThat(toolLock.schemaVersion === 1 && object(expectedTool) && typeof expectedTool.packageSha256 === "string",
      `${target.id}: generator package lock is incomplete`);
    requireThat(object(provenance.generatorTool)
      && Object.entries(expectedTool).every(([key, value]) => canonical(provenance.generatorTool[key]) === canonical(value)),
      `${target.id}: generation tool differs from the pinned package`);
    requireThat(provenance.target === target.id && provenance.package === target.package && provenance.version === target.version, `${target.id}: generation input differs from target`);
    requireThat(provenance.typescript === plan.config.toolchain.typescript && canonical(provenance.generator) === canonical(target.generator), `${target.id}: generation configuration differs from target`);
    requireThat(canonical(provenance.catalogCandidates) === canonical(catalogCandidates(target)), `${target.id}: generation catalog candidates differ from target`);
    requireThat(provenance.profile === target.profile, `${target.id}: generation profile differs from target`);
    const profileDirectory = profiles.get(target.profile);
    if (!inspectedProfiles.has(target.profile)) inspectedProfiles.set(target.profile, inspectInputOverlays({ root: plan.root, profileDirectory }));
    const inspected = inspectedProfiles.get(target.profile);
    requireThat(provenance.profileLockSha256 === inspected.profileLockSha256, `${target.id}: profile lockfile hash differs from generation`);
    requireThat(provenance.profileManifestSha256 === inspected.profileManifestSha256, `${target.id}: profile manifest hash differs from generation`);
    requireThat(object(provenance.inputOverlays) && provenance.inputOverlays.fingerprint === inspected.fingerprint, `${target.id}: input overlay fingerprint differs from generation`);
    const recordedInputs = provenance.inputOverlays;
    requireThat(recordedInputs.sourceProfileDirectory === profileDirectory && recordedInputs.applicable === inspected.applicable && recordedInputs.applied === inspected.applicable
      && typeof recordedInputs.profileDirectory === "string" && path.isAbsolute(recordedInputs.profileDirectory)
      && (inspected.applicable || recordedInputs.profileDirectory === profileDirectory)
      && provenance.inputPackageDirectory === path.join(recordedInputs.profileDirectory, "node_modules", target.package),
    `${target.id}: generation input package directory differs from profile evidence`);
    const catalogFile = path.join(plan.root, "artifacts", target.id, "declarations.json");
    requireThat(existsSync(catalogFile) === !!target.generator.declarationCatalog, `${target.id}: declaration catalog output differs from configuration`);
    requireThat(target.generator.declarationCatalog
      ? provenance.declarationCatalogSha256 === sha256(readFileSync(catalogFile))
      : provenance.declarationCatalogSha256 === undefined,
    `${target.id}: declaration catalog hash differs from generation`);
    const originalPackageDirectory = path.join(profileDirectory, "node_modules", target.package);
    const references = declarationReferences(target, plan.root, originalPackageDirectory);
    requireThat(object(provenance.declarationReferenceSha256) && canonical(Object.keys(provenance.declarationReferenceSha256).sort()) === canonical(references.map(({ key }) => key).sort()), `${target.id}: declaration reference inventory differs from configuration`);
    for (const { key, file } of references) {
      requireThat(existsSync(file), `${target.id}: declaration reference is missing: ${key}`);
      requireThat(provenance.declarationReferenceSha256[key] === sha256(readFileSync(file)), `${target.id}: declaration reference hash differs from generation: ${key}`);
    }
    return { provenance, provenanceFile, catalogFile, references };
  }
  return (target) => {
    if (!receipts.has(target.id)) receipts.set(target.id, read(target));
    return receipts.get(target.id);
  };
}

/** Authenticate catalog lineage before using its owner graph to derive project references. */
export function reconcileProjects(plan, requested = [], strict = false, readReceipt = receiptReader(plan)) {
  const byModule = new Map(plan.config.targets.map((target) => [target.generator.module, target]));
  const dependencies = new Map();
  const errors = new Map();
  const loading = new Set();
  const loaded = new Map();
  function load(target) {
    if (loaded.has(target.id)) return loaded.get(target.id);
    if (errors.has(target.id)) throw errors.get(target.id);
    requireThat(!loading.has(target.id), `${target.id}: cyclic declaration catalog receipt lineage`);
    loading.add(target.id);
    try {
      const receipt = readReceipt(target);
      requireThat(target.generator.declarationCatalog === true, `${target.id}: project owner must emit a declaration catalog`);
      // Only owner metadata is needed here; inherited declaration inventories can be large.
      const { schemaVersion, owner, owners } = JSON.parse(readFileSync(receipt.catalogFile, "utf8"));
      const catalog = { schemaVersion, owner, owners };
      const actual = catalogProjectDependencies(catalog, target, plan.config.targets);
      const available = new Map();
      for (const { file } of receipt.references) {
        const reference = JSON.parse(readFileSync(file, "utf8"));
        const producer = byModule.get(reference.owner);
        requireThat(producer, `${target.id}: declaration reference has no configured project owner: ${reference.owner}`);
        const authenticated = load(producer);
        requireThat(sha256(readFileSync(file)) === authenticated.hash, `${target.id}: declaration reference differs from owner ${producer.id}'s authenticated catalog`);
        for (const owner of authenticated.catalog.owners) {
          requireThat(!available.has(owner.name) || canonical(available.get(owner.name)) === canonical(owner.dependencies), `${target.id}: inherited catalog owner dependencies disagree: ${owner.name}`);
          available.set(owner.name, owner.dependencies);
        }
      }
      for (const owner of catalog.owners) {
        if (owner.name !== catalog.owner) requireThat(available.has(owner.name) && canonical(available.get(owner.name)) === canonical(owner.dependencies), `${target.id}: unauthenticated inherited catalog owner: ${owner.name}`);
      }
      for (const id of actual) {
        const owner = plan.config.targets.find((entry) => entry.id === id).generator.module;
        requireThat(available.has(owner), `${target.id}: used catalog owner is absent from authenticated references: ${owner}`);
      }
      dependencies.set(target.id, actual);
      const result = { catalog, hash: receipt.provenance.declarationCatalogSha256 };
      loaded.set(target.id, result);
      return result;
    } catch (error) { errors.set(target.id, error); throw error; }
    finally { loading.delete(target.id); }
  }
  // Missing receipts are normal before the first generation. They never supply project edges.
  const roots = strict && requested.length ? requested.map((id) => {
    const project = plan.projects.find((entry) => entry.id === id);
    requireThat(project, `Unknown target: ${id}`);
    return project;
  }) : plan.projects;
  const included = new Set();
  function include(project) {
    if (included.has(project.id)) return;
    included.add(project.id);
    for (const id of project.target.dependencies) include(plan.projects.find((entry) => entry.id === id));
    if (project.target.generator.declarationCatalog) {
      try { load(project.target); } catch { /* Strict selected checks below surface the recorded failure. */ }
    }
  }
  roots.forEach(include);
  const reconciled = planProjects(plan.config, plan.root, dependencies);
  reconciled.solution = plan.solution;
  if (strict) for (const project of selectedProjects(reconciled, requested)) {
    if (errors.has(project.id)) throw errors.get(project.id);
  }
  return reconciled;
}

/** Verify project text and generation provenance before invoking the compiler. */
export function checkProjects(plan, requested = []) {
  const readReceipt = receiptReader(plan);
  plan = reconcileProjects(plan, requested, true, readReceipt);
  const selected = selectedProjects(plan, requested);
  requireThat(existsSync(plan.solution) && readFileSync(plan.solution, "utf8") === plan.solutionContent, "Bindings solution differs from configuration; run projects.mjs --write");
  const checked = [];
  for (const project of selected) {
    requireThat(existsSync(project.file) && readFileSync(project.file, "utf8") === project.content, `${project.id}: project differs from configuration; run projects.mjs --write`);
    const target = project.target;
    const { provenance, provenanceFile } = readReceipt(target);
    requireThat(object(provenance.sourceSha256) && canonical(Object.keys(provenance.sourceSha256).sort()) === canonical([...target.files].sort()), `${project.id}: generation source inventory differs from target`);
    const sources = Object.fromEntries(project.sources.map((file, index) => {
      requireThat(existsSync(file), `${project.id}: generated source is missing: ${target.files[index]}`);
      const hash = sha256(readFileSync(file));
      requireThat(hash === provenance.sourceSha256[target.files[index]], `${project.id}: generated source hash differs: ${target.files[index]}`);
      return [target.files[index], hash];
    }));
    checked.push({ target: project.id, profile: project.profile, dependencies: [...project.dependencies], project: slash(path.relative(plan.root, project.file)), projectSha256: sha256(readFileSync(project.file)), sources, generationSha256: sha256(readFileSync(provenanceFile)) });
  }
  return checked;
}

export function buildProjects(plan, requested = [], dotnet = process.env.CLOUDEDGE_DOTNET ?? "dotnet") {
  const checked = checkProjects(plan, requested);
  const reportDirectory = path.join(plan.root, "artifacts", "projects");
  mkdirSync(reportDirectory, { recursive: true });
  const stamp = new Date().toISOString().replaceAll(":", "-");
  const log = path.join(reportDirectory, `build-${stamp}.log`);
  const report = { startedAtUtc: new Date().toISOString(), dotnet, requested, configurationSha256: sha256(canonical(plan.config)), supportPackage: plan.supportPackage, checked, log, builds: [] };
  const targets = requested.length ? requested.map((id) => plan.projects.find((project) => project.id === id).file) : [plan.solution];
  const fd = openSync(log, "w");
  try {
    for (const target of targets) {
      const args = ["build", target, "--nologo"];
      console.log(`Building ${slash(path.relative(plan.root, target))}; log: ${log}`);
      const result = spawnSync(dotnet, args, { cwd: plan.root, stdio: ["ignore", fd, fd] });
      report.builds.push({ args, exitCode: result.status, signal: result.signal, error: result.error?.message });
      requireThat(!result.error && result.status === 0, `Binding compilation failed: ${result.error?.message ?? result.signal ?? result.status}; see ${log}`);
    }
    report.succeeded = true;
    return report;
  } finally {
    closeSync(fd);
    report.finishedAtUtc = new Date().toISOString();
    report.succeeded ??= false;
    atomicWrite(path.join(reportDirectory, `build-${stamp}.json`), JSON.stringify(report, null, 2) + "\n");
    atomicWrite(path.join(reportDirectory, "latest.json"), JSON.stringify(report, null, 2) + "\n");
  }
}

function main() {
  const [mode = "--check", ...requested] = process.argv.slice(2);
  requireThat(["--write", "--check", "--build"].includes(mode) && requested.every((id) => !id.startsWith("--")) && (mode !== "--write" || requested.length === 0), "Usage: node scripts/projects.mjs --write | --check [target ...] | --build [target ...]");
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  const plan = planProjects(JSON.parse(readFileSync(path.join(root, "config", "targets.json"), "utf8")), root);
  if (mode === "--write") {
    writeProjects(plan);
    console.log(`Wrote ${plan.projects.length} F# project(s) and the bindings solution; generation and compilation are separate checks.`);
  } else if (mode === "--check") {
    console.log(`Checked ${checkProjects(plan, requested).length} generated project(s) and their source hashes.`);
  } else {
    buildProjects(plan, requested);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { main(); } catch (error) { console.error(`CloudEdge projects failed: ${error.message}`); process.exitCode = 1; }
}
