<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Examples.props" />
  <ItemGroup>
    <PackageReference Include="FSharp.CloudEdge.Runtime.Workers" Version="0.1.*" Condition="'$(CloudEdgeUseSource)' != 'true'" />
    <ProjectReference Include="$(CloudEdgeSrc)Runtime/Platform/FSharp.CloudEdge.Runtime.Workers/FSharp.CloudEdge.Runtime.Workers.fsproj" Condition="'$(CloudEdgeUseSource)' == 'true'" />
    <PackageReference Include="FSharp.CloudEdge.Runtime.Sandbox" Version="0.1.*" Condition="'$(CloudEdgeUseSource)' != 'true'" />
    <ProjectReference Include="$(CloudEdgeSrc)Runtime/Compute/FSharp.CloudEdge.Runtime.Sandbox/FSharp.CloudEdge.Runtime.Sandbox.fsproj" Condition="'$(CloudEdgeUseSource)' == 'true'" />
    <PackageReference Include="FSharp.CloudEdge.Runtime.SandboxBridge" Version="0.1.*" Condition="'$(CloudEdgeUseSource)' != 'true'" />
    <ProjectReference Include="$(CloudEdgeSrc)Runtime/Compute/FSharp.CloudEdge.Runtime.SandboxBridge/FSharp.CloudEdge.Runtime.SandboxBridge.fsproj" Condition="'$(CloudEdgeUseSource)' == 'true'" />
    <PackageReference Include="FSharp.CloudEdge.Runtime.ComputerArtifacts" Version="0.1.*" Condition="'$(CloudEdgeUseSource)' != 'true'" />
    <ProjectReference Include="$(CloudEdgeSrc)Runtime/Compute/FSharp.CloudEdge.Runtime.ComputerArtifacts/FSharp.CloudEdge.Runtime.ComputerArtifacts.fsproj" Condition="'$(CloudEdgeUseSource)' == 'true'" />
    <PackageReference Include="FSharp.CloudEdge.Runtime.Computer" Version="0.1.*" Condition="'$(CloudEdgeUseSource)' != 'true'" />
    <ProjectReference Include="$(CloudEdgeSrc)Runtime/Compute/FSharp.CloudEdge.Runtime.Computer/FSharp.CloudEdge.Runtime.Computer.fsproj" Condition="'$(CloudEdgeUseSource)' == 'true'" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="CodeRunner.fs" />
    <Compile Include="WorkspaceFiles.fs" />
    <Compile Include="Notebook.fs" />
    <Compile Include="TestRunner.fs" />
    <Compile Include="TextSearch.fs" />
    <Compile Include="TeamRepositories.fs" />
    <Compile Include="WorkspacePlan.fs" />
  </ItemGroup>
</Project>
