// <auto-generated>
//   Generated by Xantham.Generator from workers-ai-provider.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec FSharp.CloudEdge.Runtime.WorkersAIProvider

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type ContinentCode =
    | AF
    | AN
    | AS
    | EU
    | NA
    | OC
    | SA

type IncomingRequestCfPropertiesEdgeRequestKeepAliveStatus =
    | N0 = 0
    | N1 = 1
    | N2 = 2
    | N3 = 3
    | N4 = 4
    | N5 = 5

[<Interface>]
type GatewayDelegateError =
    abstract kind: GatewayDelegateErrorKind
    abstract cause: obj option
    abstract name: string with get, set
    abstract message: string with get, set
    abstract stack: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (kind: GatewayDelegateErrorKind, name: string, message: string, ?cause: obj, ?stack: string) : GatewayDelegateError = jsNative
    /// <summary>
    /// Indicates whether the argument provided is a built-in Error instance or not.
    /// </summary>
    [<Import("GatewayDelegateError.isError", "workers-ai-provider")>]
    static member isError (error: obj) : bool = jsNative

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type GatewayDelegateErrorKind =
    | [<CompiledName("config")>] Config
    | [<CompiledName("dispatch")>] Dispatch
    | [<CompiledName("provider")>] Provider
    | [<CompiledName("resume-expired")>] ResumeExpired

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type WireFormat =
    | [<CompiledName("anthropic")>] Anthropic
    | [<CompiledName("google")>] Google
    | [<CompiledName("openai")>] Openai

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type Billing =
    | [<CompiledName("byok")>] Byok
    | [<CompiledName("unified")>] Unified

[<Interface>]
type GatewayProviderInfo =
    /// <summary>
    /// Slug prefix the user types in <c>wai("&lt;resolverKey&gt;/&lt;model&gt;")</c>. For
    /// <c>runCatalog</c> providers this is also the run-catalog author (so
    /// <c>env.AI.run("&lt;resolverKey&gt;/&lt;model&gt;")</c> resolves).
    /// </summary>
    abstract resolverKey: string with get, set
    /// <summary>
    /// Provider id for the gateway universal endpoint (<c>env.AI.gateway().run([{ provider }])</c>).
    /// </summary>
    abstract gatewayProviderId: string with get, set
    /// <summary>
    /// Built-in parser wire format. <c>openai</c> covers the whole OpenAI-compatible
    /// long tail (deepseek, grok, groq, mistral, perplexity, …). Absent ⇒ reachable
    /// only via the bring-your-own-provider wrapper (provider-native, non-chat, or a
    /// gateway-path URL shape we don't reproduce reliably from the slug delegate).
    /// </summary>
    abstract wireFormat: WireFormat option with get, set
    /// <summary>
    /// Wire format the unified-billing <b>run path</b> (<c>env.AI.run</c>) emits for this
    /// provider — which is NOT always the provider's native format. Cloudflare's
    /// unified catalog normalizes most providers to OpenAI chat-completions (so
    /// <c>google</c> is parsed with the <c>openai</c> plugin on the run path), but passes
    /// <b>Anthropic through natively</b> (<c>content[].text</c>, native tool shape), so
    /// anthropic must be parsed with the <c>anthropic</c> plugin. Defaults to <c>"openai"</c>
    /// for run-catalog providers when omitted. Only meaningful when <c>runCatalog</c>.
    /// </summary>
    abstract runWireFormat: WireFormat option with get, set
    /// <summary>
    /// Base URL the wire-format builder should target so the request URL it
    /// generates host-strips (via transformEndpoint) to the provider's
    /// gateway-native endpoint. Omit to use the <c>@ai-sdk</c> provider's default (the
    /// provider's own host — correct for <c>openai</c>/<c>anthropic</c>/<c>google</c>). Required
    /// for OpenAI-wire providers that share the <c>openai</c> plugin but live on a
    /// different host (deepseek, grok, groq, mistral, perplexity, …).
    /// </summary>
    abstract baseURL: string option with get, set
    /// <summary>
    /// On the unified-billing resumable run catalog (<c>env.AI.run</c>, <c>cf-aig-run-id</c>).
    /// </summary>
    abstract runCatalog: bool with get, set
    /// <summary>
    /// Whether the provider has a gateway path (<c>env.AI.gateway().run</c>). <c>false</c> ⇒
    /// <b>run-path only</b>: the provider is on the unified run catalog but is not a
    /// native gateway provider, so caching, server-side fallback, and
    /// <c>transport: "gateway"</c> are unavailable and the delegate rejects them with a
    /// clear error (rather than failing upstream). Defaults to <c>true</c>.
    /// </summary>
    abstract gatewayPath: bool option with get, set
    /// <summary>
    /// Billing model when reached through the gateway.
    /// </summary>
    abstract billing: Billing with get, set
    /// <summary>
    /// Header(s) carrying the upstream provider key (stripped on the gateway path unless BYOK-forwarded).
    /// </summary>
    abstract authHeaders: string[] with get, set
    /// <summary>
    /// Host matcher for bring-your-own-provider URL detection.
    /// </summary>
    abstract hostPattern: obj option with get, set
    /// <summary>
    /// Strip the provider host, leaving the gateway endpoint path (+ query).
    /// </summary>
    abstract transformEndpoint: (string -> string) option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (resolverKey: string, gatewayProviderId: string, runCatalog: bool, billing: Billing, authHeaders: string[], ?wireFormat: WireFormat, ?runWireFormat: WireFormat, ?baseURL: string, ?gatewayPath: bool, ?hostPattern: obj, ?transformEndpoint: (string -> string)) : GatewayProviderInfo = jsNative

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type ResumeExpiredPolicy =
    | [<CompiledName("accept-partial")>] AcceptPartial
    | [<CompiledName("error")>] Error

[<Interface>]
type ResumableStreamOptions =
    /// <summary>
    /// Cloudflare AI binding (e.g. <c>env.AI</c>) — used for the resume fetch.
    /// </summary>
    abstract binding: obj with get, set
    /// <summary>
    /// Gateway id the run was issued under.
    /// </summary>
    abstract gateway: string with get, set
    /// <summary>
    /// The <c>cf-aig-run-id</c> of the run to resume.
    /// </summary>
    abstract runId: string with get, set
    /// <summary>
    /// Initial run-path response body. Omit for <b>cross-invocation re-attach</b>: the
    /// stream then starts by fetching <c>resume?from={fromEvent}</c> directly (e.g. a new
    /// Durable Object invocation re-attaching to a run after eviction).
    /// </summary>
    abstract initial: obj option with get, set
    /// <summary>
    /// SSE event index to (re-)attach from. Defaults to <c>0</c>. Used as the starting
    /// <c>from</c> when <c>initial</c> is omitted, and as the base offset for the event
    /// counter (so a later reconnect resumes from the correct absolute index).
    /// </summary>
    abstract fromEvent: float option with get, set
    /// <summary>
    /// What to do when the resume buffer has expired (404). Defaults to <c>"error"</c>.
    /// </summary>
    abstract onResumeExpired: ResumeExpiredPolicy option with get, set
    /// <summary>
    /// Max reconnect attempts before giving up. Defaults to 5.
    /// </summary>
    abstract maxReconnects: float option with get, set
    /// <summary>
    /// Fired before each reconnect with the resume <c>from</c> index and attempt number.
    /// </summary>
    abstract onReconnect: ResumableStreamOptions.OnReconnect option with get, set
    /// <summary>
    /// Fired with the cumulative SSE event offset whenever complete events are
    /// emitted. Use it to persist <c>{ runId, eventOffset }</c> for cross-invocation
    /// re-attach (throttle your own writes — this can fire per chunk).
    /// </summary>
    abstract onProgress: (float -> unit) option with get, set
    /// <summary>
    /// Abort signal for the consuming request. When it aborts (or the downstream
    /// consumer cancels the wrapped stream), the engine stops <b>without</b>
    /// reconnecting — an intentional cancel must never trigger a resume reconnect.
    /// The signal is also forwarded to the resume fetch.
    /// </summary>
    abstract signal: obj option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (binding: obj, gateway: string, runId: string, ?initial: obj, ?fromEvent: float, ?onResumeExpired: ResumeExpiredPolicy, ?maxReconnects: float, ?onReconnect: ResumableStreamOptions.OnReconnect, ?onProgress: (float -> unit), ?signal: obj) : ResumableStreamOptions = jsNative

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type GatewayErrorCode =
    | [<CompiledName("auth")>] Auth
    | [<CompiledName("bad-request")>] BadRequest
    | [<CompiledName("gateway-error")>] GatewayError
    | [<CompiledName("not-found")>] NotFound
    | [<CompiledName("provider-error")>] ProviderError
    | [<CompiledName("rate-limit")>] RateLimit
    | [<CompiledName("resume-expired")>] ResumeExpired
    | [<CompiledName("unknown")>] Unknown

/// <summary>
/// Context attached to a WorkersAIGatewayError.
/// </summary>
[<Interface>]
type GatewayErrorContext =
    /// <summary>
    /// Gateway provider id (e.g. <c>"openai"</c>, <c>"google-ai-studio"</c>).
    /// </summary>
    abstract provider: string option with get, set
    /// <summary>
    /// Provider-native model id.
    /// </summary>
    abstract modelId: string option with get, set
    /// <summary>
    /// Transport the failed dispatch used.
    /// </summary>
    abstract transport: GatewayErrorContext.Transport option with get, set
    /// <summary>
    /// HTTP status, if any.
    /// </summary>
    abstract status: float option with get, set
    /// <summary>
    /// <c>cf-aig-log-id</c> for cross-referencing in the dashboard.
    /// </summary>
    abstract logId: string option with get, set
    /// <summary>
    /// <c>cf-aig-run-id</c>, if the run path issued one.
    /// </summary>
    abstract runId: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?provider: string, ?modelId: string, ?transport: GatewayErrorContext.Transport, ?status: float, ?logId: string, ?runId: string) : GatewayErrorContext = jsNative

/// <summary>
/// A single dispatch failure through AI Gateway (run or gateway path).
/// </summary>
[<Interface>]
type WorkersAIGatewayError =
    abstract code: GatewayErrorCode
    /// <summary>
    /// Whether a retry or fallback to another model is worth attempting.
    /// </summary>
    abstract recoverable: bool
    abstract status: float option
    abstract context: GatewayErrorContext
    /// <summary>
    /// Parsed gateway/provider error envelope (or raw text).
    /// </summary>
    abstract raw: obj option
    abstract cause: obj option
    abstract name: string with get, set
    abstract message: string with get, set
    abstract stack: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (code: GatewayErrorCode, recoverable: bool, context: GatewayErrorContext, name: string, message: string, ?status: float, ?raw: obj, ?cause: obj, ?stack: string) : WorkersAIGatewayError = jsNative
    /// <summary>
    /// Classify an arbitrary thrown value. Understands AI SDK <c>APICallError</c>
    /// (reads <c>statusCode</c> / <c>responseBody</c> / <c>isRetryable</c>); falls back to a
    /// recoverable <c>gateway-error</c> for transport/connection failures so a fallback
    /// chain keeps trying.
    /// </summary>
    [<Import("WorkersAIGatewayError.fromUnknown", "workers-ai-provider")>]
    static member fromUnknown (e: obj) : WorkersAIGatewayError = jsNative
    /// <summary>
    /// Build from an HTTP <c>Response</c> (reads the body for the envelope).
    /// </summary>
    [<Import("WorkersAIGatewayError.fromResponse", "workers-ai-provider")>]
    static member fromResponse (resp: obj, ?context: GatewayErrorContext) : JS.Promise<WorkersAIGatewayError> = jsNative
    /// <summary>
    /// Indicates whether the argument provided is a built-in Error instance or not.
    /// </summary>
    [<Import("WorkersAIGatewayError.isError", "workers-ai-provider")>]
    static member isError (error: obj) : bool = jsNative

/// <summary>
/// One leg of a client-side fallback chain.
/// </summary>
[<Interface>]
type FallbackAttempt =
    /// <summary>
    /// The model slug attempted.
    /// </summary>
    abstract model: string with get, set
    /// <summary>
    /// Transport used for this attempt.
    /// </summary>
    abstract transport: GatewayErrorContext.Transport with get, set
    /// <summary>
    /// Whether this attempt succeeded.
    /// </summary>
    abstract ok: bool with get, set
    /// <summary>
    /// HTTP status, if any.
    /// </summary>
    abstract status: float option with get, set
    /// <summary>
    /// The classified error, when the attempt failed.
    /// </summary>
    abstract error: WorkersAIGatewayError option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (model: string, transport: GatewayErrorContext.Transport, ok: bool, ?status: float, ?error: WorkersAIGatewayError) : FallbackAttempt = jsNative

/// <summary>
/// Every model in a client-side fallback chain failed.
/// </summary>
[<Interface>]
type WorkersAIFallbackError =
    /// <summary>
    /// The ordered attempt tree (primary first, then each fallback).
    /// </summary>
    abstract attempts: FallbackAttempt[]
    /// <summary>
    /// The last (most recent) attempt's error, if any.
    /// </summary>
    abstract lastError: WorkersAIGatewayError option
    abstract name: string with get, set
    abstract message: string with get, set
    abstract stack: string option with get, set
    abstract cause: obj option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (attempts: FallbackAttempt[], name: string, message: string, ?lastError: WorkersAIGatewayError, ?stack: string, ?cause: obj) : WorkersAIFallbackError = jsNative
    /// <summary>
    /// Indicates whether the argument provided is a built-in Error instance or not.
    /// </summary>
    [<Import("WorkersAIFallbackError.isError", "workers-ai-provider")>]
    static member isError (error: obj) : bool = jsNative

/// <summary>
/// One model in a client-side fallback chain.
/// </summary>
[<Interface>]
type FallbackLeg =
    /// <summary>
    /// The model slug this leg dispatches.
    /// </summary>
    abstract slug: string with get, set
    /// <summary>
    /// The built AI SDK model.
    /// </summary>
    abstract model: FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4 with get, set
    /// <summary>
    /// Transport the leg uses.
    /// </summary>
    abstract transport: Transport with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (slug: string, model: FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4, transport: Transport) : FallbackLeg = jsNative

/// <summary>
/// Gateway delegate — route AI SDK catalog models through Cloudflare AI Gateway,
/// with capability-driven transport selection.
/// <br /><br />
/// Two transports back the same model, chosen from the requested options:
/// <br /><br />
///   - <b>Run path</b> <c>env.AI.run(slug, body, { returnRawResponse })</c> — resumable
///     streaming (<c>cf-aig-run-id</c>). The default.
///   - <b>Gateway path</b> <c>env.AI.gateway(id).run([entry, …fallback])</c> — server-side
///     fallback and caching. Does not surface <c>cf-aig-run-id</c>, so resume is off.
/// <br /><br />
/// The SAME <c>@ai-sdk/*</c> provider parses the response on either path, so there is no
/// per-provider or per-path response parsing here. Provider plugins (which import
/// <c>@ai-sdk/openai</c>, <c>@ai-sdk/anthropic</c>, …) are injected from sub-path modules
/// (<c>workers-ai-provider/openai</c>, …) so those AI SDK packages stay OPTIONAL peer
/// dependencies — you only install the ones you use.
/// </summary>
/// <example>
/// <code>
/// ```ts
/// import { createGatewayDelegate } from "workers-ai-provider/gateway-delegate";
/// import { openai } from "workers-ai-provider/openai";
/// import { streamText } from "ai";
///
/// const wai = createGatewayDelegate({
///   binding: env.AI,
///   gateway: "my-gateway",
///   providers: [openai],
/// });
///
/// const result = streamText({ model: wai("openai/gpt-5"), prompt: "Hello" });
/// // result.response.headers["cf-aig-run-id"] is set — resume from there.
/// </code>
/// <code>
/// </code>
/// </example>
[<Interface>]
type ParsedSlug =
    /// <summary>
    /// First path segment — the registry resolver key (selects provider + wire format).
    /// </summary>
    abstract resolverKey: string with get, set
    /// <summary>
    /// Remaining segments — the provider-native model id.
    /// </summary>
    abstract modelId: string with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (resolverKey: string, modelId: string) : ParsedSlug = jsNative

/// <summary>
/// Adapts a <c>@ai-sdk/*</c> provider to the delegate, keyed by the response wire
/// format it parses. Imported from a sub-path module (e.g.
/// <c>workers-ai-provider/openai</c>) so the AI SDK package stays an optional peer
/// dependency. One plugin serves every registry provider of that wire format —
/// the <c>openai</c> plugin covers the whole OpenAI-compatible long tail (deepseek,
/// grok, groq, mistral, perplexity, openrouter, …).
/// </summary>
[<Interface>]
type ProviderPlugin =
    /// <summary>
    /// The response wire format this builder parses.
    /// </summary>
    abstract wireFormat: WireFormat
    /// <summary>
    /// Build the AI SDK model, wiring the gateway-dispatching <c>fetch</c>. <c>baseURL</c>
    /// (when provided by the registry) targets the provider's host so the request
    /// URL host-strips to its gateway-native endpoint — pass it to the underlying
    /// <c>@ai-sdk</c> provider.
    /// </summary>
    abstract create: args: ProviderPlugin.Create.Args -> FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4
    [<ParamObject; Emit("$0")>]
    static member Create (wireFormat: WireFormat, create: (ProviderPlugin.Create.Args -> FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4)) : ProviderPlugin = jsNative

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type Transport =
    | [<CompiledName("gateway")>] Gateway
    | [<CompiledName("run")>] Run

[<Interface>]
type FallbackOptions =
    /// <summary>
    /// <c>"client"</c> keeps resume (sequential run-path attempts); <c>"server"</c> uses the gateway path.
    /// </summary>
    abstract mode: FallbackOptions.Mode with get, set
    /// <summary>
    /// Ordered model slugs to try after the primary.
    /// </summary>
    abstract models: string[] with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (mode: FallbackOptions.Mode, models: string[]) : FallbackOptions = jsNative

[<Interface>]
type DispatchInfo =
    abstract transport: Transport with get, set
    abstract resumeEnabled: bool with get, set
    abstract warnings: string[] with get, set
    abstract runId: string option with get, set
    abstract status: float option with get, set
    abstract cfStep: string option with get, set
    abstract cacheStatus: string option with get, set
    abstract logId: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (transport: Transport, resumeEnabled: bool, warnings: string[], ?runId: string, ?status: float, ?cfStep: string, ?cacheStatus: string, ?logId: string) : DispatchInfo = jsNative

[<Interface>]
type DelegateCallOptions =
    /// <summary>
    /// Resumable streaming (run path). Defaults to the delegate's <c>resume</c> (true).
    /// </summary>
    abstract resume: bool option with get, set
    /// <summary>
    /// Cross-model fallback. <c>"server"</c> mode uses the gateway path (disables resume).
    /// </summary>
    abstract fallback: FallbackOptions option with get, set
    /// <summary>
    /// Gateway-path response caching (seconds). Forces the gateway path.
    /// </summary>
    abstract cacheTtl: float option with get, set
    /// <summary>
    /// Bypass gateway cache. Forces the gateway path.
    /// </summary>
    abstract skipCache: bool option with get, set
    /// <summary>
    /// Escape hatch: force a transport.
    /// </summary>
    abstract transport: Transport option with get, set
    /// <summary>
    /// Run path only: behavior when the resume buffer has expired (404) after a
    /// mid-stream drop. <c>"error"</c> (default) surfaces a <c>GatewayDelegateError</c>;
    /// <c>"accept-partial"</c> ends the stream cleanly with whatever was delivered.
    /// </summary>
    abstract onResumeExpired: ResumeExpiredPolicy option with get, set
    /// <summary>
    /// Extra request headers (run path: <c>extraHeaders</c>; gateway path: entry headers).
    /// </summary>
    abstract extraHeaders: Record<string, string> option with get, set
    /// <summary>
    /// Gateway path only: forward the upstream provider key instead of stripping it.
    /// Required for BYOK providers (not on unified billing). Supply the key via
    /// <c>extraHeaders</c> (e.g. <c>{ authorization: "Bearer …" }</c>); without <c>byok</c> the
    /// delegate strips provider auth headers so unified billing applies.
    /// </summary>
    abstract byok: bool option with get, set
    /// <summary>
    /// Gateway path only: BYOK stored-key alias to authenticate with
    /// (<c>cf-aig-byok-alias</c>). Selects a non-<c>default</c> key you configured for the
    /// provider on the gateway. Independent of <c>byok</c> (which controls whether the
    /// caller's own provider auth header is forwarded vs. stripped).
    /// </summary>
    abstract byokAlias: string option with get, set
    /// <summary>
    /// Per-request Zero Data Retention override (<c>cf-aig-zdr</c>), Unified Billing
    /// only: <c>true</c> forces ZDR-capable upstreams, <c>false</c> disables it for this
    /// request. Overrides the gateway-level ZDR default. Applied on both transports
    /// (run path: passed through gateway options as a header; gateway path: entry header).
    /// </summary>
    abstract zdr: bool option with get, set
    /// <summary>
    /// Override the delegate's gateway for this model.
    /// </summary>
    abstract gateway: obj option with get, set
    /// <summary>
    /// Custom metadata attached to the gateway log for this request (spend
    /// attribution, tenant ids, etc.). Merges over any <c>metadata</c> already set via
    /// <c>gateway: { metadata }</c>. Applied on both transports (run path: gateway
    /// options; gateway path: <c>cf-aig-metadata</c> header). <c>bigint</c> values are
    /// coerced to strings for the header form.
    /// </summary>
    abstract metadata: Record<string, U4<string, float, bigint, bool> option> option with get, set
    /// <summary>
    /// Force gateway log collection on/off for this request (both transports).
    /// </summary>
    abstract collectLog: bool option with get, set
    /// <summary>
    /// Called once per dispatch with the resolved transport + gateway headers.
    /// </summary>
    abstract onDispatch: (DispatchInfo -> unit) option with get, set
    /// <summary>
    /// Run path only: fired with the cumulative SSE event offset as the resumable
    /// stream advances. Pair with <c>onDispatch</c> (for <c>runId</c>) to persist
    /// <c>{ runId, eventOffset }</c> for cross-invocation re-attach after eviction.
    /// Throttle your own writes — this can fire per chunk.
    /// </summary>
    abstract onProgress: (float -> unit) option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?resume: bool, ?fallback: FallbackOptions, ?cacheTtl: float, ?skipCache: bool, ?transport: Transport, ?onResumeExpired: ResumeExpiredPolicy, ?extraHeaders: Record<string, string>, ?byok: bool, ?byokAlias: string, ?zdr: bool, ?gateway: obj, ?metadata: Record<string, U4<string, float, bigint, bool> option>, ?collectLog: bool, ?onDispatch: (DispatchInfo -> unit), ?onProgress: (float -> unit)) : DelegateCallOptions = jsNative

[<Interface>]
type Selection =
    abstract transport: Transport with get, set
    abstract resumeEnabled: bool with get, set
    abstract warnings: string[] with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (transport: Transport, resumeEnabled: bool, warnings: string[]) : Selection = jsNative

/// <summary>
/// Bring-your-own-provider: route any <c>@ai-sdk/*</c> provider's HTTP traffic through
/// Cloudflare AI Gateway, without the catalog slug delegate. The provider keeps
/// its own request/response shaping; this only swaps the transport.
/// <br /><br />
/// Use it for providers the slug delegate cannot auto-wire (bedrock, replicate,
/// audio/image providers, anything provider-native), or when you want full control
/// of the underlying <c>@ai-sdk</c> provider. This is the gateway path only — BYOK and
/// caching are available, resume (<c>cf-aig-run-id</c>) is not.
/// </summary>
/// <example>
/// <code>
/// ```ts
/// import { createOpenAI } from "@ai-sdk/openai";
/// import { createGatewayFetch } from "workers-ai-provider/gateway";
///
/// const openai = createOpenAI({
///   apiKey: env.OPENAI_API_KEY, // forwarded when byok: true
///   fetch: createGatewayFetch({ binding: env.AI, gateway: "my-gw", byok: true }),
/// });
/// const model = openai("gpt-5");
/// </code>
/// <code>
/// </code>
/// </example>
[<Interface>]
type GatewayFetchConfig =
    /// <summary>
    /// A Cloudflare AI binding (e.g. <c>env.AI</c>).
    /// </summary>
    abstract binding: obj with get, set
    /// <summary>
    /// Gateway id (or options).
    /// </summary>
    abstract gateway: obj with get, set
    /// <summary>
    /// Force a gateway provider id instead of detecting it from the request URL.
    /// Required when the wrapped provider's host is not in the registry.
    /// </summary>
    abstract provider: string option with get, set
    /// <summary>
    /// Forward the upstream provider key (Authorization / x-api-key / …) instead of
    /// stripping it. Required for BYOK providers. Defaults to <c>false</c> (strip, so
    /// unified billing / the gateway's stored key applies).
    /// </summary>
    abstract byok: bool option with get, set
    /// <summary>
    /// Extra headers added to every gateway entry.
    /// </summary>
    abstract extraHeaders: Record<string, string> option with get, set
    /// <summary>
    /// Gateway-path response caching (seconds).
    /// </summary>
    abstract cacheTtl: float option with get, set
    /// <summary>
    /// Bypass gateway cache.
    /// </summary>
    abstract skipCache: bool option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (binding: obj, gateway: obj, ?provider: string, ?byok: bool, ?extraHeaders: Record<string, string>, ?cacheTtl: float, ?skipCache: bool) : GatewayFetchConfig = jsNative

/// <remarks>@deprecated Use <c>AISearchChatSettings</c> instead. AutoRAG has been renamed to AI Search.</remarks>
/// <remarks>@see https://developers.cloudflare.com/ai-search/</remarks>
type AISearchChatSettings =
    /// <summary>
    /// Whether to inject a safety prompt before all conversations.
    /// Defaults to <c>false</c>.
    /// </summary>
    abstract safePrompt: bool option with get, set
    [<EmitIndexer>]
    abstract Item: string -> obj with get, set

[<Interface>]
type AISearchChatLanguageModel =
    inherit FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4
    abstract defaultObjectGenerationMode: string
    abstract supportedUrls: U2<JS.Promise<Record<string, obj[]>>, Record<string, obj[]>>
    abstract modelId: TextGenerationModels
    abstract settings: AISearchChatSettings
    abstract config: obj
    abstract getWarnings: obj with get, set
    /// <summary>
    /// Build the search query from messages.
    /// Flattens the conversation into a single string for aiSearch.
    /// </summary>
    abstract buildQuery: obj with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (specificationVersion: string, defaultObjectGenerationMode: string, supportedUrls: U2<JS.Promise<Record<string, obj[]>>, Record<string, obj[]>>, modelId: TextGenerationModels, settings: AISearchChatSettings, config: obj, provider: string, getWarnings: obj, buildQuery: obj, doGenerate: (FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4GenerateResult>), doStream: (FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4StreamResult>)) : AISearchChatLanguageModel = jsNative

type TextGenerationModels = string

[<Interface>]
type WorkersAITranscriptionSettings =
    /// <summary>
    /// Language of the audio, as an ISO-639-1 code (e.g. "en", "fr").
    /// Only supported by Whisper models. Nova-3 detects language automatically.
    /// </summary>
    abstract language: string option with get, set
    /// <summary>
    /// Initial prompt / context to guide the transcription.
    /// Mapped to <c>initial_prompt</c> for Whisper models.
    /// </summary>
    abstract prompt: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?language: string, ?prompt: string) : WorkersAITranscriptionSettings = jsNative

[<Interface>]
type CreateRunConfig =
    /// <summary>
    /// Your Cloudflare account identifier.
    /// </summary>
    abstract accountId: string with get, set
    /// <summary>
    /// Cloudflare API token/key with appropriate permissions.
    /// </summary>
    abstract apiKey: string with get, set
    /// <summary>
    /// Custom fetch implementation for intercepting requests.
    /// </summary>
    abstract fetch: Func<obj, obj option, JS.Promise<obj>> option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (accountId: string, apiKey: string, ?fetch: Func<obj, obj option, JS.Promise<obj>>) : CreateRunConfig = jsNative

type TranscriptionModels = string

/// <summary>
/// Workers AI transcription model implementing the AI SDK's <c>TranscriptionModelV4</c> interface.
/// <br /><br />
/// Supports:
/// - Whisper models (<c>@cf/openai/whisper</c>, <c>whisper-tiny-en</c>, <c>whisper-large-v3-turbo</c>)
/// - Deepgram Nova-3 (<c>@cf/deepgram/nova-3</c>) — uses a different input/output format
/// </summary>
[<Interface>]
type WorkersAITranscriptionModel =
    inherit FSharp.CloudEdge.Support.AI.V4.Provider.TranscriptionModelV4
    abstract modelId: TranscriptionModels
    abstract settings: WorkersAITranscriptionSettings
    abstract config: WorkersAITranscriptionModel.Config
    abstract runWhisper: obj with get, set
    abstract normalizeWhisperResponse: obj with get, set
    abstract runNova3: obj with get, set
    abstract normalizeNova3Response: obj with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (modelId: TranscriptionModels, settings: WorkersAITranscriptionSettings, config: WorkersAITranscriptionModel.Config, specificationVersion: string, provider: string, doGenerate: (FSharp.CloudEdge.Support.AI.V4.Provider.TranscriptionModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.TranscriptionModelV4Result>), runWhisper: obj, normalizeWhisperResponse: obj, runNova3: obj, normalizeNova3Response: obj) : WorkersAITranscriptionModel = jsNative

type WorkersAISpeechSettings = obj

type SpeechModels = string

/// <summary>
/// Workers AI speech (text-to-speech) model implementing the AI SDK's <c>SpeechModelV4</c> interface.
/// <br /><br />
/// Currently supports Deepgram Aura-1 (<c>@cf/deepgram/aura-1</c>).
/// The model accepts <c>{ text, voice?, speed? }</c> and returns raw audio bytes.
/// </summary>
[<Interface>]
type WorkersAISpeechModel =
    inherit FSharp.CloudEdge.Support.AI.V4.Provider.SpeechModelV4
    abstract modelId: SpeechModels
    abstract settings: WorkersAISpeechSettings
    abstract config: WorkersAISpeechModel.Config
    [<ParamObject; Emit("$0")>]
    static member Create (modelId: SpeechModels, settings: WorkersAISpeechSettings, config: WorkersAISpeechModel.Config, specificationVersion: string, provider: string, doGenerate: (FSharp.CloudEdge.Support.AI.V4.Provider.SpeechModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.SpeechModelV4Result>)) : WorkersAISpeechModel = jsNative

type WorkersAIRerankingSettings = obj

type RerankingModels = string

/// <summary>
/// Workers AI reranking model implementing the AI SDK's <c>RerankingModelV4</c> interface.
/// <br /><br />
/// Supports BGE reranker models (<c>@cf/baai/bge-reranker-base</c>, <c>bge-reranker-v2-m3</c>).
/// <br /><br />
/// Workers AI reranking API:
/// - Input: <c>{ query, contexts: [{ text }], top_k? }</c>
/// - Output: <c>{ response: [{ id, score }] }</c>
/// </summary>
[<Interface>]
type WorkersAIRerankingModel =
    inherit FSharp.CloudEdge.Support.AI.V4.Provider.RerankingModelV4
    abstract modelId: RerankingModels
    abstract settings: WorkersAIRerankingSettings
    abstract config: WorkersAIRerankingModel.Config
    [<ParamObject; Emit("$0")>]
    static member Create (modelId: RerankingModels, settings: WorkersAIRerankingSettings, config: WorkersAIRerankingModel.Config, specificationVersion: string, provider: string, doRerank: (FSharp.CloudEdge.Support.AI.V4.Provider.RerankingModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.RerankingModelV4Result>)) : WorkersAIRerankingModel = jsNative

/// <remarks>@deprecated Use <c>AISearchChatLanguageModel</c> instead. AutoRAG has been renamed to AI Search.</remarks>
/// <remarks>@see https://developers.cloudflare.com/ai-search/</remarks>
[<Interface>]
type AutoRAGChatLanguageModel =
    inherit AISearchChatLanguageModel
    [<ParamObject; Emit("$0")>]
    static member Create (specificationVersion: string, defaultObjectGenerationMode: string, supportedUrls: U2<JS.Promise<Record<string, obj[]>>, Record<string, obj[]>>, modelId: TextGenerationModels, settings: AISearchChatSettings, config: obj, provider: string, getWarnings: obj, buildQuery: obj, doGenerate: (FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4GenerateResult>), doStream: (FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4StreamResult>)) : AutoRAGChatLanguageModel = jsNative

/// <remarks>@deprecated Use <c>AISearchChatSettings</c> instead. AutoRAG has been renamed to AI Search.</remarks>
/// <remarks>@see https://developers.cloudflare.com/ai-search/</remarks>
type AutoRAGChatSettings = AISearchChatSettings

type WorkersAISettings = U2<WorkersAISettings2, WorkersAISettings3>

[<Interface>]
type WorkersAISettings2 =
    /// <summary>
    /// Provide a Cloudflare AI binding.
    /// </summary>
    abstract binding: obj with get, set
    /// <summary>
    /// Credentials must be absent when a binding is given.
    /// </summary>
    abstract accountId: unit option with get, set
    abstract apiKey: unit option with get, set
    /// <summary>
    /// Optionally specify a gateway. For third-party catalog routing (see
    /// <c>providers</c>) this defaults to the account's <c>"default"</c> gateway when unset.
    /// </summary>
    abstract gateway: obj option with get, set
    /// <summary>
    /// Provider plugins that enable routing third-party catalog models
    /// (e.g. <c>"openai/gpt-5-mini"</c>) through AI Gateway. Supply them from the
    /// sub-path modules, e.g. <c>import { openai } from "workers-ai-provider/openai"</c>.
    /// <br /><br />
    /// When set, calling the provider with a <c>"&lt;provider&gt;/&lt;model&gt;"</c> slug (anything
    /// that is not a <c>@cf/...</c> Workers AI model id) is automatically dispatched
    /// through the createGatewayDelegate | gateway delegate. Leaving this
    /// unset preserves the exact prior behavior — only Workers AI models are built.
    /// </summary>
    /// <remarks>@experimental The gateway delegate is an experimental surface.</remarks>
    abstract providers: ProviderPlugin[] option with get, set
    /// <summary>
    /// Default resume behavior for gateway-routed catalog models. Defaults to
    /// <c>true</c>. Overridable per call. Only relevant when <c>providers</c> is set.
    /// </summary>
    abstract resume: bool option with get, set
    /// <summary>
    /// Default resume-expiry policy for gateway-routed catalog models (run path).
    /// Defaults to <c>"error"</c>. Only relevant when <c>providers</c> is set.
    /// </summary>
    abstract onResumeExpired: ResumeExpiredPolicy option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (binding: obj, ?accountId: unit, ?apiKey: unit, ?gateway: obj, ?providers: ProviderPlugin[], ?resume: bool, ?onResumeExpired: ResumeExpiredPolicy) : WorkersAISettings2 = jsNative

[<Interface>]
type WorkersAISettings3 =
    /// <summary>
    /// Provide Cloudflare API credentials directly. Must be used if a binding is not specified.
    /// </summary>
    abstract accountId: string with get, set
    abstract apiKey: string with get, set
    /// <summary>
    /// Both binding must be absent if credentials are used directly.
    /// </summary>
    abstract binding: unit option with get, set
    /// <summary>
    /// Custom fetch implementation. You can use it as a middleware to
    /// intercept requests, or to provide a custom fetch implementation
    /// for e.g. testing. Only available in credentials mode.
    /// </summary>
    abstract fetch: Func<obj, obj option, JS.Promise<obj>> option with get, set
    /// <summary>
    /// Optionally specify a gateway. For third-party catalog routing (see
    /// <c>providers</c>) this defaults to the account's <c>"default"</c> gateway when unset.
    /// </summary>
    abstract gateway: obj option with get, set
    /// <summary>
    /// Provider plugins that enable routing third-party catalog models
    /// (e.g. <c>"openai/gpt-5-mini"</c>) through AI Gateway. Supply them from the
    /// sub-path modules, e.g. <c>import { openai } from "workers-ai-provider/openai"</c>.
    /// <br /><br />
    /// When set, calling the provider with a <c>"&lt;provider&gt;/&lt;model&gt;"</c> slug (anything
    /// that is not a <c>@cf/...</c> Workers AI model id) is automatically dispatched
    /// through the createGatewayDelegate | gateway delegate. Leaving this
    /// unset preserves the exact prior behavior — only Workers AI models are built.
    /// </summary>
    /// <remarks>@experimental The gateway delegate is an experimental surface.</remarks>
    abstract providers: ProviderPlugin[] option with get, set
    /// <summary>
    /// Default resume behavior for gateway-routed catalog models. Defaults to
    /// <c>true</c>. Overridable per call. Only relevant when <c>providers</c> is set.
    /// </summary>
    abstract resume: bool option with get, set
    /// <summary>
    /// Default resume-expiry policy for gateway-routed catalog models (run path).
    /// Defaults to <c>"error"</c>. Only relevant when <c>providers</c> is set.
    /// </summary>
    abstract onResumeExpired: ResumeExpiredPolicy option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (accountId: string, apiKey: string, ?binding: unit, ?fetch: Func<obj, obj option, JS.Promise<obj>>, ?gateway: obj, ?providers: ProviderPlugin[], ?resume: bool, ?onResumeExpired: ResumeExpiredPolicy) : WorkersAISettings3 = jsNative

type EmbeddingModels = string

type ImageGenerationModels = string

[<Interface>]
type WorkersAI =
    /// <summary>
    /// Creates a model for text generation. Accepts a <c>@cf/...</c> Workers AI id, or
    /// a <c>"&lt;provider&gt;/&lt;model&gt;"</c> catalog slug when <c>providers</c> is configured.
    /// </summary>
    abstract chat<'M>: modelId: U2<string, 'M> * ?settings: obj -> WorkersAIChatLanguageModel
    abstract embedding: modelId: EmbeddingModels * ?settings: WorkersAI.Embedding.Settings -> WorkersAIEmbeddingModel
    abstract textEmbedding: modelId: EmbeddingModels * ?settings: WorkersAI.Embedding.Settings -> WorkersAIEmbeddingModel
    abstract textEmbeddingModel: modelId: EmbeddingModels * ?settings: WorkersAI.Embedding.Settings -> WorkersAIEmbeddingModel
    /// <summary>
    /// Creates a model for image generation.
    /// </summary>
    abstract image: modelId: ImageGenerationModels * ?settings: WorkersAI.Image.Settings -> WorkersAIImageModel
    abstract imageModel: modelId: ImageGenerationModels * ?settings: WorkersAI.Image.Settings -> WorkersAIImageModel
    /// <summary>
    /// Creates a model for speech-to-text transcription.
    /// </summary>
    abstract transcription: modelId: TranscriptionModels * ?settings: WorkersAITranscriptionSettings -> WorkersAITranscriptionModel
    abstract transcriptionModel: modelId: TranscriptionModels * ?settings: WorkersAITranscriptionSettings -> WorkersAITranscriptionModel
    /// <summary>
    /// Creates a model for text-to-speech synthesis.
    /// </summary>
    abstract speech: modelId: SpeechModels * ?settings: WorkersAISpeechSettings -> WorkersAISpeechModel
    abstract speechModel: modelId: SpeechModels * ?settings: WorkersAISpeechSettings -> WorkersAISpeechModel
    /// <summary>
    /// Creates a model for document reranking.
    /// </summary>
    abstract reranking: modelId: RerankingModels * ?settings: WorkersAIRerankingSettings -> WorkersAIRerankingModel
    abstract rerankingModel: modelId: RerankingModels * ?settings: WorkersAIRerankingSettings -> WorkersAIRerankingModel
    [<Emit("$0($1...)")>]
    abstract Invoke<'M>: modelId: U2<string, 'M> * ?settings: obj -> WorkersAIChatLanguageModel
    [<ParamObject; Emit("$0")>]
    static member Create (chat: Func<U2<string, 'M>, obj option, WorkersAIChatLanguageModel>, embedding: Func<EmbeddingModels, WorkersAI.Embedding.Settings option, WorkersAIEmbeddingModel>, textEmbedding: Func<EmbeddingModels, WorkersAI.Embedding.Settings option, WorkersAIEmbeddingModel>, textEmbeddingModel: Func<EmbeddingModels, WorkersAI.Embedding.Settings option, WorkersAIEmbeddingModel>, image: Func<ImageGenerationModels, WorkersAI.Image.Settings option, WorkersAIImageModel>, imageModel: Func<ImageGenerationModels, WorkersAI.Image.Settings option, WorkersAIImageModel>, transcription: Func<TranscriptionModels, WorkersAITranscriptionSettings option, WorkersAITranscriptionModel>, transcriptionModel: Func<TranscriptionModels, WorkersAITranscriptionSettings option, WorkersAITranscriptionModel>, speech: Func<SpeechModels, WorkersAISpeechSettings option, WorkersAISpeechModel>, speechModel: Func<SpeechModels, WorkersAISpeechSettings option, WorkersAISpeechModel>, reranking: Func<RerankingModels, WorkersAIRerankingSettings option, WorkersAIRerankingModel>, rerankingModel: Func<RerankingModels, WorkersAIRerankingSettings option, WorkersAIRerankingModel>) : WorkersAI = jsNative

[<Interface>]
type WorkersAIChatLanguageModel =
    inherit FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4
    abstract defaultObjectGenerationMode: string
    abstract supportedUrls: U2<JS.Promise<Record<string, obj[]>>, Record<string, obj[]>>
    abstract modelId: TextGenerationModels
    abstract settings: WorkersAIChatLanguageModel.Settings
    abstract config: obj
    abstract getArgs: obj with get, set
    /// <summary>
    /// Build the inputs object for <c>binding.run()</c>, shared by doGenerate and doStream.
    /// <br /><br />
    /// Images are embedded inline in messages as OpenAI-compatible content
    /// arrays with <c>image_url</c> parts. Both the REST API and the binding
    /// accept this format at runtime.
    /// <br /><br />
    /// The binding path additionally normalises null content to empty strings.
    /// <br /><br />
    /// Reasoning controls (<c>reasoning_effort</c>, <c>chat_template_kwargs</c>) are
    /// forwarded here from settings. These belong on the INPUTS object, not on
    /// the 3rd-arg options / REST query string — see
    /// https://github.com/cloudflare/ai/issues/501. Per-call values from
    /// <c>providerOptions["workers-ai"]</c> override settings.
    /// <br /><br />
    /// <c>reasoning_effort: null</c> is a valid value ("disable reasoning"), so we
    /// check <c>!== undefined</c> rather than truthiness.
    /// <br /><br />
    /// The unified <c>reasoning</c> call option (spec v4) is mapped onto
    /// <c>reasoning_effort</c> between the two: an explicit per-call
    /// <c>providerOptions["workers-ai"].reasoning_effort</c> wins, then the unified
    /// option, then settings.
    /// </summary>
    abstract buildRunInputs: obj with get, set
    /// <summary>
    /// Get passthrough options for binding.run() from settings.
    /// <br /><br />
    /// <c>reasoning_effort</c> and <c>chat_template_kwargs</c> are explicitly excluded
    /// here — they belong on the <c>inputs</c> object (see <c>buildRunInputs</c>), not on
    /// the <c>options</c> (3rd) arg of binding.run() or the REST query string.
    /// </summary>
    abstract getRunOptions: obj with get, set
    /// <summary>
    /// Extract reasoning, text, and tool calls from a non-streaming response.
    /// <br /><br />
    /// Shared by <c>doGenerate</c> and <c>doStream</c>'s graceful-degradation branch (the
    /// path gpt-oss falls through, since it doesn't support <c>/ai/run/</c> streaming
    /// and is retried non-streaming). When a forced tool call was leaked into
    /// text content (gpt-oss harmony quirk), it is salvaged into a structured
    /// tool call and the leaked JSON text is suppressed. A warning is appended in
    /// place so callers can observe the reinterpretation.
    /// </summary>
    abstract extractContent: obj with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (specificationVersion: string, defaultObjectGenerationMode: string, supportedUrls: U2<JS.Promise<Record<string, obj[]>>, Record<string, obj[]>>, modelId: TextGenerationModels, settings: WorkersAIChatLanguageModel.Settings, config: obj, provider: string, getArgs: obj, buildRunInputs: obj, getRunOptions: obj, extractContent: obj, doGenerate: (FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4GenerateResult>), doStream: (FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4StreamResult>)) : WorkersAIChatLanguageModel = jsNative

[<Interface>]
type WorkersAIEmbeddingModel =
    inherit FSharp.CloudEdge.Support.AI.V4.Provider.EmbeddingModelV4
    abstract modelId: EmbeddingModels
    abstract config: obj
    abstract settings: obj
    abstract maxEmbeddingsPerCall: float
    abstract supportsParallelCalls: bool
    abstract doEmbed: __0: FSharp.CloudEdge.Support.AI.V4.Provider.EmbeddingModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.EmbeddingModelV4Result>
    [<ParamObject; Emit("$0")>]
    static member Create (specificationVersion: string, modelId: EmbeddingModels, config: obj, settings: obj, provider: string, maxEmbeddingsPerCall: float, supportsParallelCalls: bool, doEmbed: (FSharp.CloudEdge.Support.AI.V4.Provider.EmbeddingModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.EmbeddingModelV4Result>)) : WorkersAIEmbeddingModel = jsNative

[<Interface>]
type WorkersAIImageModel =
    inherit FSharp.CloudEdge.Support.AI.V4.Provider.ImageModelV4
    abstract modelId: ImageGenerationModels
    abstract settings: WorkersAI.Image.Settings
    abstract config: WorkersAIImageModel.Config
    abstract maxImagesPerCall: float
    abstract doGenerate: __0: FSharp.CloudEdge.Support.AI.V4.Provider.ImageModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.ImageModelV4Result>
    [<ParamObject; Emit("$0")>]
    static member Create (modelId: ImageGenerationModels, settings: WorkersAI.Image.Settings, config: WorkersAIImageModel.Config, specificationVersion: string, maxImagesPerCall: float, provider: string, doGenerate: (FSharp.CloudEdge.Support.AI.V4.Provider.ImageModelV4CallOptions -> JS.Promise<FSharp.CloudEdge.Support.AI.V4.Provider.ImageModelV4Result>)) : WorkersAIImageModel = jsNative

/// <remarks>@deprecated Use <c>AISearchSettings</c> instead. AutoRAG has been renamed to AI Search.</remarks>
/// <remarks>@see https://developers.cloudflare.com/ai-search/</remarks>
[<Interface>]
type AISearchSettings =
    abstract binding: obj with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (binding: obj) : AISearchSettings = jsNative

/// <remarks>@deprecated Use <c>AISearchProvider</c> instead. AutoRAG has been renamed to AI Search.</remarks>
/// <remarks>@see https://developers.cloudflare.com/ai-search/</remarks>
[<Interface>]
type AISearchProvider =
    /// <summary>
    /// Creates a model for text generation.
    /// </summary>
    abstract chat: ?settings: AISearchChatSettings -> AISearchChatLanguageModel
    [<Emit("$0($1...)")>]
    abstract Invoke: ?settings: AISearchChatSettings -> AISearchChatLanguageModel
    [<ParamObject; Emit("$0")>]
    static member Create (chat: (AISearchChatSettings option -> AISearchChatLanguageModel)) : AISearchProvider = jsNative

/// <remarks>@deprecated Use <c>AISearchSettings</c> instead. AutoRAG has been renamed to AI Search.</remarks>
/// <remarks>@see https://developers.cloudflare.com/ai-search/</remarks>
type AutoRAGSettings = AISearchSettings

/// <remarks>@deprecated Use <c>AISearchProvider</c> instead. AutoRAG has been renamed to AI Search.</remarks>
/// <remarks>@see https://developers.cloudflare.com/ai-search/</remarks>
type AutoRAGProvider = AISearchProvider

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    [<Import("GatewayDelegateError", "workers-ai-provider"); EmitConstructor>]
    static member GatewayDelegateError (kind: GatewayDelegateErrorKind, message: string, ?cause: obj) : GatewayDelegateError = jsNative
    /// <summary>
    /// The provider table. Order matters only for <c>detectProviderByUrl</c> (first match
    /// wins); slugs are looked up by <c>resolverKey</c>.
    /// </summary>
    [<Import("GATEWAY_PROVIDERS", "workers-ai-provider")>]
    static member GATEWAY_PROVIDERS: GatewayProviderInfo[] = jsNative
    /// <summary>
    /// Look up a provider by the slug prefix the user typed (honoring aliases).
    /// </summary>
    [<Import("findProviderBySlug", "workers-ai-provider")>]
    static member findProviderBySlug (resolverKey: string) : GatewayProviderInfo option = jsNative
    /// <summary>
    /// Detect the gateway provider from a wrapped provider's request URL (BYOG).
    /// </summary>
    [<Import("detectProviderByUrl", "workers-ai-provider")>]
    static member detectProviderByUrl (url: string) : GatewayProviderInfo option = jsNative
    /// <summary>
    /// All slug keys with a built-in parser (auto-wireable by the slug delegate).
    /// </summary>
    [<Import("wireableProviders", "workers-ai-provider")>]
    static member wireableProviders () : GatewayProviderInfo[] = jsNative
    [<Import("createResumableStream", "workers-ai-provider")>]
    static member createResumableStream (options: ResumableStreamOptions) : obj = jsNative
    /// <summary>
    /// A single dispatch failure through AI Gateway (run or gateway path).
    /// </summary>
    [<Import("WorkersAIGatewayError", "workers-ai-provider"); EmitConstructor>]
    static member WorkersAIGatewayError (code: GatewayErrorCode, message: string, ?opts: WorkersAIGatewayError.Opts) : WorkersAIGatewayError = jsNative
    /// <summary>
    /// Every model in a client-side fallback chain failed.
    /// </summary>
    [<Import("WorkersAIFallbackError", "workers-ai-provider"); EmitConstructor>]
    static member WorkersAIFallbackError (attempts: FallbackAttempt[], ?message: string) : WorkersAIFallbackError = jsNative
    /// <summary>
    /// Wrap a chain of models so a failed <i>pre-stream</i> dispatch falls through to the
    /// next model, preserving resume on each leg's own transport. If every leg fails,
    /// throws a WorkersAIFallbackError carrying the full attempt tree.
    /// <br /><br />
    /// Fallback triggers on <c>doGenerate</c>/<c>doStream</c> rejection (the dispatch never
    /// produced a stream). Errors that surface <i>mid-stream</i> — after content has
    /// already been emitted — are not recoverable here and propagate as-is.
    /// </summary>
    [<Import("createClientFallbackModel", "workers-ai-provider")>]
    static member createClientFallbackModel (legs: FallbackLeg[]) : FSharp.CloudEdge.Support.AI.V4.Provider.LanguageModelV4 = jsNative
    /// <summary>
    /// Parse a <c>vendor/model</c> slug. The first segment is the resolver key (which
    /// registry entry handles it); the rest is the provider-native model id. Routing
    /// providers keep multi-segment model ids, e.g. <c>openrouter/anthropic/claude</c>.
    /// </summary>
    [<Import("parseSlug", "workers-ai-provider")>]
    static member parseSlug (slug: string) : ParsedSlug = jsNative
    /// <summary>
    /// Resolve the transport from the requested options. Gateway-only features (server
    /// fallback, caching) force the gateway path and disable resume — with a loud
    /// warning if resume was merely defaulted, or a thrown error if it was explicitly
    /// requested.
    /// </summary>
    [<Import("selectTransport", "workers-ai-provider")>]
    static member selectTransport (opts: DelegateCallOptions, resumeExplicitlyTrue: bool, ?runCatalog: bool, ?gatewayAvailable: bool) : Selection = jsNative
    /// <summary>
    /// A <c>fetch</c> that dispatches the wrapped provider's request through AI Gateway.
    /// Detects the gateway provider id from the request URL (or uses <c>config.provider</c>),
    /// strips the provider host to the endpoint path, and forwards the body verbatim.
    /// </summary>
    [<Import("createGatewayFetch", "workers-ai-provider")>]
    static member createGatewayFetch (config: GatewayFetchConfig) : Func<obj, obj option, JS.Promise<obj>> = jsNative
    /// <summary>
    /// Wrap an <c>@ai-sdk/*</c> provider factory so its traffic flows through AI Gateway.
    /// A thin convenience over createGatewayFetch — it injects the gateway
    /// <c>fetch</c> (and a placeholder <c>apiKey</c> unless you supply one for BYOK).
    /// </summary>
    /// <example>
    /// <code>
    /// ```ts
    /// import { createOpenAI } from "@ai-sdk/openai";
    /// import { createGatewayProvider } from "workers-ai-provider/gateway";
    ///
    /// const openai = createGatewayProvider(createOpenAI, {
    ///   binding: env.AI,
    ///   gateway: "my-gw",
    /// });
    /// const model = openai("gpt-5");
    /// </code>
    /// <code>
    /// </code>
    /// </example>
    [<Import("createGatewayProvider", "workers-ai-provider")>]
    static member createGatewayProvider<'T> (factory: (CreateGatewayProvider.Factory.Opts -> 'T), config: CreateGatewayProvider.Config) : 'T = jsNative
    [<Import("AISearchChatLanguageModel", "workers-ai-provider"); EmitConstructor>]
    static member AISearchChatLanguageModel (modelId: TextGenerationModels, settings: AISearchChatSettings, config: AISearchChatLanguageModel.Config) : AISearchChatLanguageModel = jsNative
    /// <summary>
    /// Workers AI transcription model implementing the AI SDK's <c>TranscriptionModelV4</c> interface.
    /// <br /><br />
    /// Supports:
    /// - Whisper models (<c>@cf/openai/whisper</c>, <c>whisper-tiny-en</c>, <c>whisper-large-v3-turbo</c>)
    /// - Deepgram Nova-3 (<c>@cf/deepgram/nova-3</c>) — uses a different input/output format
    /// </summary>
    [<Import("WorkersAITranscriptionModel", "workers-ai-provider"); EmitConstructor>]
    static member WorkersAITranscriptionModel (modelId: TranscriptionModels, settings: WorkersAITranscriptionSettings, config: WorkersAITranscriptionModel.Config) : WorkersAITranscriptionModel = jsNative
    /// <summary>
    /// Workers AI speech (text-to-speech) model implementing the AI SDK's <c>SpeechModelV4</c> interface.
    /// <br /><br />
    /// Currently supports Deepgram Aura-1 (<c>@cf/deepgram/aura-1</c>).
    /// The model accepts <c>{ text, voice?, speed? }</c> and returns raw audio bytes.
    /// </summary>
    [<Import("WorkersAISpeechModel", "workers-ai-provider"); EmitConstructor>]
    static member WorkersAISpeechModel (modelId: SpeechModels, settings: WorkersAISpeechSettings, config: WorkersAISpeechModel.Config) : WorkersAISpeechModel = jsNative
    /// <summary>
    /// Workers AI reranking model implementing the AI SDK's <c>RerankingModelV4</c> interface.
    /// <br /><br />
    /// Supports BGE reranker models (<c>@cf/baai/bge-reranker-base</c>, <c>bge-reranker-v2-m3</c>).
    /// <br /><br />
    /// Workers AI reranking API:
    /// - Input: <c>{ query, contexts: [{ text }], top_k? }</c>
    /// - Output: <c>{ response: [{ id, score }] }</c>
    /// </summary>
    [<Import("WorkersAIRerankingModel", "workers-ai-provider"); EmitConstructor>]
    static member WorkersAIRerankingModel (modelId: RerankingModels, settings: WorkersAIRerankingSettings, config: WorkersAIRerankingModel.Config) : WorkersAIRerankingModel = jsNative
    /// <remarks>@deprecated Use <c>AISearchChatLanguageModel</c> instead. AutoRAG has been renamed to AI Search.</remarks>
    /// <remarks>@see https://developers.cloudflare.com/ai-search/</remarks>
    [<Import("AutoRAGChatLanguageModel", "workers-ai-provider"); EmitConstructor>]
    static member AutoRAGChatLanguageModel (modelId: TextGenerationModels, settings: AISearchChatSettings, config: AISearchChatLanguageModel.Config) : AutoRAGChatLanguageModel = jsNative
    /// <summary>
    /// Create a Workers AI provider instance.
    /// </summary>
    [<Import("createWorkersAI", "workers-ai-provider")>]
    static member createWorkersAI (options: WorkersAISettings) : WorkersAI = jsNative
    /// <summary>
    /// Create an AI Search provider instance.
    /// <br /><br />
    /// AI Search (formerly AutoRAG) is Cloudflare's managed search service.
    /// </summary>
    /// <remarks>@see https://developers.cloudflare.com/ai-search/</remarks>
    [<Import("createAISearch", "workers-ai-provider")>]
    static member createAISearch (options: AISearchSettings, ?providerName: string) : AISearchProvider = jsNative
    /// <remarks>@deprecated Use <c>createAISearch</c> instead. AutoRAG has been renamed to AI Search.</remarks>
    /// <remarks>@see https://developers.cloudflare.com/ai-search/</remarks>
    [<Import("createAutoRAG", "workers-ai-provider")>]
    static member createAutoRAG (options: AISearchSettings) : AISearchProvider = jsNative

module AISearchChatLanguageModel =
    [<Interface>]
    type Config =
        abstract provider: string with get, set
        abstract binding: obj with get, set
        abstract gateway: obj option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (provider: string, binding: obj, ?gateway: obj) : Config = jsNative

/// <summary>workers-ai-provider/anthropic</summary>
module Anthropic =
    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        /// <summary>
        /// Anthropic-wire provider plugin for the gateway delegate. Pass to
        /// <c>createGatewayDelegate({ providers: [anthropic] })</c> to handle
        /// <c>"anthropic/&lt;model&gt;"</c> slugs.
        /// <br /><br />
        /// Requires <c>@ai-sdk/anthropic</c> (an optional peer dependency — install it yourself).
        /// </summary>
        [<Import("anthropic", "workers-ai-provider/anthropic")>]
        static member anthropic: ProviderPlugin = jsNative

module CreateGatewayProvider =
    [<Interface>]
    type Config =
        inherit GatewayFetchConfig
        abstract apiKey: string option with get, set
        abstract baseURL: string option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (binding: obj, gateway: obj, ?provider: string, ?byok: bool, ?extraHeaders: Record<string, string>, ?cacheTtl: float, ?skipCache: bool, ?apiKey: string, ?baseURL: string) : Config = jsNative

    module Factory =
        [<Interface>]
        type Opts =
            abstract apiKey: string option with get, set
            abstract baseURL: string option with get, set
            abstract fetch: Func<obj, obj option, JS.Promise<obj>> with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (fetch: Func<obj, obj option, JS.Promise<obj>>, ?apiKey: string, ?baseURL: string) : Opts = jsNative

module FallbackOptions =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Mode =
        | [<CompiledName("client")>] Client
        | [<CompiledName("server")>] Server

/// <summary>workers-ai-provider/gateway</summary>
module Gateway =
    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        /// <summary>
        /// A <c>fetch</c> that dispatches the wrapped provider's request through AI Gateway.
        /// Detects the gateway provider id from the request URL (or uses <c>config.provider</c>),
        /// strips the provider host to the endpoint path, and forwards the body verbatim.
        /// </summary>
        [<Import("createGatewayFetch", "workers-ai-provider/gateway")>]
        static member createGatewayFetch (config: GatewayFetchConfig) : Func<obj, obj option, JS.Promise<obj>> = jsNative
        /// <summary>
        /// Wrap an <c>@ai-sdk/*</c> provider factory so its traffic flows through AI Gateway.
        /// A thin convenience over createGatewayFetch — it injects the gateway
        /// <c>fetch</c> (and a placeholder <c>apiKey</c> unless you supply one for BYOK).
        /// </summary>
        /// <example>
        /// <code>
        /// ```ts
        /// import { createOpenAI } from "@ai-sdk/openai";
        /// import { createGatewayProvider } from "workers-ai-provider/gateway";
        ///
        /// const openai = createGatewayProvider(createOpenAI, {
        ///   binding: env.AI,
        ///   gateway: "my-gw",
        /// });
        /// const model = openai("gpt-5");
        /// </code>
        /// <code>
        /// </code>
        /// </example>
        [<Import("createGatewayProvider", "workers-ai-provider/gateway")>]
        static member createGatewayProvider<'T> (factory: (CreateGatewayProvider.Factory.Opts -> 'T), config: CreateGatewayProvider.Config) : 'T = jsNative

module GatewayErrorContext =
    [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
    type Transport =
        | [<CompiledName("gateway")>] Gateway
        | [<CompiledName("run")>] Run

/// <summary>workers-ai-provider/google</summary>
module Google =
    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        /// <summary>
        /// Google (Gemini) provider plugin for the gateway delegate. Pass to
        /// <c>createGatewayDelegate({ providers: [google] })</c> to handle <c>"google/&lt;model&gt;"</c>
        /// (Google AI Studio) and <c>"google-vertex/&lt;model&gt;"</c> slugs.
        /// <br /><br />
        /// Requires <c>@ai-sdk/google</c> (an optional peer dependency — install it yourself).
        /// </summary>
        [<Import("google", "workers-ai-provider/google")>]
        static member google: ProviderPlugin = jsNative

/// <summary>workers-ai-provider/openai</summary>
module Openai =
    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        /// <summary>
        /// OpenAI-wire provider plugin for the gateway delegate. Pass to
        /// <c>createGatewayDelegate({ providers: [openai] })</c> to handle every
        /// OpenAI-compatible provider in one go — <c>openai/…</c>, plus the OpenAI-compatible
        /// long tail (<c>deepseek/…</c>, <c>xai/…</c>, <c>groq/…</c>, <c>mistral/…</c>, <c>perplexity/…</c>,
        /// <c>openrouter/…</c>, <c>cohere/…</c>, …). The registry routes each slug to its gateway
        /// provider id; this plugin only supplies the response parser.
        /// <br /><br />
        /// Requires <c>@ai-sdk/openai</c> (an optional peer dependency — install it yourself).
        /// <br /><br />
        /// Uses <c>.chat()</c> (Chat Completions) deliberately: the bare <c>openai()</c> call
        /// (AI SDK v6+) defaults to the Responses API, which the AI Gateway run catalog
        /// does not serve.
        /// </summary>
        [<Import("openai", "workers-ai-provider/openai")>]
        static member openai: ProviderPlugin = jsNative

module ProviderPlugin =
    module Create =
        [<Interface>]
        type Args =
            abstract modelId: string with get, set
            abstract fetch: Func<obj, obj option, JS.Promise<obj>> with get, set
            abstract baseURL: string option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (modelId: string, fetch: Func<obj, obj option, JS.Promise<obj>>, ?baseURL: string) : Args = jsNative

        module Args =
            module Fetch =
                module Input =
                    type Item<'HostMetadata> =
                        /// <summary>
                        /// <a href="https://www.iana.org/assignments/as-numbers/as-numbers.xhtml">ASN</a> of the incoming request.
                        /// </summary>
                        /// <example><c>395747</c></example>
                        abstract asn: float option with get, set
                        /// <summary>
                        /// The organization which owns the ASN of the incoming request.
                        /// </summary>
                        /// <example><c>"Google Cloud"</c></example>
                        abstract asOrganization: string option with get, set
                        /// <summary>
                        /// The original value of the <c>Accept-Encoding</c> header if Cloudflare modified it.
                        /// </summary>
                        /// <example><c>"gzip, deflate, br"</c></example>
                        abstract clientAcceptEncoding: string option with get, set
                        /// <summary>
                        /// The number of milliseconds it took for the request to reach your worker.
                        /// </summary>
                        /// <example><c>22</c></example>
                        abstract clientTcpRtt: float option with get, set
                        /// <summary>
                        /// The three-letter <a href="https://en.wikipedia.org/wiki/IATA_airport_code">IATA</a>
                        /// airport code of the data center that the request hit.
                        /// </summary>
                        /// <example><c>"DFW"</c></example>
                        abstract colo: string with get, set
                        /// <summary>
                        /// Represents the upstream's response to a
                        /// <a href="https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html">TCP <c>keepalive</c> message</a>
                        /// from cloudflare.
                        /// <br /><br />
                        /// For workers with no upstream, this will always be <c>1</c>.
                        /// </summary>
                        /// <example><c>3</c></example>
                        abstract edgeRequestKeepAliveStatus: IncomingRequestCfPropertiesEdgeRequestKeepAliveStatus with get, set
                        /// <summary>
                        /// The HTTP Protocol the request used.
                        /// </summary>
                        /// <example><c>"HTTP/2"</c></example>
                        abstract httpProtocol: string with get, set
                        /// <summary>
                        /// The browser-requested prioritization information in the request object.
                        /// <br /><br />
                        /// If no information was set, defaults to the empty string <c>""</c>
                        /// </summary>
                        /// <example><c>"weight=192;exclusive=0;group=3;group-weight=127"</c></example>
                        /// <defaultValue>""</defaultValue>
                        abstract requestPriority: string with get, set
                        /// <summary>
                        /// The TLS version of the connection to Cloudflare.
                        /// In requests served over plaintext (without TLS), this property is the empty string <c>""</c>.
                        /// </summary>
                        /// <example><c>"TLSv1.3"</c></example>
                        abstract tlsVersion: string with get, set
                        /// <summary>
                        /// The cipher for the connection to Cloudflare.
                        /// In requests served over plaintext (without TLS), this property is the empty string <c>""</c>.
                        /// </summary>
                        /// <example><c>"AEAD-AES128-GCM-SHA256"</c></example>
                        abstract tlsCipher: string with get, set
                        /// <summary>
                        /// Metadata containing the <a href="https://www.rfc-editor.org/rfc/rfc5246#section-7.4.1.2"><c>HELLO</c></a> and <a href="https://www.rfc-editor.org/rfc/rfc5246#section-7.4.9"><c>FINISHED</c></a> messages from this request's TLS handshake.
                        /// <br /><br />
                        /// If the incoming request was served over plaintext (without TLS) this field is undefined.
                        /// </summary>
                        abstract tlsExportedAuthenticator: obj option with get, set
                        /// <summary>
                        /// Results of Cloudflare's Bot Management analysis
                        /// </summary>
                        abstract botManagement: ProviderPlugin.Create.Args.Fetch.Input.Item.BotManagement with get, set
                        /// <summary>
                        /// Duplicate of <c>botManagement.score</c>.
                        /// </summary>
                        /// <remarks>@deprecated</remarks>
                        abstract clientTrustScore: float with get, set
                        /// <summary>
                        /// Custom metadata set per-host in <a href="https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/">Cloudflare for SaaS</a>.
                        /// <br /><br />
                        /// This field is only present if you have Cloudflare for SaaS enabled on your account
                        /// and you have followed the <a href="(https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/domain-support/custom-metadata/">required steps to enable it</a>).
                        /// </summary>
                        abstract hostMetadata: 'HostMetadata option with get, set
                        /// <summary>
                        /// The <a href="https://www.iso.org/iso-3166-country-codes.html">ISO 3166-1 Alpha 2</a> country code the request originated from.
                        /// <br /><br />
                        /// If your worker is <a href="https://support.cloudflare.com/hc/en-us/articles/203306930-Understanding-Cloudflare-Tor-support-and-Onion-Routing">configured to accept TOR connections</a>, this may also be <c>"T1"</c>, indicating a request that originated over TOR.
                        /// <br /><br />
                        /// If Cloudflare is unable to determine where the request originated this property is omitted.
                        /// <br /><br />
                        /// The country code <c>"T1"</c> is used for requests originating on TOR.
                        /// </summary>
                        /// <example><c>"GB"</c></example>
                        abstract country: ProviderPlugin.Create.Args.Fetch.Input.Item.Country option with get, set
                        /// <summary>
                        /// If present, this property indicates that the request originated in the EU
                        /// </summary>
                        /// <example><c>"1"</c></example>
                        abstract isEUCountry: string option with get, set
                        /// <summary>
                        /// A two-letter code indicating the continent the request originated from.
                        /// </summary>
                        /// <example><c>"AN"</c></example>
                        abstract continent: ContinentCode option with get, set
                        /// <summary>
                        /// The city the request originated from
                        /// </summary>
                        /// <example><c>"Austin"</c></example>
                        abstract city: string option with get, set
                        /// <summary>
                        /// Postal code of the incoming request
                        /// </summary>
                        /// <example><c>"78701"</c></example>
                        abstract postalCode: string option with get, set
                        /// <summary>
                        /// Latitude of the incoming request
                        /// </summary>
                        /// <example><c>"30.27130"</c></example>
                        abstract latitude: string option with get, set
                        /// <summary>
                        /// Longitude of the incoming request
                        /// </summary>
                        /// <example><c>"-97.74260"</c></example>
                        abstract longitude: string option with get, set
                        /// <summary>
                        /// Timezone of the incoming request
                        /// </summary>
                        /// <example><c>"America/Chicago"</c></example>
                        abstract timezone: string option with get, set
                        /// <summary>
                        /// If known, the ISO 3166-2 name for the first level region associated with
                        /// the IP address of the incoming request
                        /// </summary>
                        /// <example><c>"Texas"</c></example>
                        abstract region: string option with get, set
                        /// <summary>
                        /// If known, the ISO 3166-2 code for the first-level region associated with
                        /// the IP address of the incoming request
                        /// </summary>
                        /// <example><c>"TX"</c></example>
                        abstract regionCode: string option with get, set
                        /// <summary>
                        /// Metro code (DMA) of the incoming request
                        /// </summary>
                        /// <example><c>"635"</c></example>
                        abstract metroCode: string option with get, set
                        /// <summary>
                        /// Information about the client certificate presented to Cloudflare.
                        /// <br /><br />
                        /// This is populated when the incoming request is served over TLS using
                        /// either Cloudflare Access or API Shield (mTLS)
                        /// and the presented SSL certificate has a valid
                        /// <a href="https://ldapwiki.com/wiki/Certificate%20Serial%20Number">Certificate Serial Number</a>
                        /// (i.e., not <c>null</c> or <c>""</c>).
                        /// <br /><br />
                        /// Otherwise, a set of placeholder values are used.
                        /// <br /><br />
                        /// The property <c>certPresented</c> will be set to <c>"1"</c> when
                        /// the object is populated (i.e. the above conditions were met).
                        /// </summary>
                        abstract tlsClientAuth: obj with get, set
                        [<EmitIndexer>]
                        abstract Item: string -> obj with get, set

                    module Item =
                        [<Interface>]
                        type BotManagement =
                            /// <summary>
                            /// Cloudflare’s <a href="https://developers.cloudflare.com/bots/concepts/bot-score/">level of certainty</a> that a request comes from a bot,
                            /// represented as an integer percentage between <c>1</c> (almost certainly a bot) and <c>99</c> (almost certainly human).
                            /// </summary>
                            /// <example><c>54</c></example>
                            abstract score: float with get, set
                            /// <summary>
                            /// A boolean value that is true if the request comes from a good bot, like Google or Bing.
                            /// Most customers choose to allow this traffic. For more details, see <a href="https://developers.cloudflare.com/firewall/known-issues-and-faq/#how-does-firewall-rules-handle-traffic-from-known-bots">Traffic from known bots</a>.
                            /// </summary>
                            abstract verifiedBot: bool with get, set
                            /// <summary>
                            /// A boolean value that is true if the request originates from a
                            /// Cloudflare-verified proxy service.
                            /// </summary>
                            abstract corporateProxy: bool with get, set
                            /// <summary>
                            /// A boolean value that's true if the request matches <a href="https://developers.cloudflare.com/bots/reference/static-resources/">file extensions</a> for many types of static resources.
                            /// </summary>
                            abstract staticResource: bool with get, set
                            /// <summary>
                            /// List of IDs that correlate to the Bot Management heuristic detections made on a request (you can have multiple heuristic detections on the same request).
                            /// </summary>
                            abstract detectionIds: float[] with get, set
                            /// <summary>
                            /// A <a href="https://developers.cloudflare.com/bots/concepts/ja3-fingerprint/">JA3 Fingerprint</a> to help profile specific SSL/TLS clients
                            /// across different destination IPs, Ports, and X509 certificates.
                            /// </summary>
                            abstract ja3Hash: string with get, set
                            [<ParamObject; Emit("$0")>]
                            static member Create (score: float, verifiedBot: bool, corporateProxy: bool, staticResource: bool, detectionIds: float[], ja3Hash: string) : BotManagement = jsNative

                        [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
                        type Country =
                            | AD
                            | AE
                            | AF
                            | AG
                            | AI
                            | AL
                            | AM
                            | AO
                            | AQ
                            | AR
                            | AS
                            | AT
                            | AU
                            | AW
                            | AX
                            | AZ
                            | BA
                            | BB
                            | BD
                            | BE
                            | BF
                            | BG
                            | BH
                            | BI
                            | BJ
                            | BL
                            | BM
                            | BN
                            | BO
                            | BQ
                            | BR
                            | BS
                            | BT
                            | BV
                            | BW
                            | BY
                            | BZ
                            | CA
                            | CC
                            | CD
                            | CF
                            | CG
                            | CH
                            | CI
                            | CK
                            | CL
                            | CM
                            | CN
                            | CO
                            | CR
                            | CU
                            | CV
                            | CW
                            | CX
                            | CY
                            | CZ
                            | DE
                            | DJ
                            | DK
                            | DM
                            | DO
                            | DZ
                            | EC
                            | EE
                            | EG
                            | EH
                            | ER
                            | ES
                            | ET
                            | FI
                            | FJ
                            | FK
                            | FM
                            | FO
                            | FR
                            | GA
                            | GB
                            | GD
                            | GE
                            | GF
                            | GG
                            | GH
                            | GI
                            | GL
                            | GM
                            | GN
                            | GP
                            | GQ
                            | GR
                            | GS
                            | GT
                            | GU
                            | GW
                            | GY
                            | HK
                            | HM
                            | HN
                            | HR
                            | HT
                            | HU
                            | ID
                            | IE
                            | IL
                            | IM
                            | IN
                            | IO
                            | IQ
                            | IR
                            | IS
                            | IT
                            | JE
                            | JM
                            | JO
                            | JP
                            | KE
                            | KG
                            | KH
                            | KI
                            | KM
                            | KN
                            | KP
                            | KR
                            | KW
                            | KY
                            | KZ
                            | LA
                            | LB
                            | LC
                            | LI
                            | LK
                            | LR
                            | LS
                            | LT
                            | LU
                            | LV
                            | LY
                            | MA
                            | MC
                            | MD
                            | ME
                            | MF
                            | MG
                            | MH
                            | MK
                            | ML
                            | MM
                            | MN
                            | MO
                            | MP
                            | MQ
                            | MR
                            | MS
                            | MT
                            | MU
                            | MV
                            | MW
                            | MX
                            | MY
                            | MZ
                            | NA
                            | NC
                            | NE
                            | NF
                            | NG
                            | NI
                            | NL
                            | NO
                            | NP
                            | NR
                            | NU
                            | NZ
                            | OM
                            | PA
                            | PE
                            | PF
                            | PG
                            | PH
                            | PK
                            | PL
                            | PM
                            | PN
                            | PR
                            | PS
                            | PT
                            | PW
                            | PY
                            | QA
                            | RE
                            | RO
                            | RS
                            | RU
                            | RW
                            | SA
                            | SB
                            | SC
                            | SD
                            | SE
                            | SG
                            | SH
                            | SI
                            | SJ
                            | SK
                            | SL
                            | SM
                            | SN
                            | SO
                            | SR
                            | SS
                            | ST
                            | SV
                            | SX
                            | SY
                            | SZ
                            | T1
                            | TC
                            | TD
                            | TF
                            | TG
                            | TH
                            | TJ
                            | TK
                            | TL
                            | TM
                            | TN
                            | TO
                            | TR
                            | TT
                            | TV
                            | TW
                            | TZ
                            | UA
                            | UG
                            | UM
                            | US
                            | UY
                            | UZ
                            | VA
                            | VC
                            | VE
                            | VG
                            | VI
                            | VN
                            | VU
                            | WF
                            | WS
                            | YE
                            | YT
                            | ZA
                            | ZM
                            | ZW

module ResumableStreamOptions =
    type OnReconnect = delegate of fromEvent: float * attempt: float -> unit

module WorkersAI =
    module Embedding =
        type Settings =
            abstract gateway: obj option with get, set
            abstract maxEmbeddingsPerCall: float option with get, set
            abstract supportsParallelCalls: bool option with get, set
            [<EmitIndexer>]
            abstract Item: string -> obj with get, set

    module Image =
        [<Interface>]
        type Settings =
            abstract maxImagesPerCall: float option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?maxImagesPerCall: float) : Settings = jsNative

module WorkersAIChatLanguageModel =
    type Settings =
        /// <summary>
        /// Whether to inject a safety prompt before all conversations.
        /// Defaults to <c>false</c>.
        /// </summary>
        abstract safePrompt: bool option with get, set
        /// <summary>
        /// Optionally set Cloudflare AI Gateway options.
        /// </summary>
        abstract gateway: obj option with get, set
        /// <summary>
        /// Session affinity key for prefix-cache optimization.
        /// Routes requests with the same key to the same backend replica.
        /// </summary>
        abstract sessionAffinity: string option with get, set
        /// <summary>
        /// Controls the reasoning budget for reasoning-capable Workers AI models
        /// (e.g. <c>@cf/zai-org/glm-4.7-flash</c>, <c>@cf/moonshotai/kimi-k2.7-code</c>,
        /// <c>@cf/openai/gpt-oss-120b</c>).
        /// <br /><br />
        /// <c>null</c> is a valid value and disables reasoning for models that support it.
        /// Forwarded on the <c>inputs</c> object of <c>binding.run(model, inputs)</c>.
        /// </summary>
        abstract reasoning_effort: WorkersAIChatLanguageModel.Settings.ReasoningEffort option with get, set
        /// <summary>
        /// Chat-template overrides for reasoning-capable models that expose
        /// thinking toggles (e.g. GLM, Kimi).
        /// <br /><br />
        /// Forwarded on the <c>inputs</c> object of <c>binding.run(model, inputs)</c>.
        /// </summary>
        abstract chat_template_kwargs: WorkersAIChatLanguageModel.Settings.ChatTemplateKwargs option with get, set
        [<EmitIndexer>]
        abstract Item: string -> obj with get, set

    module Settings =
        [<Interface>]
        type ChatTemplateKwargs =
            /// <summary>
            /// Whether to enable reasoning. Enabled by default on reasoning models.
            /// </summary>
            abstract enable_thinking: bool option with get, set
            abstract clear_thinking: bool option with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (?enable_thinking: bool, ?clear_thinking: bool) : ChatTemplateKwargs = jsNative

        [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
        type ReasoningEffort =
            | [<CompiledName("high")>] High
            | [<CompiledName("low")>] Low
            | [<CompiledName("medium")>] Medium

module WorkersAIGatewayError =
    [<Interface>]
    type Opts =
        abstract recoverable: bool option with get, set
        abstract status: float option with get, set
        abstract context: GatewayErrorContext option with get, set
        abstract raw: obj option with get, set
        abstract cause: obj option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (?recoverable: bool, ?status: float, ?context: GatewayErrorContext, ?raw: obj, ?cause: obj) : Opts = jsNative

module WorkersAIImageModel =
    [<Interface>]
    type Config =
        abstract provider: string with get, set
        abstract binding: obj with get, set
        abstract gateway: obj option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (provider: string, binding: obj, ?gateway: obj) : Config = jsNative

module WorkersAIRerankingModel =
    [<Interface>]
    type Config =
        abstract provider: string with get, set
        abstract binding: obj with get, set
        abstract gateway: obj option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (provider: string, binding: obj, ?gateway: obj) : Config = jsNative

module WorkersAISpeechModel =
    [<Interface>]
    type Config =
        abstract provider: string with get, set
        abstract binding: obj with get, set
        abstract gateway: obj option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (provider: string, binding: obj, ?gateway: obj) : Config = jsNative

module WorkersAITranscriptionModel =
    [<Interface>]
    type Config =
        abstract provider: string with get, set
        abstract binding: obj with get, set
        abstract gateway: obj option with get, set
        /// <summary>
        /// Whether the binding is a real <c>env.AI</c> binding (true) or a REST shim (false).
        /// Nova-3 uses different upload paths depending on this.
        /// </summary>
        abstract isBinding: bool with get, set
        /// <summary>
        /// REST credentials, only set when <c>isBinding</c> is false.
        /// Needed for Nova-3 which requires binary upload, bypassing the JSON-based REST shim.
        /// </summary>
        abstract credentials: CreateRunConfig option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (provider: string, binding: obj, isBinding: bool, ?gateway: obj, ?credentials: CreateRunConfig) : Config = jsNative

type GatewayDelegateErrorConstructor =
    /// <summary>
    /// Indicates whether the argument provided is a built-in Error instance or not.
    /// </summary>
    abstract isError: error: obj -> bool
    [<EmitConstructor>]
    abstract Create: kind: GatewayDelegateErrorKind * message: string * ?cause: obj -> GatewayDelegateError

/// <summary>
/// A single dispatch failure through AI Gateway (run or gateway path).
/// </summary>
type WorkersAIGatewayErrorConstructor =
    /// <summary>
    /// Classify an arbitrary thrown value. Understands AI SDK <c>APICallError</c>
    /// (reads <c>statusCode</c> / <c>responseBody</c> / <c>isRetryable</c>); falls back to a
    /// recoverable <c>gateway-error</c> for transport/connection failures so a fallback
    /// chain keeps trying.
    /// </summary>
    abstract fromUnknown: e: obj -> WorkersAIGatewayError
    /// <summary>
    /// Build from an HTTP <c>Response</c> (reads the body for the envelope).
    /// </summary>
    abstract fromResponse: resp: obj * ?context: GatewayErrorContext -> JS.Promise<WorkersAIGatewayError>
    /// <summary>
    /// Indicates whether the argument provided is a built-in Error instance or not.
    /// </summary>
    abstract isError: error: obj -> bool
    /// <summary>
    /// A single dispatch failure through AI Gateway (run or gateway path).
    /// </summary>
    [<EmitConstructor>]
    abstract Create: code: GatewayErrorCode * message: string * ?opts: WorkersAIGatewayError.Opts -> WorkersAIGatewayError

/// <summary>
/// Every model in a client-side fallback chain failed.
/// </summary>
type WorkersAIFallbackErrorConstructor =
    /// <summary>
    /// Indicates whether the argument provided is a built-in Error instance or not.
    /// </summary>
    abstract isError: error: obj -> bool
    /// <summary>
    /// Every model in a client-side fallback chain failed.
    /// </summary>
    [<EmitConstructor>]
    abstract Create: attempts: FallbackAttempt[] * ?message: string -> WorkersAIFallbackError
