<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Examples.props" />
  <ItemGroup>
    <ProjectReference Include="$(CloudEdgeSrc)Runtime/Platform/FSharp.CloudEdge.Runtime.Workers/FSharp.CloudEdge.Runtime.Workers.fsproj" />
    <ProjectReference Include="$(CloudEdgeSrc)Runtime/RPC/FSharp.CloudEdge.Runtime.Capnweb/FSharp.CloudEdge.Runtime.Capnweb.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="PricingApi.fs" />
    <Compile Include="PricingEndpoint.fs" />
    <Compile Include="GuardedEndpoint.fs" />
  </ItemGroup>
</Project>
