// <auto-generated>
//   Generated by Xantham.Generator from @cloudflare/actors.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec FSharp.CloudEdge.Runtime.Actors

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS
open Fable.Core.TS.Dom

/// <summary>
/// Alias type for DurableObjectState to match the adopted Actor nomenclature.
/// This type represents the state of a Durable Object in Cloudflare Workers.
/// </summary>
type ActorState = obj

/// <summary>
/// Type definition for a constructor of an actor.
/// </summary>
/// <remarks>@template T - The type of the actor</remarks>
type ActorConstructor<'T when 'T :> Actor<obj>> =
    [<EmitConstructor>]
    abstract Create: state: ActorState * env: obj -> 'T

/// <summary>
/// Configuration options for an actor.
/// </summary>
[<Interface>]
type ActorConfiguration =
    abstract locationHint: DurableObjectLocationHint option with get, set
    abstract sockets: ActorConfiguration.Sockets option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?locationHint: DurableObjectLocationHint, ?sockets: ActorConfiguration.Sockets) : ActorConfiguration = jsNative

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type DurableObjectLocationHint =
    | [<CompiledName("afr")>] Afr
    | [<CompiledName("apac")>] Apac
    | [<CompiledName("apac-ne")>] ApacNe
    | [<CompiledName("apac-se")>] ApacSe
    | [<CompiledName("eeur")>] Eeur
    | [<CompiledName("enam")>] Enam
    | [<CompiledName("me")>] Me
    | [<CompiledName("oc")>] Oc
    | [<CompiledName("sam")>] Sam
    | [<CompiledName("weur")>] Weur
    | [<CompiledName("wnam")>] Wnam

[<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
type ContinentCode =
    | AF
    | AN
    | AS
    | EU
    | NA
    | OC
    | SA

/// <summary>
/// Base abstract class for Workers that provides common functionality and structure.
/// </summary>
/// <remarks>@template T - The type of the environment object that will be available to the worker</remarks>
[<Interface>]
type Entrypoint<'T> =
    abstract env: 'T with get, set
    abstract ctx: obj with get, set
    abstract fetch: request: obj -> JS.Promise<obj>
    abstract __WORKER_ENTRYPOINT_BRAND: unit
    abstract email: (obj -> JS.Promise<unit> option) option with get, set
    abstract connect: (obj -> JS.Promise<unit> option) option with get, set
    abstract queue: (obj -> JS.Promise<unit> option) option with get, set
    abstract scheduled: (obj -> JS.Promise<unit> option) option with get, set
    abstract tail: (obj[] -> JS.Promise<unit> option) option with get, set
    abstract tailStream: (obj -> obj) option with get, set
    abstract test: (obj -> JS.Promise<unit> option) option with get, set
    abstract trace: (obj[] -> JS.Promise<unit> option) option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (env: 'T, ctx: obj, fetch: (obj -> JS.Promise<obj>), ?email: (obj -> JS.Promise<unit> option), ?connect: (obj -> JS.Promise<unit> option), ?queue: (obj -> JS.Promise<unit> option), ?scheduled: (obj -> JS.Promise<unit> option), ?tail: (obj[] -> JS.Promise<unit> option), ?tailStream: (obj -> obj), ?test: (obj -> JS.Promise<unit> option), ?trace: (obj[] -> JS.Promise<unit> option)) : Entrypoint<'T> = jsNative

type IncomingRequestCfPropertiesEdgeRequestKeepAliveStatus =
    | N0 = 0
    | N1 = 1
    | N2 = 2
    | N3 = 3
    | N4 = 4
    | N5 = 5

/// <summary>
/// Extended Actor class that provides additional functionality for Durable Objects.
/// This class adds SQL storage capabilities and browsing functionality to the base DurableObject.
/// </summary>
/// <remarks>@template E - The type of the environment object that will be available to the actor</remarks>
[<Interface>]
[<Import("Actor", "@cloudflare/actors")>]
type Actor<'E> =
    /// <remarks>@deprecated Use <c>name</c> instead as that maps to the value from <c>nameFromRequest</c></remarks>
    abstract identifier: string option with get, set
    abstract _name: obj option with get, set
    abstract _onInitCalled: obj with get, set
    abstract _setNameCalled: obj with get, set
    abstract name: string option
    abstract storage: Storage.Storage with get, set
    abstract alarms: Alarms.Alarms<Actor<'E>> with get, set
    abstract sockets: Sockets<Actor<'E>> with get, set
    abstract __studio: ``_``: obj -> JS.Promise<obj>
    /// <summary>
    /// Set the identifier for the actor as named by the client
    /// </summary>
    /// <param name="id">The identifier to set</param>
    abstract setName: id: string -> JS.Promise<unit>
    /// <summary>
    /// Initializes the persisted properties table and loads any stored values.
    /// This is called during construction to ensure properties are loaded before any code uses them.
    /// </summary>
    /// <remarks>@private</remarks>
    abstract _initializePersistedProperties: obj with get, set
    /// <summary>
    /// Waits for setName to be called before proceeding with request handling.
    /// This ensures that onRequest has access to the correct identifier.
    /// </summary>
    /// <remarks>@private</remarks>
    abstract _waitForSetName: obj with get, set
    /// <summary>
    /// Persists a property value to the Durable Object storage.
    /// </summary>
    /// <param name="propertyKey">The name of the property to persist</param>
    /// <param name="value">The value to persist</param>
    /// <remarks>@private</remarks>
    abstract _persistProperty: obj with get, set
    /// <summary>
    /// Abstract method that must be implemented by derived classes to handle incoming requests.
    /// </summary>
    /// <param name="request">- The incoming request to handle</param>
    /// <returns>A Promise that resolves to a Response</returns>
    abstract fetch: request: obj -> JS.Promise<obj>
    /// <summary>
    /// Lifecycle method that is called when the actor is initialized.
    /// </summary>
    /// <remarks>@protected</remarks>
    abstract onInit: unit -> JS.Promise<unit>
    /// <summary>
    /// Lifecycle method that is called when the actor is notified of an alarm.
    /// </summary>
    /// <remarks>@protected</remarks>
    /// <param name="alarmInfo">- Information about the alarm that was triggered</param>
    abstract onAlarm: ?alarmInfo: obj -> JS.Promise<unit>
    /// <summary>
    /// Hook that is called whenever a
    /// </summary>
    /// <remarks>
    /// @Persist
    /// decorated property is stored in the database.
    /// Override this method to listen to persistence events.
    /// </remarks>
    /// <param name="key">The property key that was persisted</param>
    /// <param name="value">The value that was persisted</param>
    abstract onPersist: key: string * value: obj -> unit
    abstract onRequest: request: obj -> JS.Promise<obj>
    abstract shouldUpgradeSocket: request: obj -> bool
    abstract onWebSocketUpgrade: request: obj -> obj
    abstract onWebSocketConnect: ws: obj * request: obj -> unit
    abstract onWebSocketDisconnect: ws: obj -> unit
    abstract onWebSocketMessage: ws: obj * message: obj -> unit
    abstract webSocketMessage: ws: obj * message: obj -> JS.Promise<unit>
    abstract webSocketClose: ws: obj * code: float -> JS.Promise<unit>
    abstract alarm: ?alarmInfo: obj -> JS.Promise<unit>
    /// <summary>
    /// Execute SQL queries against the Agent's database
    /// </summary>
    /// <remarks>@template T Type of the returned rows</remarks>
    /// <param name="strings">SQL query template strings</param>
    /// <param name="values">Values to be inserted into the query</param>
    /// <returns>Array of query results</returns>
    abstract sql<'T>: strings: obj * [<ParamArray>] values: U3<string, float, bool> option[] -> 'T[]
    /// <summary>
    /// Tracks the last access time of an actor instance.
    /// </summary>
    /// <param name="idString">The identifier of the actor instance to track.</param>
    abstract track: idString: string -> JS.Promise<unit>
    /// <summary>
    /// Destroy the Actor by removing all actor library specific tables and state
    /// that is associated with the actor.
    /// </summary>
    /// <param name="_">- Optional configuration object</param>
    /// <param name="_.trackingInstance">- Optional tracking instance name</param>
    /// <param name="_.forceEviction">- When true, forces eviction of the actor from the cache</param>
    /// <remarks>@throws Will throw an exception when forceEviction is true</remarks>
    abstract destroy: ?``_``: Actor.Destroy -> JS.Promise<unit>
    abstract __DURABLE_OBJECT_BRAND: unit
    abstract ctx: obj with get, set
    abstract env: 'E with get, set
    abstract connect: (obj -> JS.Promise<unit> option) option with get, set
    abstract webSocketError: Func<obj, obj, JS.Promise<unit> option> option with get, set
    /// <summary>
    /// Static method to extract an ID from a request URL. Default response "default".
    /// </summary>
    /// <param name="request">- The incoming request</param>
    /// <returns>The name string value defined by the client application to reference an instance</returns>
    [<Import("Actor.nameFromRequest", "@cloudflare/actors")>]
    static member nameFromRequest (request: obj) : JS.Promise<string option> = jsNative
    /// <summary>
    /// Static method to configure the actor.
    /// </summary>
    static member configuration
        with get (): (obj -> ActorConfiguration) = jsNative
        and set (_: (obj -> ActorConfiguration)): unit = jsNative
    /// <summary>
    /// Static method to get an actor instance by ID
    /// </summary>
    /// <param name="id">- The ID of the actor to get</param>
    /// <returns>The actor instance</returns>
    [<Import("Actor.get", "@cloudflare/actors")>]
    static member get (id: string) : obj = jsNative

type RecipientType = obj

[<Interface>]
type SQLSchemaMigration =
    /// <summary>
    /// Each migration is identified by this number. You should always use monotonically
    /// increasing numbers for any new migration added, and never change already applied
    /// migrations.
    /// If you modify the <c>sql</c> statement of an already applied migration the change will not be applied.
    /// </summary>
    abstract idMonotonicInc: float with get, set
    /// <summary>
    /// Just a description for you, the coder, to know what the migration is about.
    /// This is not used in any way by the migrations runner.
    /// </summary>
    abstract description: string with get, set
    /// <summary>
    /// The SQL statement to execute for a single schema migration.
    /// Can be multiple statements separated by semicolon (<c>;</c>).
    /// This statement is passed directly to the <c>storage.sql.exec()</c> function.
    /// See https://developers.cloudflare.com/durable-objects/api/storage-api/#sqlexec
    /// <br /><br />
    /// You should always try and make your SQL statements to be safe to run multiple times.
    /// Even though <c>SQLSchemaMigrations.runAll()</c> keeps track of the last migration ID and
    /// never runs anything less than that ID, it's best practice for your statements to be defensive.
    /// For example use <c>CREATE TABLE IF NOT EXISTS</c> instead of <c>CREATE TABLE</c>.
    /// <br /><br />
    /// Also, you should never change the <c>sql</c> code of an already ran migration. Add a new entry
    /// in the <c>SQLSchemaMigrationsConfig.migrations</c> list altering the schema as you wish.
    /// <br /><br />
    /// In majority of cases you should always provide this. In the cases where you need to dynamically
    /// fetch your statements at runtime, the <c>SQLSchemaMigrations.runAll</c> function accepts
    /// a function (<c>genSql</c>) that will be called when migrations are executed and based on the <c>idMonotonicInc</c>
    /// you can return the SQL statement to run at that point.
    /// If <c>sql</c> is provided, then that callback function is not called even if provided.
    /// </summary>
    abstract sql: string option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (idMonotonicInc: float, description: string, ?sql: string) : SQLSchemaMigration = jsNative

[<Interface>]
type SQLSchemaMigrations =
    abstract ``__#1@#private``: obj with get, set
    /// <summary>
    /// This is a quick check based on the in memory tracker of last migration ran,
    /// therefore this always returns <c>true</c> until <c>runAll</c> runs at least once.
    /// </summary>
    /// <returns><c>true</c> if the <c>migrations</c> list provided has not been ran in full yet.</returns>
    abstract hasMigrationsToRun: unit -> bool
    /// <summary>
    /// Runs all the migrations that haven't already ran. The <c>idMonotonicInc</c> of each migration is used
    /// to track which migrations ran or not. New migrations should always have higher <c>idMonotonicInc</c>
    /// than older ones!
    /// </summary>
    /// <param name="sqlGen">
    /// An optional callback function to generate the SQL statement of a given migration at runtime.
    /// If the migration entry already has a valid <c>sql</c> statement this callback is NOT called.
    /// </param>
    /// <returns>The numbers of rows read and written throughout the migration execution.</returns>
    abstract runAll: ?sqlGen: (float -> string) -> JS.Promise<SQLSchemaMigrations.RunAll.Result.Item>
    [<ParamObject; Emit("$0")>]
    static member Create (``__#1@#private``: obj, hasMigrationsToRun: (unit -> bool), runAll: ((float -> string) option -> JS.Promise<SQLSchemaMigrations.RunAll.Result.Item>)) : SQLSchemaMigrations = jsNative

[<Interface>]
type Sockets<'P> =
    abstract parent: obj with get, set
    abstract context: obj with get, set
    abstract connections: JS.Map<string, Sockets.Connections.Item> with get, set
    abstract message: message: string * ?``to``: U2<string, RecipientType[]> * ?exclude: RecipientType[] -> unit
    abstract webSocketMessage: ws: Sockets.Connections.Item * message: obj -> JS.Promise<unit>
    abstract webSocketClose: ws: Sockets.Connections.Item * code: float -> JS.Promise<unit>
    abstract acceptWebSocket: request: obj -> Sockets.AcceptWebSocket.Result
    [<ParamObject; Emit("$0")>]
    static member Create (parent: obj, context: obj, connections: JS.Map<string, Sockets.Connections.Item>, message: Action<string, U2<string, RecipientType[]> option, RecipientType[] option>, webSocketMessage: Func<Sockets.Connections.Item, obj, JS.Promise<unit>>, webSocketClose: Func<Sockets.Connections.Item, float, JS.Promise<unit>>, acceptWebSocket: (obj -> Sockets.AcceptWebSocket.Result)) : Sockets<'P> = jsNative

[<Interface>]
type SqlStorage =
    abstract exec: sql: string * [<ParamArray>] ``params``: obj[] -> obj
    [<ParamObject; Emit("$0")>]
    static member Create (exec: Func<string, obj[], obj>) : SqlStorage = jsNative

[<Interface>]
type StudioQueryRequest =
    abstract ``type``: string with get, set
    abstract statement: string with get, set
    abstract ``params``: obj[] option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, statement: string, ?``params``: obj[]) : StudioQueryRequest = jsNative

[<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
type StudioRequest =
    | [<CompiledName("query")>] Query of statement: string * ``params``: obj[] option
    | [<CompiledName("transaction")>] Transaction of statements: string[] * ``params``: obj[] option

[<Interface>]
type StudioTransactionRequest =
    abstract ``type``: string with get, set
    abstract statements: string[] with get, set
    abstract ``params``: obj[] option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (``type``: string, statements: string[], ?``params``: obj[]) : StudioTransactionRequest = jsNative

[<Interface>]
type TryNOptions =
    /// <param name="err">Error thrown by the function.</param>
    /// <param name="nextAttempt">Number of next attempt to make.</param>
    /// <returns>Returns true if the error and nextAttempt number is retryable.</returns>
    abstract isRetryable: TryNOptions.IsRetryable option with get, set
    /// <summary>
    /// Number of milliseconds to use as multiplier for the exponential backoff.
    /// </summary>
    abstract baseDelayMs: float option with get, set
    /// <summary>
    /// Maximum number of milliseconds to wait.
    /// </summary>
    abstract maxDelayMs: float option with get, set
    /// <summary>
    /// If true, logs the error and attempt number to the console.
    /// </summary>
    abstract verbose: bool option with get, set
    [<ParamObject; Emit("$0")>]
    static member Create (?isRetryable: TryNOptions.IsRetryable, ?baseDelayMs: float, ?maxDelayMs: float, ?verbose: bool) : TryNOptions = jsNative

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// Base abstract class for Workers that provides common functionality and structure.
    /// </summary>
    /// <remarks>@template T - The type of the environment object that will be available to the worker</remarks>
    [<Import("Entrypoint", "@cloudflare/actors"); EmitConstructor>]
    static member Entrypoint<'T> (ctx: obj, env: obj) : Entrypoint<'T> = jsNative
    /// <summary>
    /// Extended Actor class that provides additional functionality for Durable Objects.
    /// This class adds SQL storage capabilities and browsing functionality to the base DurableObject.
    /// </summary>
    /// <remarks>@template E - The type of the environment object that will be available to the actor</remarks>
    [<Import("Actor", "@cloudflare/actors"); EmitConstructor>]
    static member Actor<'E> (?ctx: ActorState, ?env: 'E) : Actor<'E> = jsNative
    /// <summary>
    /// Creates a handler for a Worker or Actor.
    /// This function can handle both class-based and function-based handlers.
    /// </summary>
    /// <remarks>@template E - The type of the environment object</remarks>
    /// <param name="input">- The handler input (class or function)</param>
    /// <param name="opts">- Optional options for integration features</param>
    /// <returns>An ExportedHandler that can be used as a Worker</returns>
    [<Import("handler", "@cloudflare/actors")>]
    static member handler<'E> (input: U3<Func<obj, 'E option, obj option, obj>, Handler.Input.ResultConstructor<'E>, Handler.InputConstructor<'E>>, ?opts: Handler.Opts) : Handler.Result<'E> = jsNative
    [<Import("getActor", "@cloudflare/actors")>]
    static member getActor<'T when 'T :> Actor<obj>> (ActorClass: FSharp.CloudEdge.Runtime.Actors.ActorConstructor<'T>, id: string) : obj = jsNative
    /// <summary>
    /// Decorator that marks a property to be persisted in Durable Object storage.
    /// When the property value changes, it will be automatically stored in the '_actor_persist' table.
    /// Supports deep tracking of nested object properties.
    /// </summary>
    [<Import("Persist", "@cloudflare/actors")>]
    static member Persist (target: unit, context: obj) : unit = jsNative
    [<Import("RetryConditionAlways", "@cloudflare/actors")>]
    static member RetryConditionAlways () : bool = jsNative
    [<Import("RetryConditionNever", "@cloudflare/actors")>]
    static member RetryConditionNever () : bool = jsNative
    /// <param name="fn">The function to call for each attempt. Receives the attempt number.</param>
    /// <param name="isRetryable">The function to call to determine if the error is retryable. Receives the error and the next attempt number.</param>
    /// <param name="options">The options for the retry strategy.</param>
    /// <param name="options.baseDelayMs">Number of milliseconds to use as multiplier for the exponential backoff.</param>
    /// <param name="options.maxDelayMs">Maximum number of milliseconds to wait.</param>
    /// <param name="options.verbose">If true, logs the error and attempt number to the console.</param>
    /// <returns>The result of the <c>fn</c> function or propagates the last error thrown once <c>isRetryable</c> returns false or all retries failed.</returns>
    [<Import("tryWhile", "@cloudflare/actors")>]
    static member tryWhile<'T> (fn: (float -> JS.Promise<'T>), isRetryable: TryWhile.IsRetryable, ?options: TryWhile.Options) : JS.Promise<'T> = jsNative
    /// <param name="n">Number of total attempts to make.</param>
    /// <param name="fn">The function to call for each attempt. Receives the attempt number.</param>
    /// <param name="options">The options for the retry strategy.</param>
    /// <param name="options.isRetryable">The function to call to determine if the error is retryable. Receives the error and the next attempt number.</param>
    /// <param name="options.baseDelayMs">Number of milliseconds to use as multiplier for the exponential backoff.</param>
    /// <param name="options.maxDelayMs">Maximum number of milliseconds to wait.</param>
    /// <param name="options.verbose">If true, logs the error and attempt number to the console.</param>
    /// <returns>The result of the <c>fn</c> function or propagates the last error thrown once <c>isRetryable</c> returns false or all retries failed.</returns>
    [<Import("tryN", "@cloudflare/actors")>]
    static member tryN<'T> (n: float, fn: (float -> JS.Promise<'T>), ?options: TryNOptions) : JS.Promise<'T> = jsNative
    /// <summary>
    /// Returns the number of milliseconds to wait before retrying a request.
    /// See the "Full Jitter" approach in https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/.
    /// </summary>
    /// <param name="attempt">The number of attempts so far.</param>
    /// <param name="baseDelayMs">Number of milliseconds to use as multiplier for the exponential backoff.</param>
    /// <param name="maxDelayMs">Maximum number of milliseconds to wait.</param>
    /// <returns>Milliseconds to wait before retrying.</returns>
    [<Import("jitterBackoff", "@cloudflare/actors")>]
    static member jitterBackoff (attempt: float, baseDelayMs: float, maxDelayMs: float) : float = jsNative
    /// <summary>
    /// Returns true if the given error is retryable according to the Durable Object error handling.
    /// See https://developers.cloudflare.com/durable-objects/best-practices/error-handling/.
    /// </summary>
    [<Import("isErrorRetryable", "@cloudflare/actors")>]
    static member isErrorRetryable (err: obj) : bool = jsNative

module Actor =
    [<Interface>]
    type Destroy =
        abstract forceEviction: bool option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (?forceEviction: bool) : Destroy = jsNative

module ActorConfiguration =
    [<Interface>]
    type Sockets =
        abstract upgradePath: string option with get, set
        abstract autoResponse: ActorConfiguration.Sockets.AutoResponse option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (?upgradePath: string, ?autoResponse: ActorConfiguration.Sockets.AutoResponse) : Sockets = jsNative

    module Sockets =
        [<Interface>]
        type AutoResponse =
            abstract ping: string with get, set
            abstract pong: string with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (ping: string, pong: string) : AutoResponse = jsNative

/// <summary>@cloudflare/actors/alarms</summary>
module Alarms =
    [<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
    type Schedule =
        | [<CompiledName("scheduled")>] Scheduled of id: string * callback: obj * payload: obj * identifier: string * time: float
        | [<CompiledName("delayed")>] Delayed of id: string * callback: obj * payload: obj * identifier: string * time: float * delayInSeconds: float
        | [<CompiledName("cron")>] Cron of id: string * callback: obj * payload: obj * identifier: string * time: float * cron: string

    [<Interface>]
    type Schedule2<'K, 'T> =
        /// <summary>
        /// Unique identifier for the schedule
        /// </summary>
        abstract id: string with get, set
        /// <summary>
        /// Name of the method to be called
        /// </summary>
        abstract callback: 'K with get, set
        /// <summary>
        /// Data to be passed to the callback
        /// </summary>
        abstract payload: 'T with get, set
        /// <summary>
        /// Actor identifier
        /// </summary>
        abstract identifier: string with get, set
        /// <summary>
        /// Type of schedule for one-time execution at a specific time
        /// </summary>
        abstract ``type``: string with get, set
        /// <summary>
        /// Timestamp when the task should execute
        /// </summary>
        abstract time: float with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (id: string, callback: 'K, payload: 'T, identifier: string, ``type``: string, time: float) : Schedule2<'K, 'T> = jsNative

    [<Interface>]
    type Schedule3<'K, 'T> =
        /// <summary>
        /// Unique identifier for the schedule
        /// </summary>
        abstract id: string with get, set
        /// <summary>
        /// Name of the method to be called
        /// </summary>
        abstract callback: 'K with get, set
        /// <summary>
        /// Data to be passed to the callback
        /// </summary>
        abstract payload: 'T with get, set
        /// <summary>
        /// Actor identifier
        /// </summary>
        abstract identifier: string with get, set
        /// <summary>
        /// Type of schedule for delayed execution
        /// </summary>
        abstract ``type``: string with get, set
        /// <summary>
        /// Timestamp when the task should execute
        /// </summary>
        abstract time: float with get, set
        /// <summary>
        /// Number of seconds to delay execution
        /// </summary>
        abstract delayInSeconds: float with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (id: string, callback: 'K, payload: 'T, identifier: string, ``type``: string, time: float, delayInSeconds: float) : Schedule3<'K, 'T> = jsNative

    [<Interface>]
    type Schedule4<'K, 'T> =
        /// <summary>
        /// Unique identifier for the schedule
        /// </summary>
        abstract id: string with get, set
        /// <summary>
        /// Name of the method to be called
        /// </summary>
        abstract callback: 'K with get, set
        /// <summary>
        /// Data to be passed to the callback
        /// </summary>
        abstract payload: 'T with get, set
        /// <summary>
        /// Actor identifier
        /// </summary>
        abstract identifier: string with get, set
        /// <summary>
        /// Type of schedule for recurring execution based on cron expression
        /// </summary>
        abstract ``type``: string with get, set
        /// <summary>
        /// Timestamp for the next execution
        /// </summary>
        abstract time: float with get, set
        /// <summary>
        /// Cron expression defining the schedule
        /// </summary>
        abstract cron: string with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (id: string, callback: 'K, payload: 'T, identifier: string, ``type``: string, time: float, cron: string) : Schedule4<'K, 'T> = jsNative

    [<Interface>]
    type Alarms<'P> =
        abstract parent: obj with get, set
        abstract storage: obj option with get, set
        abstract actorName: string option with get, set
        /// <summary>
        /// Schedule a task to be executed in the future
        /// </summary>
        /// <remarks>@template T Type of the payload data</remarks>
        /// <param name="when">When to execute the task (Date, seconds delay, or cron expression)</param>
        /// <param name="callback">Name of the method to call</param>
        /// <param name="payload">Data to pass to the callback</param>
        /// <returns>Schedule object representing the scheduled task</returns>
        abstract schedule<'T>: ``when``: U3<string, float, JS.Date> * callback: obj * ?payload: 'T -> JS.Promise<FSharp.CloudEdge.Runtime.Actors.Alarms.Alarms.GetSchedules.Result.Item>
        /// <summary>
        /// Get a scheduled task by ID
        /// </summary>
        /// <remarks>@template T Type of the payload data</remarks>
        /// <param name="id">ID of the scheduled task</param>
        /// <returns>The Schedule object or undefined if not found</returns>
        abstract getSchedule<'T>: id: string -> JS.Promise<U3<Alarms.Alarms.GetSchedule.Result.Item<'T>, Alarms.Alarms.GetSchedule.Result.Item2<'T>, Alarms.Alarms.GetSchedule.Result.Item3<'T>> option>
        /// <summary>
        /// Get scheduled tasks matching the given criteria
        /// </summary>
        /// <remarks>@template T Type of the payload data</remarks>
        /// <param name="criteria">Criteria to filter schedules</param>
        /// <returns>Array of matching Schedule objects</returns>
        abstract getSchedules: ?criteria: Alarms.Alarms.GetSchedules.Criteria -> Alarms.Alarms.GetSchedules.Result.Item[]
        /// <summary>
        /// Cancel a scheduled task
        /// </summary>
        /// <param name="id">ID of the task to cancel</param>
        /// <returns>true if the task was cancelled, false otherwise</returns>
        abstract cancelSchedule: id: string -> JS.Promise<bool>
        abstract _scheduleNextAlarm: obj with get, set
        abstract alarm: (obj option -> JS.Promise<unit>)
        /// <summary>
        /// Execute SQL queries against the Agent's database
        /// </summary>
        /// <remarks>@template T Type of the returned rows</remarks>
        /// <param name="strings">SQL query template strings</param>
        /// <param name="values">Values to be inserted into the query</param>
        /// <returns>Array of query results</returns>
        abstract sql<'T>: strings: obj * [<ParamArray>] values: U3<string, float, bool> option[] -> 'T[]
        abstract _tryCatch: obj with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (parent: obj, schedule: Func<U3<string, float, JS.Date>, obj, 'T option, JS.Promise<FSharp.CloudEdge.Runtime.Actors.Alarms.Alarms.GetSchedules.Result.Item>>, getSchedule: (string -> JS.Promise<U3<Alarms.Alarms.GetSchedule.Result.Item<'T>, Alarms.Alarms.GetSchedule.Result.Item2<'T>, Alarms.Alarms.GetSchedule.Result.Item3<'T>> option>), getSchedules: (Alarms.Alarms.GetSchedules.Criteria option -> Alarms.Alarms.GetSchedules.Result.Item[]), cancelSchedule: (string -> JS.Promise<bool>), _scheduleNextAlarm: obj, alarm: (obj option -> JS.Promise<unit>), sql: Func<obj, U3<string, float, bool> option[], 'T[]>, _tryCatch: obj, ?storage: obj, ?actorName: string) : Alarms<'P> = jsNative

    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        [<Import("Alarms", "@cloudflare/actors/alarms"); EmitConstructor>]
        static member Alarms<'P> (ctx: obj option, parent: 'P) : FSharp.CloudEdge.Runtime.Actors.Alarms.Alarms<'P> = jsNative

    module Alarms =
        module GetSchedule =
            module Result =
                [<Interface>]
                type Item<'T> =
                    /// <summary>
                    /// Unique identifier for the schedule
                    /// </summary>
                    abstract id: string with get, set
                    /// <summary>
                    /// Name of the method to be called
                    /// </summary>
                    abstract callback: string with get, set
                    /// <summary>
                    /// Data to be passed to the callback
                    /// </summary>
                    abstract payload: 'T with get, set
                    /// <summary>
                    /// Actor identifier
                    /// </summary>
                    abstract identifier: string with get, set
                    /// <summary>
                    /// Type of schedule for one-time execution at a specific time
                    /// </summary>
                    abstract ``type``: string with get, set
                    /// <summary>
                    /// Timestamp when the task should execute
                    /// </summary>
                    abstract time: float with get, set
                    [<ParamObject; Emit("$0")>]
                    static member Create (id: string, callback: string, payload: 'T, identifier: string, ``type``: string, time: float) : Item<'T> = jsNative

                [<Interface>]
                type Item2<'T> =
                    /// <summary>
                    /// Unique identifier for the schedule
                    /// </summary>
                    abstract id: string with get, set
                    /// <summary>
                    /// Name of the method to be called
                    /// </summary>
                    abstract callback: string with get, set
                    /// <summary>
                    /// Data to be passed to the callback
                    /// </summary>
                    abstract payload: 'T with get, set
                    /// <summary>
                    /// Actor identifier
                    /// </summary>
                    abstract identifier: string with get, set
                    /// <summary>
                    /// Type of schedule for delayed execution
                    /// </summary>
                    abstract ``type``: string with get, set
                    /// <summary>
                    /// Timestamp when the task should execute
                    /// </summary>
                    abstract time: float with get, set
                    /// <summary>
                    /// Number of seconds to delay execution
                    /// </summary>
                    abstract delayInSeconds: float with get, set
                    [<ParamObject; Emit("$0")>]
                    static member Create (id: string, callback: string, payload: 'T, identifier: string, ``type``: string, time: float, delayInSeconds: float) : Item2<'T> = jsNative

                [<Interface>]
                type Item3<'T> =
                    /// <summary>
                    /// Unique identifier for the schedule
                    /// </summary>
                    abstract id: string with get, set
                    /// <summary>
                    /// Name of the method to be called
                    /// </summary>
                    abstract callback: string with get, set
                    /// <summary>
                    /// Data to be passed to the callback
                    /// </summary>
                    abstract payload: 'T with get, set
                    /// <summary>
                    /// Actor identifier
                    /// </summary>
                    abstract identifier: string with get, set
                    /// <summary>
                    /// Type of schedule for recurring execution based on cron expression
                    /// </summary>
                    abstract ``type``: string with get, set
                    /// <summary>
                    /// Timestamp for the next execution
                    /// </summary>
                    abstract time: float with get, set
                    /// <summary>
                    /// Cron expression defining the schedule
                    /// </summary>
                    abstract cron: string with get, set
                    [<ParamObject; Emit("$0")>]
                    static member Create (id: string, callback: string, payload: 'T, identifier: string, ``type``: string, time: float, cron: string) : Item3<'T> = jsNative

        module GetSchedules =
            [<Interface>]
            type Criteria =
                abstract id: string option with get, set
                abstract ``type``: Alarms.Alarms.GetSchedules.Criteria.Type option with get, set
                abstract timeRange: Alarms.Alarms.GetSchedules.Criteria.TimeRange option with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (?id: string, ?``type``: Alarms.Alarms.GetSchedules.Criteria.Type, ?timeRange: Alarms.Alarms.GetSchedules.Criteria.TimeRange) : Criteria = jsNative

            module Criteria =
                [<Interface>]
                type TimeRange =
                    abstract start: JS.Date option with get, set
                    abstract ``end``: JS.Date option with get, set
                    [<ParamObject; Emit("$0")>]
                    static member Create (?start: JS.Date, ?``end``: JS.Date) : TimeRange = jsNative

                [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
                type Type =
                    | [<CompiledName("cron")>] Cron
                    | [<CompiledName("delayed")>] Delayed
                    | [<CompiledName("scheduled")>] Scheduled

            module Result =
                [<RequireQualifiedAccess; TypeScriptTaggedUnion("type", CaseRules.None)>]
                type Item =
                    | [<CompiledName("scheduled")>] Scheduled of id: string * callback: string * payload: obj * identifier: string * time: float
                    | [<CompiledName("delayed")>] Delayed of id: string * callback: string * payload: obj * identifier: string * time: float * delayInSeconds: float
                    | [<CompiledName("cron")>] Cron of id: string * callback: string * payload: obj * identifier: string * time: float * cron: string

                [<Interface>]
                type Item2<'T> =
                    /// <summary>
                    /// Unique identifier for the schedule
                    /// </summary>
                    abstract id: string with get, set
                    /// <summary>
                    /// Name of the method to be called
                    /// </summary>
                    abstract callback: string with get, set
                    /// <summary>
                    /// Data to be passed to the callback
                    /// </summary>
                    abstract payload: 'T with get, set
                    /// <summary>
                    /// Actor identifier
                    /// </summary>
                    abstract identifier: string with get, set
                    /// <summary>
                    /// Type of schedule for one-time execution at a specific time
                    /// </summary>
                    abstract ``type``: string with get, set
                    /// <summary>
                    /// Timestamp when the task should execute
                    /// </summary>
                    abstract time: float with get, set
                    [<ParamObject; Emit("$0")>]
                    static member Create (id: string, callback: string, payload: 'T, identifier: string, ``type``: string, time: float) : Item2<'T> = jsNative

                [<Interface>]
                type Item3<'T> =
                    /// <summary>
                    /// Unique identifier for the schedule
                    /// </summary>
                    abstract id: string with get, set
                    /// <summary>
                    /// Name of the method to be called
                    /// </summary>
                    abstract callback: string with get, set
                    /// <summary>
                    /// Data to be passed to the callback
                    /// </summary>
                    abstract payload: 'T with get, set
                    /// <summary>
                    /// Actor identifier
                    /// </summary>
                    abstract identifier: string with get, set
                    /// <summary>
                    /// Type of schedule for delayed execution
                    /// </summary>
                    abstract ``type``: string with get, set
                    /// <summary>
                    /// Timestamp when the task should execute
                    /// </summary>
                    abstract time: float with get, set
                    /// <summary>
                    /// Number of seconds to delay execution
                    /// </summary>
                    abstract delayInSeconds: float with get, set
                    [<ParamObject; Emit("$0")>]
                    static member Create (id: string, callback: string, payload: 'T, identifier: string, ``type``: string, time: float, delayInSeconds: float) : Item3<'T> = jsNative

                [<Interface>]
                type Item4<'T> =
                    /// <summary>
                    /// Unique identifier for the schedule
                    /// </summary>
                    abstract id: string with get, set
                    /// <summary>
                    /// Name of the method to be called
                    /// </summary>
                    abstract callback: string with get, set
                    /// <summary>
                    /// Data to be passed to the callback
                    /// </summary>
                    abstract payload: 'T with get, set
                    /// <summary>
                    /// Actor identifier
                    /// </summary>
                    abstract identifier: string with get, set
                    /// <summary>
                    /// Type of schedule for recurring execution based on cron expression
                    /// </summary>
                    abstract ``type``: string with get, set
                    /// <summary>
                    /// Timestamp for the next execution
                    /// </summary>
                    abstract time: float with get, set
                    /// <summary>
                    /// Cron expression defining the schedule
                    /// </summary>
                    abstract cron: string with get, set
                    [<ParamObject; Emit("$0")>]
                    static member Create (id: string, callback: string, payload: 'T, identifier: string, ``type``: string, time: float, cron: string) : Item4<'T> = jsNative

module Entrypoint =
    module Fetch =
        module Request =
            type Item<'HostMetadata> =
                /// <summary>
                /// <a href="https://www.iana.org/assignments/as-numbers/as-numbers.xhtml">ASN</a> of the incoming request.
                /// </summary>
                /// <example><c>395747</c></example>
                abstract asn: float option with get, set
                /// <summary>
                /// The organization which owns the ASN of the incoming request.
                /// </summary>
                /// <example><c>"Google Cloud"</c></example>
                abstract asOrganization: string option with get, set
                /// <summary>
                /// The original value of the <c>Accept-Encoding</c> header if Cloudflare modified it.
                /// </summary>
                /// <example><c>"gzip, deflate, br"</c></example>
                abstract clientAcceptEncoding: string option with get, set
                /// <summary>
                /// The number of milliseconds it took for the request to reach your worker.
                /// </summary>
                /// <example><c>22</c></example>
                abstract clientTcpRtt: float option with get, set
                /// <summary>
                /// The three-letter <a href="https://en.wikipedia.org/wiki/IATA_airport_code">IATA</a>
                /// airport code of the data center that the request hit.
                /// </summary>
                /// <example><c>"DFW"</c></example>
                abstract colo: string with get, set
                /// <summary>
                /// Represents the upstream's response to a
                /// <a href="https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html">TCP <c>keepalive</c> message</a>
                /// from cloudflare.
                /// <br /><br />
                /// For workers with no upstream, this will always be <c>1</c>.
                /// </summary>
                /// <example><c>3</c></example>
                abstract edgeRequestKeepAliveStatus: IncomingRequestCfPropertiesEdgeRequestKeepAliveStatus with get, set
                /// <summary>
                /// The HTTP Protocol the request used.
                /// </summary>
                /// <example><c>"HTTP/2"</c></example>
                abstract httpProtocol: string with get, set
                /// <summary>
                /// The browser-requested prioritization information in the request object.
                /// <br /><br />
                /// If no information was set, defaults to the empty string <c>""</c>
                /// </summary>
                /// <example><c>"weight=192;exclusive=0;group=3;group-weight=127"</c></example>
                /// <defaultValue>""</defaultValue>
                abstract requestPriority: string with get, set
                /// <summary>
                /// The TLS version of the connection to Cloudflare.
                /// In requests served over plaintext (without TLS), this property is the empty string <c>""</c>.
                /// </summary>
                /// <example><c>"TLSv1.3"</c></example>
                abstract tlsVersion: string with get, set
                /// <summary>
                /// The cipher for the connection to Cloudflare.
                /// In requests served over plaintext (without TLS), this property is the empty string <c>""</c>.
                /// </summary>
                /// <example><c>"AEAD-AES128-GCM-SHA256"</c></example>
                abstract tlsCipher: string with get, set
                /// <summary>
                /// Metadata containing the <a href="https://www.rfc-editor.org/rfc/rfc5246#section-7.4.1.2"><c>HELLO</c></a> and <a href="https://www.rfc-editor.org/rfc/rfc5246#section-7.4.9"><c>FINISHED</c></a> messages from this request's TLS handshake.
                /// <br /><br />
                /// If the incoming request was served over plaintext (without TLS) this field is undefined.
                /// </summary>
                abstract tlsExportedAuthenticator: obj option with get, set
                /// <summary>
                /// Results of Cloudflare's Bot Management analysis
                /// </summary>
                abstract botManagement: Entrypoint.Fetch.Request.Item.BotManagement with get, set
                /// <summary>
                /// Duplicate of <c>botManagement.score</c>.
                /// </summary>
                /// <remarks>@deprecated</remarks>
                abstract clientTrustScore: float with get, set
                /// <summary>
                /// Custom metadata set per-host in <a href="https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/">Cloudflare for SaaS</a>.
                /// <br /><br />
                /// This field is only present if you have Cloudflare for SaaS enabled on your account
                /// and you have followed the <a href="(https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/domain-support/custom-metadata/">required steps to enable it</a>).
                /// </summary>
                abstract hostMetadata: 'HostMetadata option with get, set
                /// <summary>
                /// The <a href="https://www.iso.org/iso-3166-country-codes.html">ISO 3166-1 Alpha 2</a> country code the request originated from.
                /// <br /><br />
                /// If your worker is <a href="https://support.cloudflare.com/hc/en-us/articles/203306930-Understanding-Cloudflare-Tor-support-and-Onion-Routing">configured to accept TOR connections</a>, this may also be <c>"T1"</c>, indicating a request that originated over TOR.
                /// <br /><br />
                /// If Cloudflare is unable to determine where the request originated this property is omitted.
                /// <br /><br />
                /// The country code <c>"T1"</c> is used for requests originating on TOR.
                /// </summary>
                /// <example><c>"GB"</c></example>
                abstract country: Entrypoint.Fetch.Request.Item.Country option with get, set
                /// <summary>
                /// If present, this property indicates that the request originated in the EU
                /// </summary>
                /// <example><c>"1"</c></example>
                abstract isEUCountry: string option with get, set
                /// <summary>
                /// A two-letter code indicating the continent the request originated from.
                /// </summary>
                /// <example><c>"AN"</c></example>
                abstract continent: ContinentCode option with get, set
                /// <summary>
                /// The city the request originated from
                /// </summary>
                /// <example><c>"Austin"</c></example>
                abstract city: string option with get, set
                /// <summary>
                /// Postal code of the incoming request
                /// </summary>
                /// <example><c>"78701"</c></example>
                abstract postalCode: string option with get, set
                /// <summary>
                /// Latitude of the incoming request
                /// </summary>
                /// <example><c>"30.27130"</c></example>
                abstract latitude: string option with get, set
                /// <summary>
                /// Longitude of the incoming request
                /// </summary>
                /// <example><c>"-97.74260"</c></example>
                abstract longitude: string option with get, set
                /// <summary>
                /// Timezone of the incoming request
                /// </summary>
                /// <example><c>"America/Chicago"</c></example>
                abstract timezone: string option with get, set
                /// <summary>
                /// If known, the ISO 3166-2 name for the first level region associated with
                /// the IP address of the incoming request
                /// </summary>
                /// <example><c>"Texas"</c></example>
                abstract region: string option with get, set
                /// <summary>
                /// If known, the ISO 3166-2 code for the first-level region associated with
                /// the IP address of the incoming request
                /// </summary>
                /// <example><c>"TX"</c></example>
                abstract regionCode: string option with get, set
                /// <summary>
                /// Metro code (DMA) of the incoming request
                /// </summary>
                /// <example><c>"635"</c></example>
                abstract metroCode: string option with get, set
                /// <summary>
                /// Information about the client certificate presented to Cloudflare.
                /// <br /><br />
                /// This is populated when the incoming request is served over TLS using
                /// either Cloudflare Access or API Shield (mTLS)
                /// and the presented SSL certificate has a valid
                /// <a href="https://ldapwiki.com/wiki/Certificate%20Serial%20Number">Certificate Serial Number</a>
                /// (i.e., not <c>null</c> or <c>""</c>).
                /// <br /><br />
                /// Otherwise, a set of placeholder values are used.
                /// <br /><br />
                /// The property <c>certPresented</c> will be set to <c>"1"</c> when
                /// the object is populated (i.e. the above conditions were met).
                /// </summary>
                abstract tlsClientAuth: obj with get, set
                [<EmitIndexer>]
                abstract Item: string -> obj with get, set

            module Item =
                [<Interface>]
                type BotManagement =
                    /// <summary>
                    /// Cloudflare’s <a href="https://developers.cloudflare.com/bots/concepts/bot-score/">level of certainty</a> that a request comes from a bot,
                    /// represented as an integer percentage between <c>1</c> (almost certainly a bot) and <c>99</c> (almost certainly human).
                    /// </summary>
                    /// <example><c>54</c></example>
                    abstract score: float with get, set
                    /// <summary>
                    /// A boolean value that is true if the request comes from a good bot, like Google or Bing.
                    /// Most customers choose to allow this traffic. For more details, see <a href="https://developers.cloudflare.com/firewall/known-issues-and-faq/#how-does-firewall-rules-handle-traffic-from-known-bots">Traffic from known bots</a>.
                    /// </summary>
                    abstract verifiedBot: bool with get, set
                    /// <summary>
                    /// A boolean value that is true if the request originates from a
                    /// Cloudflare-verified proxy service.
                    /// </summary>
                    abstract corporateProxy: bool with get, set
                    /// <summary>
                    /// A boolean value that's true if the request matches <a href="https://developers.cloudflare.com/bots/reference/static-resources/">file extensions</a> for many types of static resources.
                    /// </summary>
                    abstract staticResource: bool with get, set
                    /// <summary>
                    /// List of IDs that correlate to the Bot Management heuristic detections made on a request (you can have multiple heuristic detections on the same request).
                    /// </summary>
                    abstract detectionIds: float[] with get, set
                    /// <summary>
                    /// A <a href="https://developers.cloudflare.com/bots/concepts/ja3-fingerprint/">JA3 Fingerprint</a> to help profile specific SSL/TLS clients
                    /// across different destination IPs, Ports, and X509 certificates.
                    /// </summary>
                    abstract ja3Hash: string with get, set
                    [<ParamObject; Emit("$0")>]
                    static member Create (score: float, verifiedBot: bool, corporateProxy: bool, staticResource: bool, detectionIds: float[], ja3Hash: string) : BotManagement = jsNative

                [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
                type Country =
                    | AD
                    | AE
                    | AF
                    | AG
                    | AI
                    | AL
                    | AM
                    | AO
                    | AQ
                    | AR
                    | AS
                    | AT
                    | AU
                    | AW
                    | AX
                    | AZ
                    | BA
                    | BB
                    | BD
                    | BE
                    | BF
                    | BG
                    | BH
                    | BI
                    | BJ
                    | BL
                    | BM
                    | BN
                    | BO
                    | BQ
                    | BR
                    | BS
                    | BT
                    | BV
                    | BW
                    | BY
                    | BZ
                    | CA
                    | CC
                    | CD
                    | CF
                    | CG
                    | CH
                    | CI
                    | CK
                    | CL
                    | CM
                    | CN
                    | CO
                    | CR
                    | CU
                    | CV
                    | CW
                    | CX
                    | CY
                    | CZ
                    | DE
                    | DJ
                    | DK
                    | DM
                    | DO
                    | DZ
                    | EC
                    | EE
                    | EG
                    | EH
                    | ER
                    | ES
                    | ET
                    | FI
                    | FJ
                    | FK
                    | FM
                    | FO
                    | FR
                    | GA
                    | GB
                    | GD
                    | GE
                    | GF
                    | GG
                    | GH
                    | GI
                    | GL
                    | GM
                    | GN
                    | GP
                    | GQ
                    | GR
                    | GS
                    | GT
                    | GU
                    | GW
                    | GY
                    | HK
                    | HM
                    | HN
                    | HR
                    | HT
                    | HU
                    | ID
                    | IE
                    | IL
                    | IM
                    | IN
                    | IO
                    | IQ
                    | IR
                    | IS
                    | IT
                    | JE
                    | JM
                    | JO
                    | JP
                    | KE
                    | KG
                    | KH
                    | KI
                    | KM
                    | KN
                    | KP
                    | KR
                    | KW
                    | KY
                    | KZ
                    | LA
                    | LB
                    | LC
                    | LI
                    | LK
                    | LR
                    | LS
                    | LT
                    | LU
                    | LV
                    | LY
                    | MA
                    | MC
                    | MD
                    | ME
                    | MF
                    | MG
                    | MH
                    | MK
                    | ML
                    | MM
                    | MN
                    | MO
                    | MP
                    | MQ
                    | MR
                    | MS
                    | MT
                    | MU
                    | MV
                    | MW
                    | MX
                    | MY
                    | MZ
                    | NA
                    | NC
                    | NE
                    | NF
                    | NG
                    | NI
                    | NL
                    | NO
                    | NP
                    | NR
                    | NU
                    | NZ
                    | OM
                    | PA
                    | PE
                    | PF
                    | PG
                    | PH
                    | PK
                    | PL
                    | PM
                    | PN
                    | PR
                    | PS
                    | PT
                    | PW
                    | PY
                    | QA
                    | RE
                    | RO
                    | RS
                    | RU
                    | RW
                    | SA
                    | SB
                    | SC
                    | SD
                    | SE
                    | SG
                    | SH
                    | SI
                    | SJ
                    | SK
                    | SL
                    | SM
                    | SN
                    | SO
                    | SR
                    | SS
                    | ST
                    | SV
                    | SX
                    | SY
                    | SZ
                    | T1
                    | TC
                    | TD
                    | TF
                    | TG
                    | TH
                    | TJ
                    | TK
                    | TL
                    | TM
                    | TN
                    | TO
                    | TR
                    | TT
                    | TV
                    | TW
                    | TZ
                    | UA
                    | UG
                    | UM
                    | US
                    | UY
                    | UZ
                    | VA
                    | VC
                    | VE
                    | VG
                    | VI
                    | VN
                    | VU
                    | WF
                    | WS
                    | YE
                    | YT
                    | ZA
                    | ZM
                    | ZW

module Handler =
    type InputConstructor<'E> =
        [<EmitConstructor>]
        abstract Create: state: obj * env: 'E -> obj

    [<Interface>]
    type Opts =
        abstract track: Handler.Opts.Track option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (?track: Handler.Opts.Track) : Opts = jsNative

    [<Interface>]
    type Result<'E> =
        abstract fetch: request: obj * env: 'E * ctx: obj -> JS.Promise<obj>
        [<ParamObject; Emit("$0")>]
        static member Create (fetch: Func<obj, 'E, obj, JS.Promise<obj>>) : Result<'E> = jsNative

    module Input =
        [<Interface>]
        type Result =
            abstract fetch: request: obj -> JS.Promise<obj>
            [<ParamObject; Emit("$0")>]
            static member Create (fetch: (obj -> JS.Promise<obj>)) : Result = jsNative

        type ResultConstructor<'E> =
            [<EmitConstructor>]
            abstract Create: ctx: obj * env: 'E -> FSharp.CloudEdge.Runtime.Actors.Handler.Input.Result

    module Opts =
        [<Interface>]
        type Track =
            abstract enabled: bool with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (enabled: bool) : Track = jsNative

module SQLSchemaMigrations =
    module RunAll =
        module Result =
            [<Interface>]
            type Item =
                abstract rowsRead: float with get, set
                abstract rowsWritten: float with get, set
                [<ParamObject; Emit("$0")>]
                static member Create (rowsRead: float, rowsWritten: float) : Item = jsNative

module Sockets =
    module AcceptWebSocket =
        [<Interface>]
        type Result =
            abstract client: Sockets.Connections.Item with get, set
            abstract server: Sockets.Connections.Item with get, set
            [<ParamObject; Emit("$0")>]
            static member Create (client: Sockets.Connections.Item, server: Sockets.Connections.Item) : Result = jsNative

    module Connections =
        [<Interface>]
        type Item =
            abstract accept: ?options: obj -> unit
            /// <summary>
            /// The <b><c>WebSocket.send()</c></b> method enqueues the specified data to be transmitted to the server over the WebSocket connection, increasing the value of bufferedAmount by the number of bytes needed to contain the data. If the data can't be sent (for example, because it needs to be buffered but the buffer is full), the socket is closed automatically. The browser will throw an exception if you call send() when the connection is in the CONNECTING state. If you call send() when the connection is in the CLOSING or CLOSED states, the browser will silently discard the data.
            /// <br /><br />
            /// <a href="https://developer.mozilla.org/docs/Web/API/WebSocket/send">MDN Reference</a>
            /// </summary>
            abstract send: message: U3<string, JS.ArrayBuffer, JS.ArrayBufferView> -> unit
            /// <summary>
            /// The <b><c>WebSocket.close()</c></b> method closes the WebSocket connection or connection attempt, if any. If the connection is already CLOSED, this method does nothing.
            /// <br /><br />
            /// <a href="https://developer.mozilla.org/docs/Web/API/WebSocket/close">MDN Reference</a>
            /// </summary>
            abstract close: ?code: float * ?reason: string -> unit
            abstract serializeAttachment: (obj -> unit) with get, set
            abstract deserializeAttachment: (unit -> obj) with get, set
            /// <summary>
            /// The <b><c>WebSocket.readyState</c></b> read-only property returns the current state of the WebSocket connection.
            /// <br /><br />
            /// <a href="https://developer.mozilla.org/docs/Web/API/WebSocket/readyState">MDN Reference</a>
            /// </summary>
            abstract readyState: float with get, set
            /// <summary>
            /// The <b><c>WebSocket.url</c></b> read-only property returns the absolute URL of the WebSocket as resolved by the constructor.
            /// <br /><br />
            /// <a href="https://developer.mozilla.org/docs/Web/API/WebSocket/url">MDN Reference</a>
            /// </summary>
            abstract url: string option with get, set
            /// <summary>
            /// The <b><c>WebSocket.protocol</c></b> read-only property returns the name of the sub-protocol the server selected; this will be one of the strings specified in the protocols parameter when creating the WebSocket object, or the empty string if no connection is established.
            /// <br /><br />
            /// <a href="https://developer.mozilla.org/docs/Web/API/WebSocket/protocol">MDN Reference</a>
            /// </summary>
            abstract protocol: string option with get, set
            /// <summary>
            /// The <b><c>WebSocket.extensions</c></b> read-only property returns the extensions selected by the server. This is currently only the empty string or a list of extensions as negotiated by the connection.
            /// <br /><br />
            /// <a href="https://developer.mozilla.org/docs/Web/API/WebSocket/extensions">MDN Reference</a>
            /// </summary>
            abstract extensions: string option with get, set
            /// <summary>
            /// The <b><c>WebSocket.binaryType</c></b> property controls the type of binary data being received over the WebSocket connection.
            /// <br /><br />
            /// <a href="https://developer.mozilla.org/docs/Web/API/WebSocket/binaryType">MDN Reference</a>
            /// </summary>
            abstract binaryType: Sockets.Connections.Item.BinaryType with get, set
            /// <summary>
            /// The <b><c>addEventListener()</c></b> method of the EventTarget interface sets up a function that will be called whenever the specified event is delivered to the target.
            /// <br /><br />
            /// <a href="https://developer.mozilla.org/docs/Web/API/EventTarget/addEventListener">MDN Reference</a>
            /// </summary>
            abstract addEventListener<'Type>: ``type``: 'Type * handler: obj * ?options: obj -> unit
            /// <summary>
            /// The <b><c>removeEventListener()</c></b> method of the EventTarget interface removes an event listener previously registered with EventTarget.addEventListener() from the target. The event listener to be removed is identified using a combination of the event type, the event listener function itself, and various optional options that may affect the matching process; see Matching event listeners for removal.
            /// <br /><br />
            /// <a href="https://developer.mozilla.org/docs/Web/API/EventTarget/removeEventListener">MDN Reference</a>
            /// </summary>
            abstract removeEventListener<'Type>: ``type``: 'Type * handler: obj * ?options: obj -> unit
            /// <summary>
            /// The <b><c>dispatchEvent()</c></b> method of the EventTarget sends an Event to the object, (synchronously) invoking the affected event listeners in the appropriate order. The normal event processing rules (including the capturing and optional bubbling phase) also apply to events dispatched manually with dispatchEvent().
            /// <br /><br />
            /// <a href="https://developer.mozilla.org/docs/Web/API/EventTarget/dispatchEvent">MDN Reference</a>
            /// </summary>
            abstract dispatchEvent: ``event``: obj -> bool
            [<ParamObject; Emit("$0")>]
            static member Create (accept: (obj option -> unit), send: (U3<string, JS.ArrayBuffer, JS.ArrayBufferView> -> unit), close: Action<float option, string option>, serializeAttachment: (obj -> unit), deserializeAttachment: (unit -> obj), readyState: float, binaryType: Sockets.Connections.Item.BinaryType, addEventListener: Action<'Type, obj, obj option>, removeEventListener: Action<'Type, obj, obj option>, dispatchEvent: (obj -> bool), ?url: string, ?protocol: string, ?extensions: string) : Item = jsNative

        module Item =
            [<RequireQualifiedAccess; StringEnum(CaseRules.None)>]
            type BinaryType =
                | [<CompiledName("arraybuffer")>] Arraybuffer
                | [<CompiledName("blob")>] Blob

/// <summary>@cloudflare/actors/storage</summary>
module Storage =
    /// <summary>
    /// Represents a single SQL query request with optional parameters.
    /// </summary>
    [<Interface>]
    type QueryRequest =
        abstract sql: string with get, set
        abstract ``params``: obj[] option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (sql: string, ?``params``: obj[]) : QueryRequest = jsNative

    /// <summary>
    /// Handler class for executing SQL queries and transactions against a SQL storage backend.
    /// Provides methods for executing single queries and transactions with proper error handling
    /// and result formatting.
    /// <br /><br />
    /// This class also provides access to methods from the underlying DurableObjectStorage
    /// through the proxy pattern.
    /// </summary>
    [<Interface>]
    type Storage =
        abstract raw: obj option with get, set
        abstract sqlStorage: SqlStorage option with get, set
        abstract _migrationsArray: obj with get, set
        abstract hasRanMigrations: bool with get, set
        /// <summary>
        /// Gets the current migrations array
        /// Sets the migrations array and updates the SQLSchemaMigrations instance if available
        /// </summary>
        abstract migrations: SQLSchemaMigration[] with get, set
        abstract _migrations: SQLSchemaMigrations option with get, set
        /// <summary>
        /// Executes a raw SQL query with optional parameters.
        /// </summary>
        /// <param name="opts">- Options containing the SQL query and optional parameters</param>
        /// <returns>Promise resolving to a cursor containing the query results</returns>
        /// <remarks>@throws Error if the SQL execution fails</remarks>
        abstract executeRawQuery: obj with get, set
        /// <summary>
        /// Execute SQL queries against the Agent's database
        /// </summary>
        /// <remarks>@template T Type of the returned rows</remarks>
        /// <param name="strings">SQL query template strings</param>
        /// <param name="values">Values to be inserted into the query</param>
        /// <returns>Array of query results</returns>
        abstract sql<'T>: strings: obj * [<ParamArray>] values: U3<string, float, bool> option[] -> 'T[]
        /// <summary>
        /// Executes a SQL query and formats the results based on the specified options.
        /// </summary>
        /// <param name="opts">- Options containing the SQL query, parameters, and result format preference</param>
        /// <returns>Promise resolving to either raw query results or formatted array</returns>
        abstract query: obj with get, set
        abstract runMigrations: unit -> JS.Promise<Storage.Storage.RunMigrations.Result.Item option>
        abstract __studio: cmd: StudioRequest -> JS.Promise<obj>
        [<ParamObject; Emit("$0")>]
        static member Create (_migrationsArray: obj, hasRanMigrations: bool, migrations: SQLSchemaMigration[], executeRawQuery: obj, sql: Func<obj, U3<string, float, bool> option[], 'T[]>, query: obj, runMigrations: (unit -> JS.Promise<Storage.Storage.RunMigrations.Result.Item option>), __studio: (StudioRequest -> JS.Promise<obj>), ?raw: obj, ?sqlStorage: SqlStorage, ?_migrations: SQLSchemaMigrations) : Storage = jsNative

    /// <summary>The package's value exports, each bound to its import.</summary>
    [<Erase>]
    type Exports =
        /// <summary>
        /// Handler class for executing SQL queries and transactions against a SQL storage backend.
        /// Provides methods for executing single queries and transactions with proper error handling
        /// and result formatting.
        /// <br /><br />
        /// This class also provides access to methods from the underlying DurableObjectStorage
        /// through the proxy pattern.
        /// </summary>
        [<Import("Storage", "@cloudflare/actors/storage"); EmitConstructor>]
        static member Storage (?storage: obj) : FSharp.CloudEdge.Runtime.Actors.Storage.Storage = jsNative

    module Storage =
        module RunMigrations =
            module Result =
                [<Interface>]
                type Item =
                    abstract rowsRead: float with get, set
                    abstract rowsWritten: float with get, set
                    [<ParamObject; Emit("$0")>]
                    static member Create (rowsRead: float, rowsWritten: float) : Item = jsNative

module TryNOptions =
    type IsRetryable = delegate of err: obj * nextAttempt: float -> bool

module TryWhile =
    type IsRetryable = delegate of err: obj * nextAttempt: float -> bool

    [<Interface>]
    type Options =
        abstract baseDelayMs: float option with get, set
        abstract maxDelayMs: float option with get, set
        abstract verbose: bool option with get, set
        [<ParamObject; Emit("$0")>]
        static member Create (?baseDelayMs: float, ?maxDelayMs: float, ?verbose: bool) : Options = jsNative

/// <summary>
/// Extended Actor class that provides additional functionality for Durable Objects.
/// This class adds SQL storage capabilities and browsing functionality to the base DurableObject.
/// </summary>
/// <remarks>@template E - The type of the environment object that will be available to the actor</remarks>
type ActorConstructor2 =
    /// <summary>
    /// Static method to extract an ID from a request URL. Default response "default".
    /// </summary>
    /// <param name="request">- The incoming request</param>
    /// <returns>The name string value defined by the client application to reference an instance</returns>
    abstract nameFromRequest: request: obj -> JS.Promise<string option>
    /// <summary>
    /// Static method to configure the actor.
    /// </summary>
    abstract configuration: (obj -> ActorConfiguration) with get, set
    /// <summary>
    /// Static method to get an actor instance by ID
    /// </summary>
    /// <param name="id">- The ID of the actor to get</param>
    /// <returns>The actor instance</returns>
    abstract get: id: string -> obj
    /// <summary>
    /// Extended Actor class that provides additional functionality for Durable Objects.
    /// This class adds SQL storage capabilities and browsing functionality to the base DurableObject.
    /// </summary>
    /// <remarks>@template E - The type of the environment object that will be available to the actor</remarks>
    [<EmitConstructor>]
    abstract Create<'E>: ?ctx: ActorState * ?env: 'E -> Actor<'E>
