<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ExampleKind>DotNet</ExampleKind>
  </PropertyGroup>
  <Import Project="../Examples.props" />
  <ItemGroup>
    <ProjectReference Include="$(CloudEdgeSrc)Core/FSharp.CloudEdge.Core.Api/FSharp.CloudEdge.Core.Api.fsproj" />
    <ProjectReference Include="$(CloudEdgeSrc)Tenancy/FSharp.CloudEdge.Tenancy/FSharp.CloudEdge.Tenancy.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="ClientSetup.fs" />
    <Compile Include="TokenCheck.fs" />
  </ItemGroup>
</Project>
