<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ExampleKind>DotNet</ExampleKind>
  </PropertyGroup>
  <Import Project="../Examples.props" />
  <ItemGroup>
    <PackageReference Include="FSharp.CloudEdge.Core.Api" Version="0.1.0" Condition="'$(CloudEdgeUseSource)' != 'true'" />
    <ProjectReference Include="$(CloudEdgeSrc)Core/FSharp.CloudEdge.Core.Api/FSharp.CloudEdge.Core.Api.fsproj" Condition="'$(CloudEdgeUseSource)' == 'true'" />
    <PackageReference Include="FSharp.CloudEdge.Tenancy" Version="0.1.0" Condition="'$(CloudEdgeUseSource)' != 'true'" />
    <ProjectReference Include="$(CloudEdgeSrc)Tenancy/FSharp.CloudEdge.Tenancy/FSharp.CloudEdge.Tenancy.fsproj" Condition="'$(CloudEdgeUseSource)' == 'true'" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="ClientSetup.fs" />
    <Compile Include="TokenCheck.fs" />
  </ItemGroup>
</Project>
